name: pulse-guard
networks:
  pulseguard:
    name: pulse-guard
volumes:
  postgres-data:
  redis-data:
  traefik-data:
services:
  postgres:
    image: postgres:17-alpine
    environment:
      PGPASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pulseguard
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${PG_DATABASE}", "-U", "${PG_USERNAME}"]
      timeout: 5s
      retries: 3
  redis:
    image: 'redis:alpine'
    volumes:
      - 'redis-data:/data'
    networks:
      - pulseguard
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  pulseguard:
    image: ghcr.io/denisakp/pulseguard@sha256:82486ef14514193e4643eeb7a18194dd65c87f3dda20b507729836a1a8624451
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pulseguard
    ports:
      - '${APP_PORT:-8080}:8080'
    environment:
      DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}
      REDIS_URL: ${REDIS_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
      DEFAULT_RECIPIENT_EMAIL: ${DEFAULT_RECIPIENT_EMAIL}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      retries: 3
      timeout: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pulseguard.rule=Host(`${PULSEGUARD_DOMAIN}`)"
      - "traefik.http.routers.pulseguard.entrypoints=websecure"
      - "traefik.http.routers.pulseguard.tls.certresolver=le"
      - "traefik.http.services.pulseguard.loadbalancer.server.port=${APP_PORT}"
  traefik:
    image: traefik:v3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - pulseguard
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt:/letsencrypt
      - $PWD/scripts/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    command:
      - "--api.dashboard=true"
      - "--logs.level=ERROR"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=pulseguard"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
