// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAPIKeysByUserID = `-- name: CountAPIKeysByUserID :one
SELECT COUNT(*) FROM api_keys WHERE user_id = ?
`

func (q *Queries) CountAPIKeysByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAPIKeysByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (
    id, created_at, updated_at, user_id, name, key_hash, key_prefix,
    scope, expires_at, last_used_at, last_used_ip, is_active
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAPIKeyParams struct {
	ID         string       `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	UserID     string       `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	KeyPrefix  string       `json:"key_prefix"`
	Scope      string       `json:"scope"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	LastUsedIp string       `json:"last_used_ip"`
	IsActive   int64        `json:"is_active"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scope,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.LastUsedIp,
		arg.IsActive,
	)
	return err
}

const findAPIKeyByIDForUser = `-- name: FindAPIKeyByIDForUser :one
SELECT id, created_at, updated_at, user_id, name, key_hash, key_prefix, scope, expires_at, last_used_at, last_used_ip, is_active FROM api_keys WHERE id = ? AND user_id = ?
`

type FindAPIKeyByIDForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) FindAPIKeyByIDForUser(ctx context.Context, arg FindAPIKeyByIDForUserParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, findAPIKeyByIDForUser, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.IsActive,
	)
	return i, err
}

const findAPIKeyByKeyHash = `-- name: FindAPIKeyByKeyHash :one
SELECT id, created_at, updated_at, user_id, name, key_hash, key_prefix, scope, expires_at, last_used_at, last_used_ip, is_active FROM api_keys WHERE key_hash = ?
`

func (q *Queries) FindAPIKeyByKeyHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, findAPIKeyByKeyHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.IsActive,
	)
	return i, err
}

const listAPIKeysByUserID = `-- name: ListAPIKeysByUserID :many
SELECT id, created_at, updated_at, user_id, name, key_hash, key_prefix, scope, expires_at, last_used_at, last_used_ip, is_active FROM api_keys
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUserID(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Scope,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET is_active = 0
WHERE id = ? AND user_id = ?
`

type RevokeAPIKeyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :execrows
UPDATE api_keys
SET last_used_at = ?, last_used_ip = ?
WHERE id = ?
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsedAt sql.NullTime `json:"last_used_at"`
	LastUsedIp string       `json:"last_used_ip"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, arg.LastUsedAt, arg.LastUsedIp, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
