// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlitesqlc

import (
	"context"
	"time"
)

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards (id, owner_id, name, scope, widgets, default_time_range, refresh_interval, visibility, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
RETURNING id, owner_id, name, scope, widgets, default_time_range, refresh_interval, visibility, created_at, updated_at
`

type CreateDashboardParams struct {
	ID               string    `json:"id"`
	OwnerID          string    `json:"owner_id"`
	Name             string    `json:"name"`
	Scope            string    `json:"scope"`
	Widgets          string    `json:"widgets"`
	DefaultTimeRange string    `json:"default_time_range"`
	RefreshInterval  string    `json:"refresh_interval"`
	Visibility       string    `json:"visibility"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRowContext(ctx, createDashboard,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Scope,
		arg.Widgets,
		arg.DefaultTimeRange,
		arg.RefreshInterval,
		arg.Visibility,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Scope,
		&i.Widgets,
		&i.DefaultTimeRange,
		&i.RefreshInterval,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDashboard = `-- name: DeleteDashboard :execrows
DELETE FROM dashboards WHERE id = ?1
`

func (q *Queries) DeleteDashboard(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDashboard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findDashboardByID = `-- name: FindDashboardByID :one
SELECT d.id, d.owner_id, u.name AS owner_name, d.name AS dashboard_name, d.scope, d.widgets, d.default_time_range, d.refresh_interval, d.visibility, d.created_at, d.updated_at
FROM dashboards d
JOIN users u ON u.id = d.owner_id
WHERE d.id = ?1
`

type FindDashboardByIDRow struct {
	ID               string    `json:"id"`
	OwnerID          string    `json:"owner_id"`
	OwnerName        string    `json:"owner_name"`
	DashboardName    string    `json:"dashboard_name"`
	Scope            string    `json:"scope"`
	Widgets          string    `json:"widgets"`
	DefaultTimeRange string    `json:"default_time_range"`
	RefreshInterval  string    `json:"refresh_interval"`
	Visibility       string    `json:"visibility"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) FindDashboardByID(ctx context.Context, id string) (FindDashboardByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findDashboardByID, id)
	var i FindDashboardByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OwnerName,
		&i.DashboardName,
		&i.Scope,
		&i.Widgets,
		&i.DefaultTimeRange,
		&i.RefreshInterval,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDashboards = `-- name: ListDashboards :many
SELECT d.id, d.owner_id, u.name AS owner_name, d.name AS dashboard_name, d.scope, d.widgets, d.default_time_range, d.refresh_interval, d.visibility, d.created_at, d.updated_at
FROM dashboards d
JOIN users u ON u.id = d.owner_id
ORDER BY d.updated_at DESC
LIMIT ?2 OFFSET ?1
`

type ListDashboardsParams struct {
	Off int64 `json:"off"`
	Lim int64 `json:"lim"`
}

type ListDashboardsRow struct {
	ID               string    `json:"id"`
	OwnerID          string    `json:"owner_id"`
	OwnerName        string    `json:"owner_name"`
	DashboardName    string    `json:"dashboard_name"`
	Scope            string    `json:"scope"`
	Widgets          string    `json:"widgets"`
	DefaultTimeRange string    `json:"default_time_range"`
	RefreshInterval  string    `json:"refresh_interval"`
	Visibility       string    `json:"visibility"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) ListDashboards(ctx context.Context, arg ListDashboardsParams) ([]ListDashboardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDashboards, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardsRow{}
	for rows.Next() {
		var i ListDashboardsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OwnerName,
			&i.DashboardName,
			&i.Scope,
			&i.Widgets,
			&i.DefaultTimeRange,
			&i.RefreshInterval,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboard = `-- name: UpdateDashboard :execrows
UPDATE dashboards
SET name = ?1, scope = ?2, widgets = ?3, default_time_range = ?4, refresh_interval = ?5, visibility = ?6, updated_at = ?7
WHERE id = ?8
`

type UpdateDashboardParams struct {
	Name             string    `json:"name"`
	Scope            string    `json:"scope"`
	Widgets          string    `json:"widgets"`
	DefaultTimeRange string    `json:"default_time_range"`
	RefreshInterval  string    `json:"refresh_interval"`
	Visibility       string    `json:"visibility"`
	UpdatedAt        time.Time `json:"updated_at"`
	ID               string    `json:"id"`
}

func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDashboard,
		arg.Name,
		arg.Scope,
		arg.Widgets,
		arg.DefaultTimeRange,
		arg.RefreshInterval,
		arg.Visibility,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDashboardWidgets = `-- name: UpdateDashboardWidgets :execrows
UPDATE dashboards
SET widgets = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateDashboardWidgetsParams struct {
	Widgets   string    `json:"widgets"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateDashboardWidgets(ctx context.Context, arg UpdateDashboardWidgetsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDashboardWidgets, arg.Widgets, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
