// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: escalation_policy.sql

package sqlitesqlc

import (
	"context"
	"time"
)

const createEscalationPolicy = `-- name: CreateEscalationPolicy :exec
INSERT INTO escalation_policies (id, name, scope_kind, scope_value, is_active, priority, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEscalationPolicyParams struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	ScopeKind  string    `json:"scope_kind"`
	ScopeValue string    `json:"scope_value"`
	IsActive   int64     `json:"is_active"`
	Priority   int64     `json:"priority"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreateEscalationPolicy(ctx context.Context, arg CreateEscalationPolicyParams) error {
	_, err := q.db.ExecContext(ctx, createEscalationPolicy,
		arg.ID,
		arg.Name,
		arg.ScopeKind,
		arg.ScopeValue,
		arg.IsActive,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createEscalationStep = `-- name: CreateEscalationStep :exec
INSERT INTO escalation_steps (id, policy_id, step_order, delay_minutes, channel_ids)
VALUES (?, ?, ?, ?, ?)
`

type CreateEscalationStepParams struct {
	ID           string `json:"id"`
	PolicyID     string `json:"policy_id"`
	StepOrder    int64  `json:"step_order"`
	DelayMinutes int64  `json:"delay_minutes"`
	ChannelIds   string `json:"channel_ids"`
}

func (q *Queries) CreateEscalationStep(ctx context.Context, arg CreateEscalationStepParams) error {
	_, err := q.db.ExecContext(ctx, createEscalationStep,
		arg.ID,
		arg.PolicyID,
		arg.StepOrder,
		arg.DelayMinutes,
		arg.ChannelIds,
	)
	return err
}

const deleteEscalationPolicy = `-- name: DeleteEscalationPolicy :execrows
DELETE FROM escalation_policies WHERE id = ?
`

func (q *Queries) DeleteEscalationPolicy(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEscalationPolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEscalationStepsByPolicy = `-- name: DeleteEscalationStepsByPolicy :exec
DELETE FROM escalation_steps WHERE policy_id = ?
`

func (q *Queries) DeleteEscalationStepsByPolicy(ctx context.Context, policyID string) error {
	_, err := q.db.ExecContext(ctx, deleteEscalationStepsByPolicy, policyID)
	return err
}

const findEscalationPolicyByID = `-- name: FindEscalationPolicyByID :one
SELECT id, name, scope_kind, scope_value, is_active, priority, created_at, updated_at FROM escalation_policies WHERE id = ?
`

func (q *Queries) FindEscalationPolicyByID(ctx context.Context, id string) (EscalationPolicy, error) {
	row := q.db.QueryRowContext(ctx, findEscalationPolicyByID, id)
	var i EscalationPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScopeKind,
		&i.ScopeValue,
		&i.IsActive,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEscalationPolicies = `-- name: ListEscalationPolicies :many
SELECT id, name, scope_kind, scope_value, is_active, priority, created_at, updated_at FROM escalation_policies ORDER BY priority ASC, created_at ASC
`

func (q *Queries) ListEscalationPolicies(ctx context.Context) ([]EscalationPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listEscalationPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EscalationPolicy{}
	for rows.Next() {
		var i EscalationPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ScopeKind,
			&i.ScopeValue,
			&i.IsActive,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscalationStepsByPolicy = `-- name: ListEscalationStepsByPolicy :many
SELECT id, policy_id, step_order, delay_minutes, channel_ids FROM escalation_steps WHERE policy_id = ? ORDER BY step_order ASC
`

func (q *Queries) ListEscalationStepsByPolicy(ctx context.Context, policyID string) ([]EscalationStep, error) {
	rows, err := q.db.QueryContext(ctx, listEscalationStepsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EscalationStep{}
	for rows.Next() {
		var i EscalationStep
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.StepOrder,
			&i.DelayMinutes,
			&i.ChannelIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEscalationPriority = `-- name: NextEscalationPriority :one
SELECT COALESCE(MAX(priority), 0) + 1 AS next FROM escalation_policies WHERE is_active = 1
`

func (q *Queries) NextEscalationPriority(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextEscalationPriority)
	var next int64
	err := row.Scan(&next)
	return next, err
}

const setEscalationPolicyPriority = `-- name: SetEscalationPolicyPriority :execrows
UPDATE escalation_policies
SET priority = ?, updated_at = ?
WHERE id = ?
`

type SetEscalationPolicyPriorityParams struct {
	Priority  int64     `json:"priority"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) SetEscalationPolicyPriority(ctx context.Context, arg SetEscalationPolicyPriorityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setEscalationPolicyPriority, arg.Priority, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEscalationPolicy = `-- name: UpdateEscalationPolicy :execrows
UPDATE escalation_policies
SET name = ?, scope_kind = ?, scope_value = ?, is_active = ?, priority = ?, updated_at = ?
WHERE id = ?
`

type UpdateEscalationPolicyParams struct {
	Name       string    `json:"name"`
	ScopeKind  string    `json:"scope_kind"`
	ScopeValue string    `json:"scope_value"`
	IsActive   int64     `json:"is_active"`
	Priority   int64     `json:"priority"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         string    `json:"id"`
}

func (q *Queries) UpdateEscalationPolicy(ctx context.Context, arg UpdateEscalationPolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEscalationPolicy,
		arg.Name,
		arg.ScopeKind,
		arg.ScopeValue,
		arg.IsActive,
		arg.Priority,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
