// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expiry_notification_log.sql

package sqlitesqlc

import (
	"context"
	"time"
)

const countExpiryNotificationLogsByKey = `-- name: CountExpiryNotificationLogsByKey :one
SELECT COUNT(*) FROM expiry_notification_logs
WHERE resource_id = ? AND expiry_type = ? AND threshold = ?
`

type CountExpiryNotificationLogsByKeyParams struct {
	ResourceID string `json:"resource_id"`
	ExpiryType string `json:"expiry_type"`
	Threshold  int64  `json:"threshold"`
}

func (q *Queries) CountExpiryNotificationLogsByKey(ctx context.Context, arg CountExpiryNotificationLogsByKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpiryNotificationLogsByKey, arg.ResourceID, arg.ExpiryType, arg.Threshold)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpiryNotificationLog = `-- name: CreateExpiryNotificationLog :exec
INSERT INTO expiry_notification_logs (
    id, resource_id, expiry_type, threshold, sent_at, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateExpiryNotificationLogParams struct {
	ID         string    `json:"id"`
	ResourceID string    `json:"resource_id"`
	ExpiryType string    `json:"expiry_type"`
	Threshold  int64     `json:"threshold"`
	SentAt     time.Time `json:"sent_at"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreateExpiryNotificationLog(ctx context.Context, arg CreateExpiryNotificationLogParams) error {
	_, err := q.db.ExecContext(ctx, createExpiryNotificationLog,
		arg.ID,
		arg.ResourceID,
		arg.ExpiryType,
		arg.Threshold,
		arg.SentAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiryNotificationLogsByResourceIDAndType = `-- name: DeleteExpiryNotificationLogsByResourceIDAndType :exec
DELETE FROM expiry_notification_logs
WHERE resource_id = ? AND expiry_type = ?
`

type DeleteExpiryNotificationLogsByResourceIDAndTypeParams struct {
	ResourceID string `json:"resource_id"`
	ExpiryType string `json:"expiry_type"`
}

func (q *Queries) DeleteExpiryNotificationLogsByResourceIDAndType(ctx context.Context, arg DeleteExpiryNotificationLogsByResourceIDAndTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiryNotificationLogsByResourceIDAndType, arg.ResourceID, arg.ExpiryType)
	return err
}

const deleteExpiryNotificationLogsOlderThan = `-- name: DeleteExpiryNotificationLogsOlderThan :exec
DELETE FROM expiry_notification_logs
WHERE sent_at < ?
`

func (q *Queries) DeleteExpiryNotificationLogsOlderThan(ctx context.Context, sentAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiryNotificationLogsOlderThan, sentAt)
	return err
}
