// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_event.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteHostEventsByHost = `-- name: DeleteHostEventsByHost :exec
DELETE FROM host_events WHERE host_id = ?1
`

func (q *Queries) DeleteHostEventsByHost(ctx context.Context, hostID string) error {
	_, err := q.db.ExecContext(ctx, deleteHostEventsByHost, hostID)
	return err
}

const deleteHostEventsOlderThan = `-- name: DeleteHostEventsOlderThan :execrows
DELETE FROM host_events WHERE occurred_at < ?1
`

// Retention. Deletion only, never decimation: a kernel event is rare and discrete,
// and thinning them would purge the records this feature exists to keep.
func (q *Queries) DeleteHostEventsOlderThan(ctx context.Context, occurredAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHostEventsOlderThan, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertHostEvent = `-- name: InsertHostEvent :exec
INSERT INTO host_events (id, host_id, occurred_at, kind, source, occurrences, detail)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertHostEventParams struct {
	ID          string         `json:"id"`
	HostID      string         `json:"host_id"`
	OccurredAt  time.Time      `json:"occurred_at"`
	Kind        string         `json:"kind"`
	Source      string         `json:"source"`
	Occurrences int64          `json:"occurrences"`
	Detail      sql.NullString `json:"detail"`
}

func (q *Queries) InsertHostEvent(ctx context.Context, arg InsertHostEventParams) error {
	_, err := q.db.ExecContext(ctx, insertHostEvent,
		arg.ID,
		arg.HostID,
		arg.OccurredAt,
		arg.Kind,
		arg.Source,
		arg.Occurrences,
		arg.Detail,
	)
	return err
}

const listHostEventsByHost = `-- name: ListHostEventsByHost :many
SELECT id, host_id, occurred_at, kind, source, occurrences, detail FROM host_events
WHERE host_id = ?1
ORDER BY occurred_at DESC
LIMIT ?2
`

type ListHostEventsByHostParams struct {
	HostID string `json:"host_id"`
	Limit  int64  `json:"limit"`
}

// Newest first: an operator opening a host page wants what just happened, and the
// index on (host_id, occurred_at DESC) serves exactly this.
func (q *Queries) ListHostEventsByHost(ctx context.Context, arg ListHostEventsByHostParams) ([]HostEvent, error) {
	rows, err := q.db.QueryContext(ctx, listHostEventsByHost, arg.HostID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostEvent{}
	for rows.Next() {
		var i HostEvent
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.OccurredAt,
			&i.Kind,
			&i.Source,
			&i.Occurrences,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostEventsInWindow = `-- name: ListHostEventsInWindow :many
SELECT id, host_id, occurred_at, kind, source, occurrences, detail FROM host_events
WHERE host_id = ?1 AND occurred_at >= ?2 AND occurred_at < ?3
ORDER BY occurred_at DESC
LIMIT ?4
`

type ListHostEventsInWindowParams struct {
	HostID       string    `json:"host_id"`
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
	Limit        int64     `json:"limit"`
}

// Events inside one incident's correlation window (spec 091). Half-open
// [from, to): an event exactly on the far edge belongs to one window and not two.
// Newest first, and bounded -- a storm-prone host can hold many rows in a
// six-minute window, and neither the sentence nor the served list grows with it.
// Served by the existing index on (host_id, occurred_at DESC); no new index.
func (q *Queries) ListHostEventsInWindow(ctx context.Context, arg ListHostEventsInWindowParams) ([]HostEvent, error) {
	rows, err := q.db.QueryContext(ctx, listHostEventsInWindow,
		arg.HostID,
		arg.OccurredAt,
		arg.OccurredAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostEvent{}
	for rows.Next() {
		var i HostEvent
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.OccurredAt,
			&i.Kind,
			&i.Source,
			&i.Occurrences,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
