// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_metric.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const aggregateHostMetricsInWindow = `-- name: AggregateHostMetricsInWindow :one
SELECT
    CAST(COALESCE(MAX(cpu_pct), 0.0) AS REAL) AS peak_cpu_pct,
    CAST(COALESCE(MAX(mem_pct), 0.0) AS REAL) AS peak_mem_pct,
    COUNT(*) AS sample_count
FROM host_metrics
WHERE host_id = ?1 AND sampled_at >= ?2 AND sampled_at <= ?3
`

type AggregateHostMetricsInWindowParams struct {
	HostID      string    `json:"host_id"`
	SampledAt   time.Time `json:"sampled_at"`
	SampledAt_2 time.Time `json:"sampled_at_2"`
}

type AggregateHostMetricsInWindowRow struct {
	PeakCpuPct  float64 `json:"peak_cpu_pct"`
	PeakMemPct  float64 `json:"peak_mem_pct"`
	SampleCount int64   `json:"sample_count"`
}

// Reduce a bounded correlation window to its peaks and sample count. The peaks
// are computed here rather than in Go so no numeric column ever crosses the wire
// (spec 089, FR-021). A window with no samples returns sample_count = 0; the
// caller turns that into an absent context, never a zero-filled one.
// The range predicate mirrors ListHostMetricsInRange exactly -- no strftime is
// needed for a plain comparison, only for extracting epoch seconds.
func (q *Queries) AggregateHostMetricsInWindow(ctx context.Context, arg AggregateHostMetricsInWindowParams) (AggregateHostMetricsInWindowRow, error) {
	row := q.db.QueryRowContext(ctx, aggregateHostMetricsInWindow, arg.HostID, arg.SampledAt, arg.SampledAt_2)
	var i AggregateHostMetricsInWindowRow
	err := row.Scan(&i.PeakCpuPct, &i.PeakMemPct, &i.SampleCount)
	return i, err
}

const decimateHostMetrics = `-- name: DecimateHostMetrics :execrows
DELETE FROM host_metrics
WHERE host_metrics.sampled_at < ?1
  AND host_metrics.id NOT IN (
    SELECT MIN(hm.id) FROM host_metrics hm
    WHERE hm.sampled_at < ?1
    GROUP BY hm.host_id, substr(hm.sampled_at, 1, 16)
  )
`

// Keep at most one sample per (host, minute) for rows older than the cutoff,
// deleting the rest. MIN(id) is the earliest ULID in each minute bucket;
// substr(sampled_at,1,16) buckets by 'YYYY-MM-DD HH:MM'.
func (q *Queries) DecimateHostMetrics(ctx context.Context, sampledAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, decimateHostMetrics, sampledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteHostMetricsByHost = `-- name: DeleteHostMetricsByHost :exec
DELETE FROM host_metrics WHERE host_id = ?
`

func (q *Queries) DeleteHostMetricsByHost(ctx context.Context, hostID string) error {
	_, err := q.db.ExecContext(ctx, deleteHostMetricsByHost, hostID)
	return err
}

const deleteHostMetricsOlderThan = `-- name: DeleteHostMetricsOlderThan :execrows
DELETE FROM host_metrics WHERE sampled_at < ?1
`

func (q *Queries) DeleteHostMetricsOlderThan(ctx context.Context, sampledAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHostMetricsOlderThan, sampledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertHostMetric = `-- name: InsertHostMetric :exec
INSERT INTO host_metrics (
    id, host_id, sampled_at, cpu_pct, mem_pct, net_in, net_out, disks
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertHostMetricParams struct {
	ID        string         `json:"id"`
	HostID    string         `json:"host_id"`
	SampledAt time.Time      `json:"sampled_at"`
	CpuPct    float64        `json:"cpu_pct"`
	MemPct    float64        `json:"mem_pct"`
	NetIn     int64          `json:"net_in"`
	NetOut    int64          `json:"net_out"`
	Disks     sql.NullString `json:"disks"`
}

func (q *Queries) InsertHostMetric(ctx context.Context, arg InsertHostMetricParams) error {
	_, err := q.db.ExecContext(ctx, insertHostMetric,
		arg.ID,
		arg.HostID,
		arg.SampledAt,
		arg.CpuPct,
		arg.MemPct,
		arg.NetIn,
		arg.NetOut,
		arg.Disks,
	)
	return err
}

const listHostDisksInWindow = `-- name: ListHostDisksInWindow :many
SELECT disks FROM host_metrics
WHERE host_id = ?1 AND sampled_at >= ?2 AND sampled_at <= ?3
  AND disks IS NOT NULL
`

type ListHostDisksInWindowParams struct {
	HostID      string    `json:"host_id"`
	SampledAt   time.Time `json:"sampled_at"`
	SampledAt_2 time.Time `json:"sampled_at_2"`
}

// The disks column only, for the same bounded window. Deliberately a narrow
// projection: disk usage is a stored document and nothing in this codebase
// reaches inside JSON from SQL on either dialect, so the worst mount is picked
// in Go (spec 089, FR-021a). Rows returned are bounded by the window.
func (q *Queries) ListHostDisksInWindow(ctx context.Context, arg ListHostDisksInWindowParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listHostDisksInWindow, arg.HostID, arg.SampledAt, arg.SampledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var disks sql.NullString
		if err := rows.Scan(&disks); err != nil {
			return nil, err
		}
		items = append(items, disks)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostMetricsInRange = `-- name: ListHostMetricsInRange :many
SELECT id, host_id, sampled_at, cpu_pct, mem_pct, net_in, net_out, disks FROM host_metrics
WHERE host_id = ?1 AND sampled_at >= ?2 AND sampled_at <= ?3
ORDER BY sampled_at ASC
`

type ListHostMetricsInRangeParams struct {
	HostID      string    `json:"host_id"`
	SampledAt   time.Time `json:"sampled_at"`
	SampledAt_2 time.Time `json:"sampled_at_2"`
}

func (q *Queries) ListHostMetricsInRange(ctx context.Context, arg ListHostMetricsInRangeParams) ([]HostMetric, error) {
	rows, err := q.db.QueryContext(ctx, listHostMetricsInRange, arg.HostID, arg.SampledAt, arg.SampledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostMetric{}
	for rows.Next() {
		var i HostMetric
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.SampledAt,
			&i.CpuPct,
			&i.MemPct,
			&i.NetIn,
			&i.NetOut,
			&i.Disks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
