// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incident_updates.sql

package sqlitesqlc

import (
	"context"
	"time"
)

const createIncidentUpdate = `-- name: CreateIncidentUpdate :exec
INSERT INTO incident_updates (
    id, incident_id, status, message, posted_by, posted_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateIncidentUpdateParams struct {
	ID         string    `json:"id"`
	IncidentID string    `json:"incident_id"`
	Status     string    `json:"status"`
	Message    string    `json:"message"`
	PostedBy   string    `json:"posted_by"`
	PostedAt   time.Time `json:"posted_at"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreateIncidentUpdate(ctx context.Context, arg CreateIncidentUpdateParams) error {
	_, err := q.db.ExecContext(ctx, createIncidentUpdate,
		arg.ID,
		arg.IncidentID,
		arg.Status,
		arg.Message,
		arg.PostedBy,
		arg.PostedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteIncidentUpdate = `-- name: DeleteIncidentUpdate :exec
DELETE FROM incident_updates WHERE id = ?
`

func (q *Queries) DeleteIncidentUpdate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIncidentUpdate, id)
	return err
}

const getIncidentUpdate = `-- name: GetIncidentUpdate :one
SELECT id, incident_id, status, message, posted_by, posted_at, created_at, updated_at
FROM incident_updates
WHERE id = ?
`

func (q *Queries) GetIncidentUpdate(ctx context.Context, id string) (IncidentUpdate, error) {
	row := q.db.QueryRowContext(ctx, getIncidentUpdate, id)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Message,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidentUpdates = `-- name: ListIncidentUpdates :many
SELECT id, incident_id, status, message, posted_by, posted_at, created_at, updated_at
FROM incident_updates
WHERE incident_id = ?
ORDER BY posted_at DESC
`

func (q *Queries) ListIncidentUpdates(ctx context.Context, incidentID string) ([]IncidentUpdate, error) {
	rows, err := q.db.QueryContext(ctx, listIncidentUpdates, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentUpdate{}
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Message,
			&i.PostedBy,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentUpdate = `-- name: UpdateIncidentUpdate :exec
UPDATE incident_updates
SET status = ?,
    message = ?,
    posted_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateIncidentUpdateParams struct {
	Status    string    `json:"status"`
	Message   string    `json:"message"`
	PostedAt  time.Time `json:"posted_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateIncidentUpdate(ctx context.Context, arg UpdateIncidentUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateIncidentUpdate,
		arg.Status,
		arg.Message,
		arg.PostedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
