// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incident_diagnostics.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const createIncidentDiagnostics = `-- name: CreateIncidentDiagnostics :one
INSERT INTO incident_diagnostics (
    id, created_at, updated_at, incident_id,
    request_method, request_url, request_headers, request_timeout,
    http_status_code, response_headers, response_body, response_size,
    failure_type, error_message, error_summary,
    total_duration, dns_duration, tls_duration, first_byte_duration,
    body_truncated, body_encoded,
    keyword, keyword_mode, keyword_found,
    icmp_available, icmp_reachable, icmp_rtt_ms, root_cause_hint
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, incident_id, request_method, request_url, request_headers, request_timeout, http_status_code, response_headers, response_body, response_size, failure_type, error_message, error_summary, total_duration, dns_duration, tls_duration, first_byte_duration, body_truncated, body_encoded, icmp_available, icmp_reachable, icmp_rtt_ms, root_cause_hint, keyword, keyword_mode, keyword_found
`

type CreateIncidentDiagnosticsParams struct {
	ID                string         `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	IncidentID        string         `json:"incident_id"`
	RequestMethod     string         `json:"request_method"`
	RequestUrl        string         `json:"request_url"`
	RequestHeaders    string         `json:"request_headers"`
	RequestTimeout    int64          `json:"request_timeout"`
	HttpStatusCode    int64          `json:"http_status_code"`
	ResponseHeaders   string         `json:"response_headers"`
	ResponseBody      string         `json:"response_body"`
	ResponseSize      int64          `json:"response_size"`
	FailureType       string         `json:"failure_type"`
	ErrorMessage      string         `json:"error_message"`
	ErrorSummary      string         `json:"error_summary"`
	TotalDuration     int64          `json:"total_duration"`
	DnsDuration       int64          `json:"dns_duration"`
	TlsDuration       int64          `json:"tls_duration"`
	FirstByteDuration int64          `json:"first_byte_duration"`
	BodyTruncated     int64          `json:"body_truncated"`
	BodyEncoded       int64          `json:"body_encoded"`
	Keyword           sql.NullString `json:"keyword"`
	KeywordMode       sql.NullString `json:"keyword_mode"`
	KeywordFound      sql.NullBool   `json:"keyword_found"`
	IcmpAvailable     sql.NullInt64  `json:"icmp_available"`
	IcmpReachable     sql.NullInt64  `json:"icmp_reachable"`
	IcmpRttMs         sql.NullInt64  `json:"icmp_rtt_ms"`
	RootCauseHint     string         `json:"root_cause_hint"`
}

func (q *Queries) CreateIncidentDiagnostics(ctx context.Context, arg CreateIncidentDiagnosticsParams) (IncidentDiagnostic, error) {
	row := q.db.QueryRowContext(ctx, createIncidentDiagnostics,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IncidentID,
		arg.RequestMethod,
		arg.RequestUrl,
		arg.RequestHeaders,
		arg.RequestTimeout,
		arg.HttpStatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ResponseSize,
		arg.FailureType,
		arg.ErrorMessage,
		arg.ErrorSummary,
		arg.TotalDuration,
		arg.DnsDuration,
		arg.TlsDuration,
		arg.FirstByteDuration,
		arg.BodyTruncated,
		arg.BodyEncoded,
		arg.Keyword,
		arg.KeywordMode,
		arg.KeywordFound,
		arg.IcmpAvailable,
		arg.IcmpReachable,
		arg.IcmpRttMs,
		arg.RootCauseHint,
	)
	var i IncidentDiagnostic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncidentID,
		&i.RequestMethod,
		&i.RequestUrl,
		&i.RequestHeaders,
		&i.RequestTimeout,
		&i.HttpStatusCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ResponseSize,
		&i.FailureType,
		&i.ErrorMessage,
		&i.ErrorSummary,
		&i.TotalDuration,
		&i.DnsDuration,
		&i.TlsDuration,
		&i.FirstByteDuration,
		&i.BodyTruncated,
		&i.BodyEncoded,
		&i.IcmpAvailable,
		&i.IcmpReachable,
		&i.IcmpRttMs,
		&i.RootCauseHint,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordFound,
	)
	return i, err
}

const deleteIncidentDiagnostics = `-- name: DeleteIncidentDiagnostics :execrows
DELETE FROM incident_diagnostics WHERE id = ?
`

func (q *Queries) DeleteIncidentDiagnostics(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIncidentDiagnostics, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findIncidentDiagnosticsByIncidentID = `-- name: FindIncidentDiagnosticsByIncidentID :one
SELECT id, created_at, updated_at, incident_id, request_method, request_url, request_headers, request_timeout, http_status_code, response_headers, response_body, response_size, failure_type, error_message, error_summary, total_duration, dns_duration, tls_duration, first_byte_duration, body_truncated, body_encoded, icmp_available, icmp_reachable, icmp_rtt_ms, root_cause_hint, keyword, keyword_mode, keyword_found FROM incident_diagnostics WHERE incident_id = ?
`

func (q *Queries) FindIncidentDiagnosticsByIncidentID(ctx context.Context, incidentID string) (IncidentDiagnostic, error) {
	row := q.db.QueryRowContext(ctx, findIncidentDiagnosticsByIncidentID, incidentID)
	var i IncidentDiagnostic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncidentID,
		&i.RequestMethod,
		&i.RequestUrl,
		&i.RequestHeaders,
		&i.RequestTimeout,
		&i.HttpStatusCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ResponseSize,
		&i.FailureType,
		&i.ErrorMessage,
		&i.ErrorSummary,
		&i.TotalDuration,
		&i.DnsDuration,
		&i.TlsDuration,
		&i.FirstByteDuration,
		&i.BodyTruncated,
		&i.BodyEncoded,
		&i.IcmpAvailable,
		&i.IcmpReachable,
		&i.IcmpRttMs,
		&i.RootCauseHint,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordFound,
	)
	return i, err
}

const updateIncidentDiagnostics = `-- name: UpdateIncidentDiagnostics :execrows
UPDATE incident_diagnostics
SET request_method = ?,
    request_url = ?,
    request_headers = ?,
    request_timeout = ?,
    http_status_code = ?,
    response_headers = ?,
    response_body = ?,
    response_size = ?,
    failure_type = ?,
    error_message = ?,
    error_summary = ?,
    total_duration = ?,
    dns_duration = ?,
    tls_duration = ?,
    first_byte_duration = ?,
    body_truncated = ?,
    body_encoded = ?,
    keyword = ?,
    keyword_mode = ?,
    keyword_found = ?,
    icmp_available = ?,
    icmp_reachable = ?,
    icmp_rtt_ms = ?,
    root_cause_hint = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateIncidentDiagnosticsParams struct {
	RequestMethod     string         `json:"request_method"`
	RequestUrl        string         `json:"request_url"`
	RequestHeaders    string         `json:"request_headers"`
	RequestTimeout    int64          `json:"request_timeout"`
	HttpStatusCode    int64          `json:"http_status_code"`
	ResponseHeaders   string         `json:"response_headers"`
	ResponseBody      string         `json:"response_body"`
	ResponseSize      int64          `json:"response_size"`
	FailureType       string         `json:"failure_type"`
	ErrorMessage      string         `json:"error_message"`
	ErrorSummary      string         `json:"error_summary"`
	TotalDuration     int64          `json:"total_duration"`
	DnsDuration       int64          `json:"dns_duration"`
	TlsDuration       int64          `json:"tls_duration"`
	FirstByteDuration int64          `json:"first_byte_duration"`
	BodyTruncated     int64          `json:"body_truncated"`
	BodyEncoded       int64          `json:"body_encoded"`
	Keyword           sql.NullString `json:"keyword"`
	KeywordMode       sql.NullString `json:"keyword_mode"`
	KeywordFound      sql.NullBool   `json:"keyword_found"`
	IcmpAvailable     sql.NullInt64  `json:"icmp_available"`
	IcmpReachable     sql.NullInt64  `json:"icmp_reachable"`
	IcmpRttMs         sql.NullInt64  `json:"icmp_rtt_ms"`
	RootCauseHint     string         `json:"root_cause_hint"`
	UpdatedAt         time.Time      `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateIncidentDiagnostics(ctx context.Context, arg UpdateIncidentDiagnosticsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateIncidentDiagnostics,
		arg.RequestMethod,
		arg.RequestUrl,
		arg.RequestHeaders,
		arg.RequestTimeout,
		arg.HttpStatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ResponseSize,
		arg.FailureType,
		arg.ErrorMessage,
		arg.ErrorSummary,
		arg.TotalDuration,
		arg.DnsDuration,
		arg.TlsDuration,
		arg.FirstByteDuration,
		arg.BodyTruncated,
		arg.BodyEncoded,
		arg.Keyword,
		arg.KeywordMode,
		arg.KeywordFound,
		arg.IcmpAvailable,
		arg.IcmpReachable,
		arg.IcmpRttMs,
		arg.RootCauseHint,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
