// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const createMaintenance = `-- name: CreateMaintenance :exec
INSERT INTO maintenances (
    id, created_at, updated_at, title, description, strategy, status,
    start_at, end_at, cron_expr, window_minutes, timezone,
    effective_from, effective_until, started_at, ended_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMaintenanceParams struct {
	ID             string         `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Strategy       string         `json:"strategy"`
	Status         string         `json:"status"`
	StartAt        sql.NullTime   `json:"start_at"`
	EndAt          sql.NullTime   `json:"end_at"`
	CronExpr       sql.NullString `json:"cron_expr"`
	WindowMinutes  sql.NullInt64  `json:"window_minutes"`
	Timezone       sql.NullString `json:"timezone"`
	EffectiveFrom  sql.NullTime   `json:"effective_from"`
	EffectiveUntil sql.NullTime   `json:"effective_until"`
	StartedAt      sql.NullTime   `json:"started_at"`
	EndedAt        sql.NullTime   `json:"ended_at"`
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) error {
	_, err := q.db.ExecContext(ctx, createMaintenance,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.Strategy,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.CronExpr,
		arg.WindowMinutes,
		arg.Timezone,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const deleteMaintenance = `-- name: DeleteMaintenance :execrows
DELETE FROM maintenances WHERE id = ?
`

func (q *Queries) DeleteMaintenance(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMaintenance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findActiveMaintenancesForResource = `-- name: FindActiveMaintenancesForResource :many
SELECT DISTINCT m.id, m.created_at, m.updated_at, m.title, m.description, m.strategy, m.status, m.start_at, m.end_at, m.cron_expr, m.window_minutes, m.timezone, m.effective_from, m.effective_until, m.started_at, m.ended_at FROM maintenances m
JOIN maintenance_resources mr ON mr.maintenance_id = m.id
WHERE mr.resource_id = ?
  AND (
    m.status = 'active'
    OR (m.strategy = 'one_time' AND m.status = 'scheduled' AND m.start_at <= ? AND m.end_at >= ?)
  )
`

type FindActiveMaintenancesForResourceParams struct {
	ResourceID string       `json:"resource_id"`
	StartAt    sql.NullTime `json:"start_at"`
	EndAt      sql.NullTime `json:"end_at"`
}

func (q *Queries) FindActiveMaintenancesForResource(ctx context.Context, arg FindActiveMaintenancesForResourceParams) ([]Maintenance, error) {
	rows, err := q.db.QueryContext(ctx, findActiveMaintenancesForResource, arg.ResourceID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Strategy,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CronExpr,
			&i.WindowMinutes,
			&i.Timezone,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMaintenanceByID = `-- name: FindMaintenanceByID :one
SELECT id, created_at, updated_at, title, description, strategy, status, start_at, end_at, cron_expr, window_minutes, timezone, effective_from, effective_until, started_at, ended_at FROM maintenances WHERE id = ?
`

func (q *Queries) FindMaintenanceByID(ctx context.Context, id string) (Maintenance, error) {
	row := q.db.QueryRowContext(ctx, findMaintenanceByID, id)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.Strategy,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CronExpr,
		&i.WindowMinutes,
		&i.Timezone,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const linkMaintenanceResource = `-- name: LinkMaintenanceResource :exec
INSERT INTO maintenance_resources (maintenance_id, resource_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type LinkMaintenanceResourceParams struct {
	MaintenanceID string `json:"maintenance_id"`
	ResourceID    string `json:"resource_id"`
}

func (q *Queries) LinkMaintenanceResource(ctx context.Context, arg LinkMaintenanceResourceParams) error {
	_, err := q.db.ExecContext(ctx, linkMaintenanceResource, arg.MaintenanceID, arg.ResourceID)
	return err
}

const listMaintenanceResourceIDsByMaintenanceID = `-- name: ListMaintenanceResourceIDsByMaintenanceID :many
SELECT resource_id FROM maintenance_resources WHERE maintenance_id = ?
`

func (q *Queries) ListMaintenanceResourceIDsByMaintenanceID(ctx context.Context, maintenanceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceResourceIDsByMaintenanceID, maintenanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource_id string
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenancesAll = `-- name: ListMaintenancesAll :many
SELECT id, created_at, updated_at, title, description, strategy, status, start_at, end_at, cron_expr, window_minutes, timezone, effective_from, effective_until, started_at, ended_at FROM maintenances ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListMaintenancesAllParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMaintenancesAll(ctx context.Context, arg ListMaintenancesAllParams) ([]Maintenance, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenancesAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Strategy,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CronExpr,
			&i.WindowMinutes,
			&i.Timezone,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenancesByStatus = `-- name: ListMaintenancesByStatus :many
SELECT id, created_at, updated_at, title, description, strategy, status, start_at, end_at, cron_expr, window_minutes, timezone, effective_from, effective_until, started_at, ended_at FROM maintenances WHERE status = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListMaintenancesByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListMaintenancesByStatus(ctx context.Context, arg ListMaintenancesByStatusParams) ([]Maintenance, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenancesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Strategy,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CronExpr,
			&i.WindowMinutes,
			&i.Timezone,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkMaintenanceResource = `-- name: UnlinkMaintenanceResource :exec
DELETE FROM maintenance_resources WHERE maintenance_id = ? AND resource_id = ?
`

type UnlinkMaintenanceResourceParams struct {
	MaintenanceID string `json:"maintenance_id"`
	ResourceID    string `json:"resource_id"`
}

func (q *Queries) UnlinkMaintenanceResource(ctx context.Context, arg UnlinkMaintenanceResourceParams) error {
	_, err := q.db.ExecContext(ctx, unlinkMaintenanceResource, arg.MaintenanceID, arg.ResourceID)
	return err
}

const updateMaintenance = `-- name: UpdateMaintenance :exec
UPDATE maintenances
SET title = ?, description = ?, strategy = ?, status = ?,
    start_at = ?, end_at = ?, cron_expr = ?, window_minutes = ?, timezone = ?,
    effective_from = ?, effective_until = ?,
    started_at = ?, ended_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateMaintenanceParams struct {
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Strategy       string         `json:"strategy"`
	Status         string         `json:"status"`
	StartAt        sql.NullTime   `json:"start_at"`
	EndAt          sql.NullTime   `json:"end_at"`
	CronExpr       sql.NullString `json:"cron_expr"`
	WindowMinutes  sql.NullInt64  `json:"window_minutes"`
	Timezone       sql.NullString `json:"timezone"`
	EffectiveFrom  sql.NullTime   `json:"effective_from"`
	EffectiveUntil sql.NullTime   `json:"effective_until"`
	StartedAt      sql.NullTime   `json:"started_at"`
	EndedAt        sql.NullTime   `json:"ended_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenance,
		arg.Title,
		arg.Description,
		arg.Strategy,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.CronExpr,
		arg.WindowMinutes,
		arg.Timezone,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.StartedAt,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
