// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitoring_activity.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const avgResponseTimeByResourceInWindow = `-- name: AvgResponseTimeByResourceInWindow :one
SELECT AVG(response_time) FROM monitoring_activities
WHERE resource_id = ? AND created_at >= ? AND success = 1
`

type AvgResponseTimeByResourceInWindowParams struct {
	ResourceID string    `json:"resource_id"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) AvgResponseTimeByResourceInWindow(ctx context.Context, arg AvgResponseTimeByResourceInWindowParams) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, avgResponseTimeByResourceInWindow, arg.ResourceID, arg.CreatedAt)
	var avg sql.NullFloat64
	err := row.Scan(&avg)
	return avg, err
}

const avgResponseTimeByResourcesSince = `-- name: AvgResponseTimeByResourcesSince :many
SELECT resource_id, AVG(response_time) AS avg_ms
FROM monitoring_activities
WHERE created_at >= ?1
  AND success = 1
  AND resource_id IN (/*SLICE:resource_ids*/?)
GROUP BY resource_id
`

type AvgResponseTimeByResourcesSinceParams struct {
	Since       time.Time `json:"since"`
	ResourceIds []string  `json:"resource_ids"`
}

type AvgResponseTimeByResourcesSinceRow struct {
	ResourceID string          `json:"resource_id"`
	AvgMs      sql.NullFloat64 `json:"avg_ms"`
}

// One round-trip bulk avg grouped by resource. Used by the list path to
// enrich each resource with its avg response time over a sliding window (30d).
func (q *Queries) AvgResponseTimeByResourcesSince(ctx context.Context, arg AvgResponseTimeByResourcesSinceParams) ([]AvgResponseTimeByResourcesSinceRow, error) {
	query := avgResponseTimeByResourcesSince
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Since)
	if len(arg.ResourceIds) > 0 {
		for _, v := range arg.ResourceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", strings.Repeat(",?", len(arg.ResourceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvgResponseTimeByResourcesSinceRow{}
	for rows.Next() {
		var i AvgResponseTimeByResourcesSinceRow
		if err := rows.Scan(&i.ResourceID, &i.AvgMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMonitoringActivityByResourceSuccess = `-- name: CountMonitoringActivityByResourceSuccess :one
SELECT COUNT(*) FROM monitoring_activities
WHERE resource_id = ? AND created_at >= ? AND success = 1
`

type CountMonitoringActivityByResourceSuccessParams struct {
	ResourceID string    `json:"resource_id"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CountMonitoringActivityByResourceSuccess(ctx context.Context, arg CountMonitoringActivityByResourceSuccessParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonitoringActivityByResourceSuccess, arg.ResourceID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonitoringActivityByResourceTotal = `-- name: CountMonitoringActivityByResourceTotal :one
SELECT COUNT(*) FROM monitoring_activities WHERE resource_id = ? AND created_at >= ?
`

type CountMonitoringActivityByResourceTotalParams struct {
	ResourceID string    `json:"resource_id"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CountMonitoringActivityByResourceTotal(ctx context.Context, arg CountMonitoringActivityByResourceTotalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonitoringActivityByResourceTotal, arg.ResourceID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonitoringActivitySinceSuccess = `-- name: CountMonitoringActivitySinceSuccess :one
SELECT COUNT(*) FROM monitoring_activities WHERE created_at >= ? AND success = 1
`

func (q *Queries) CountMonitoringActivitySinceSuccess(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonitoringActivitySinceSuccess, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonitoringActivitySinceTotal = `-- name: CountMonitoringActivitySinceTotal :one
SELECT COUNT(*) FROM monitoring_activities WHERE created_at >= ?
`

func (q *Queries) CountMonitoringActivitySinceTotal(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonitoringActivitySinceTotal, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMonitoringActivity = `-- name: CreateMonitoringActivity :exec
INSERT INTO monitoring_activities (
    id, created_at, updated_at, resource_id, message, success,
    response_time, response_data, is_maintenance
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMonitoringActivityParams struct {
	ID            string    `json:"id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	ResourceID    string    `json:"resource_id"`
	Message       string    `json:"message"`
	Success       int64     `json:"success"`
	ResponseTime  int64     `json:"response_time"`
	ResponseData  []byte    `json:"response_data"`
	IsMaintenance int64     `json:"is_maintenance"`
}

func (q *Queries) CreateMonitoringActivity(ctx context.Context, arg CreateMonitoringActivityParams) error {
	_, err := q.db.ExecContext(ctx, createMonitoringActivity,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ResourceID,
		arg.Message,
		arg.Success,
		arg.ResponseTime,
		arg.ResponseData,
		arg.IsMaintenance,
	)
	return err
}

const findMonitoringActivitiesByResourceID = `-- name: FindMonitoringActivitiesByResourceID :many
SELECT id, created_at, updated_at, resource_id, message, success, response_time, response_data, is_maintenance FROM monitoring_activities
WHERE resource_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type FindMonitoringActivitiesByResourceIDParams struct {
	ResourceID string `json:"resource_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) FindMonitoringActivitiesByResourceID(ctx context.Context, arg FindMonitoringActivitiesByResourceIDParams) ([]MonitoringActivity, error) {
	rows, err := q.db.QueryContext(ctx, findMonitoringActivitiesByResourceID, arg.ResourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringActivity{}
	for rows.Next() {
		var i MonitoringActivity
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceID,
			&i.Message,
			&i.Success,
			&i.ResponseTime,
			&i.ResponseData,
			&i.IsMaintenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentResponseTimes = `-- name: GetRecentResponseTimes :many
SELECT created_at, response_time FROM monitoring_activities
WHERE resource_id = ? AND success = 1
ORDER BY created_at DESC
LIMIT ?
`

type GetRecentResponseTimesParams struct {
	ResourceID string `json:"resource_id"`
	Limit      int64  `json:"limit"`
}

type GetRecentResponseTimesRow struct {
	CreatedAt    time.Time `json:"created_at"`
	ResponseTime int64     `json:"response_time"`
}

func (q *Queries) GetRecentResponseTimes(ctx context.Context, arg GetRecentResponseTimesParams) ([]GetRecentResponseTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentResponseTimes, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentResponseTimesRow{}
	for rows.Next() {
		var i GetRecentResponseTimesRow
		if err := rows.Scan(&i.CreatedAt, &i.ResponseTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringActivities = `-- name: ListMonitoringActivities :many
SELECT id, created_at, updated_at, resource_id, message, success, response_time, response_data, is_maintenance FROM monitoring_activities
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListMonitoringActivitiesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMonitoringActivities(ctx context.Context, arg ListMonitoringActivitiesParams) ([]MonitoringActivity, error) {
	rows, err := q.db.QueryContext(ctx, listMonitoringActivities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringActivity{}
	for rows.Next() {
		var i MonitoringActivity
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceID,
			&i.Message,
			&i.Success,
			&i.ResponseTime,
			&i.ResponseData,
			&i.IsMaintenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMonitoringActivityHourlyAggregateInputs = `-- name: SelectMonitoringActivityHourlyAggregateInputs :many
SELECT created_at, success FROM monitoring_activities
WHERE resource_id = ? AND created_at >= ?
ORDER BY created_at ASC
`

type SelectMonitoringActivityHourlyAggregateInputsParams struct {
	ResourceID string    `json:"resource_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type SelectMonitoringActivityHourlyAggregateInputsRow struct {
	CreatedAt time.Time `json:"created_at"`
	Success   int64     `json:"success"`
}

func (q *Queries) SelectMonitoringActivityHourlyAggregateInputs(ctx context.Context, arg SelectMonitoringActivityHourlyAggregateInputsParams) ([]SelectMonitoringActivityHourlyAggregateInputsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectMonitoringActivityHourlyAggregateInputs, arg.ResourceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectMonitoringActivityHourlyAggregateInputsRow{}
	for rows.Next() {
		var i SelectMonitoringActivityHourlyAggregateInputsRow
		if err := rows.Scan(&i.CreatedAt, &i.Success); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMonitoringActivitySuccessInWindow = `-- name: SelectMonitoringActivitySuccessInWindow :many
SELECT success FROM monitoring_activities
WHERE resource_id = ? AND created_at >= ?
ORDER BY created_at ASC
`

type SelectMonitoringActivitySuccessInWindowParams struct {
	ResourceID string    `json:"resource_id"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) SelectMonitoringActivitySuccessInWindow(ctx context.Context, arg SelectMonitoringActivitySuccessInWindowParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, selectMonitoringActivitySuccessInWindow, arg.ResourceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var success int64
		if err := rows.Scan(&success); err != nil {
			return nil, err
		}
		items = append(items, success)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
