// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const claimNotificationEvent = `-- name: ClaimNotificationEvent :execrows
UPDATE notification_events
SET claim_owner = ?, claimed_at = ?
WHERE id = ?
  AND status = 'pending'
  AND (claim_owner IS NULL OR claim_owner = '')
`

type ClaimNotificationEventParams struct {
	ClaimOwner sql.NullString `json:"claim_owner"`
	ClaimedAt  sql.NullTime   `json:"claimed_at"`
	ID         string         `json:"id"`
}

func (q *Queries) ClaimNotificationEvent(ctx context.Context, arg ClaimNotificationEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimNotificationEvent, arg.ClaimOwner, arg.ClaimedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createNotificationEvent = `-- name: CreateNotificationEvent :exec
INSERT INTO notification_events (
    id, created_at, updated_at, incident_id, type,
    status, claim_owner, claimed_at, processed_at, last_error
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNotificationEventParams struct {
	ID          string         `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	IncidentID  string         `json:"incident_id"`
	Type        string         `json:"type"`
	Status      string         `json:"status"`
	ClaimOwner  sql.NullString `json:"claim_owner"`
	ClaimedAt   sql.NullTime   `json:"claimed_at"`
	ProcessedAt sql.NullTime   `json:"processed_at"`
	LastError   string         `json:"last_error"`
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationEvent,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IncidentID,
		arg.Type,
		arg.Status,
		arg.ClaimOwner,
		arg.ClaimedAt,
		arg.ProcessedAt,
		arg.LastError,
	)
	return err
}

const deleteNotificationEvent = `-- name: DeleteNotificationEvent :exec
DELETE FROM notification_events WHERE id = ?
`

func (q *Queries) DeleteNotificationEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationEvent, id)
	return err
}

const findNotificationEventByID = `-- name: FindNotificationEventByID :one
SELECT id, created_at, updated_at, incident_id, type, status, claim_owner, claimed_at, processed_at, last_error FROM notification_events WHERE id = ?
`

func (q *Queries) FindNotificationEventByID(ctx context.Context, id string) (NotificationEvent, error) {
	row := q.db.QueryRowContext(ctx, findNotificationEventByID, id)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncidentID,
		&i.Type,
		&i.Status,
		&i.ClaimOwner,
		&i.ClaimedAt,
		&i.ProcessedAt,
		&i.LastError,
	)
	return i, err
}

const findPendingNotificationEvents = `-- name: FindPendingNotificationEvents :many
SELECT id, created_at, updated_at, incident_id, type, status, claim_owner, claimed_at, processed_at, last_error FROM notification_events
WHERE status = 'pending'
  AND type IN ('down', 'up')
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type FindPendingNotificationEventsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) FindPendingNotificationEvents(ctx context.Context, arg FindPendingNotificationEventsParams) ([]NotificationEvent, error) {
	rows, err := q.db.QueryContext(ctx, findPendingNotificationEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IncidentID,
			&i.Type,
			&i.Status,
			&i.ClaimOwner,
			&i.ClaimedAt,
			&i.ProcessedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationEvents = `-- name: ListNotificationEvents :many
SELECT id, created_at, updated_at, incident_id, type, status, claim_owner, claimed_at, processed_at, last_error FROM notification_events
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNotificationEventsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNotificationEvents(ctx context.Context, arg ListNotificationEventsParams) ([]NotificationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IncidentID,
			&i.Type,
			&i.Status,
			&i.ClaimOwner,
			&i.ClaimedAt,
			&i.ProcessedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationEventTerminal = `-- name: MarkNotificationEventTerminal :execrows
UPDATE notification_events
SET status = ?, processed_at = ?, last_error = ?,
    claim_owner = NULL, claimed_at = NULL
WHERE id = ?
`

type MarkNotificationEventTerminalParams struct {
	Status      string       `json:"status"`
	ProcessedAt sql.NullTime `json:"processed_at"`
	LastError   string       `json:"last_error"`
	ID          string       `json:"id"`
}

func (q *Queries) MarkNotificationEventTerminal(ctx context.Context, arg MarkNotificationEventTerminalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationEventTerminal,
		arg.Status,
		arg.ProcessedAt,
		arg.LastError,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNotificationEvent = `-- name: UpdateNotificationEvent :execrows
UPDATE notification_events
SET incident_id = ?, type = ?, status = ?,
    claim_owner = ?, claimed_at = ?, processed_at = ?, last_error = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateNotificationEventParams struct {
	IncidentID  string         `json:"incident_id"`
	Type        string         `json:"type"`
	Status      string         `json:"status"`
	ClaimOwner  sql.NullString `json:"claim_owner"`
	ClaimedAt   sql.NullTime   `json:"claimed_at"`
	ProcessedAt sql.NullTime   `json:"processed_at"`
	LastError   string         `json:"last_error"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateNotificationEvent(ctx context.Context, arg UpdateNotificationEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNotificationEvent,
		arg.IncidentID,
		arg.Type,
		arg.Status,
		arg.ClaimOwner,
		arg.ClaimedAt,
		arg.ProcessedAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
