// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_channel.sql

package sqlitesqlc

import (
	"context"
	"time"
)

const createNotificationChannel = `-- name: CreateNotificationChannel :exec
INSERT INTO notification_channels (
    id, created_at, updated_at, name, type, config, enabled_by_default
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateNotificationChannelParams struct {
	ID               string    `json:"id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	Name             string    `json:"name"`
	Type             string    `json:"type"`
	Config           []byte    `json:"config"`
	EnabledByDefault int64     `json:"enabled_by_default"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationChannel,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.EnabledByDefault,
	)
	return err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execrows
DELETE FROM notification_channels WHERE id = ?
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findDefaultNotificationChannels = `-- name: FindDefaultNotificationChannels :many
SELECT id, created_at, updated_at, name, type, config, enabled_by_default FROM notification_channels WHERE enabled_by_default = 1
`

func (q *Queries) FindDefaultNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, findDefaultNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.EnabledByDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNotificationChannelByID = `-- name: FindNotificationChannelByID :one
SELECT id, created_at, updated_at, name, type, config, enabled_by_default FROM notification_channels WHERE id = ?
`

func (q *Queries) FindNotificationChannelByID(ctx context.Context, id string) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, findNotificationChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.EnabledByDefault,
	)
	return i, err
}

const findNotificationChannelsByComponentID = `-- name: FindNotificationChannelsByComponentID :many
SELECT nc.id, nc.created_at, nc.updated_at, nc.name, nc.type, nc.config, nc.enabled_by_default FROM notification_channels nc
JOIN component_notification_channels cnc
    ON cnc.notification_channel_id = nc.id
WHERE cnc.component_id = ?
`

func (q *Queries) FindNotificationChannelsByComponentID(ctx context.Context, componentID string) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, findNotificationChannelsByComponentID, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.EnabledByDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNotificationChannelsByResourceID = `-- name: FindNotificationChannelsByResourceID :many
SELECT nc.id, nc.created_at, nc.updated_at, nc.name, nc.type, nc.config, nc.enabled_by_default FROM notification_channels nc
JOIN resource_notification_channels rnc
    ON rnc.notification_channel_id = nc.id
WHERE rnc.resource_id = ?
`

func (q *Queries) FindNotificationChannelsByResourceID(ctx context.Context, resourceID string) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, findNotificationChannelsByResourceID, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.EnabledByDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNotificationChannelsByType = `-- name: FindNotificationChannelsByType :many
SELECT id, created_at, updated_at, name, type, config, enabled_by_default FROM notification_channels WHERE type = ?
`

func (q *Queries) FindNotificationChannelsByType(ctx context.Context, type_ string) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, findNotificationChannelsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.EnabledByDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, created_at, updated_at, name, type, config, enabled_by_default FROM notification_channels
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNotificationChannelsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNotificationChannels(ctx context.Context, arg ListNotificationChannelsParams) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.EnabledByDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :execrows
UPDATE notification_channels
SET name = ?,
    type = ?,
    config = ?,
    enabled_by_default = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateNotificationChannelParams struct {
	Name             string    `json:"name"`
	Type             string    `json:"type"`
	Config           []byte    `json:"config"`
	EnabledByDefault int64     `json:"enabled_by_default"`
	UpdatedAt        time.Time `json:"updated_at"`
	ID               string    `json:"id"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNotificationChannel,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.EnabledByDefault,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
