// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ping.sql

package sqlitesqlc

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS ok
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var ok int64
	err := row.Scan(&ok)
	return ok, err
}
