// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AvgResponseTimeByResourceInWindow(ctx context.Context, arg AvgResponseTimeByResourceInWindowParams) (sql.NullFloat64, error)
	ClaimNotificationEvent(ctx context.Context, arg ClaimNotificationEventParams) (int64, error)
	CountAPIKeysByUserID(ctx context.Context, userID string) (int64, error)
	CountExpiryNotificationLogsByKey(ctx context.Context, arg CountExpiryNotificationLogsByKeyParams) (int64, error)
	CountIncidentsByResourceID(ctx context.Context, resourceID string) (int64, error)
	CountMonitoringActivityByResourceSuccess(ctx context.Context, arg CountMonitoringActivityByResourceSuccessParams) (int64, error)
	CountMonitoringActivityByResourceTotal(ctx context.Context, arg CountMonitoringActivityByResourceTotalParams) (int64, error)
	CountMonitoringActivitySinceSuccess(ctx context.Context, createdAt time.Time) (int64, error)
	CountMonitoringActivitySinceTotal(ctx context.Context, createdAt time.Time) (int64, error)
	CountRecentTwoFactorResetTokensByUser(ctx context.Context, arg CountRecentTwoFactorResetTokensByUserParams) (int64, error)
	CountResourcesByComponentID(ctx context.Context, componentID sql.NullString) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateComponent(ctx context.Context, arg CreateComponentParams) error
	CreateEscalationPolicy(ctx context.Context, arg CreateEscalationPolicyParams) error
	CreateEscalationStep(ctx context.Context, arg CreateEscalationStepParams) error
	CreateExpiryNotificationLog(ctx context.Context, arg CreateExpiryNotificationLogParams) error
	// US2 of spec 048: incident_repository sqlc migration.
	// Mirror of postgres/incident.sql with SQLite-specific GetIncidentStats
	// (two correlated sub-queries; SQLite lacks COUNT(*) FILTER and the
	// one-pass CTE form).
	CreateIncident(ctx context.Context, arg CreateIncidentParams) error
	CreateIncidentDiagnostics(ctx context.Context, arg CreateIncidentDiagnosticsParams) (IncidentDiagnostic, error)
	CreateIncidentEventStep(ctx context.Context, arg CreateIncidentEventStepParams) error
	CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) error
	CreateMonitoringActivity(ctx context.Context, arg CreateMonitoringActivityParams) error
	CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) error
	CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) error
	// PR1 of US1: CRUD without M2M and without 1-to-1 preloads.
	// Mirror of postgres/resource.sql with SQLite-specific date math for
	// FindMissedHeartbeats (strftime instead of EXTRACT EPOCH).
	CreateResource(ctx context.Context, arg CreateResourceParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStatusPageSettings(ctx context.Context, arg CreateStatusPageSettingsParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTwoFactorResetToken(ctx context.Context, arg CreateTwoFactorResetTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComponent(ctx context.Context, id string) (int64, error)
	DeleteEscalationPolicy(ctx context.Context, id string) (int64, error)
	DeleteEscalationStepsByPolicy(ctx context.Context, policyID string) error
	DeleteExpiredTwoFactorResetTokens(ctx context.Context, expiresAt time.Time) error
	DeleteExpiryNotificationLogsByResourceIDAndType(ctx context.Context, arg DeleteExpiryNotificationLogsByResourceIDAndTypeParams) error
	DeleteExpiryNotificationLogsOlderThan(ctx context.Context, sentAt time.Time) error
	DeleteIncident(ctx context.Context, id string) (int64, error)
	DeleteIncidentDiagnostics(ctx context.Context, id string) (int64, error)
	DeleteIncidentEventStep(ctx context.Context, id string) (int64, error)
	DeleteMaintenance(ctx context.Context, id string) (int64, error)
	DeleteNotificationChannel(ctx context.Context, id string) (int64, error)
	DeleteNotificationEvent(ctx context.Context, id string) error
	DeleteResourceCredentialByResourceID(ctx context.Context, resourceID string) (int64, error)
	DeleteTag(ctx context.Context, id string) (int64, error)
	DeleteUser(ctx context.Context, id string) error
	FindAPIKeyByIDForUser(ctx context.Context, arg FindAPIKeyByIDForUserParams) (ApiKey, error)
	FindAPIKeyByKeyHash(ctx context.Context, keyHash string) (ApiKey, error)
	FindActiveIncidentByResourceID(ctx context.Context, resourceID string) (Incident, error)
	FindActiveMaintenancesForResource(ctx context.Context, arg FindActiveMaintenancesForResourceParams) ([]Maintenance, error)
	FindActiveTwoFactorResetToken(ctx context.Context, arg FindActiveTwoFactorResetTokenParams) (TwoFactorResetToken, error)
	FindComponentByID(ctx context.Context, id string) (Component, error)
	FindDefaultNotificationChannels(ctx context.Context) ([]NotificationChannel, error)
	FindEarliestUptimeDailyAggDay(ctx context.Context) (interface{}, error)
	FindEscalationPolicyByID(ctx context.Context, id string) (EscalationPolicy, error)
	FindIncidentByID(ctx context.Context, id string) (Incident, error)
	FindIncidentDiagnosticsByIncidentID(ctx context.Context, incidentID string) (IncidentDiagnostic, error)
	FindIncidentEventStepByID(ctx context.Context, id string) (FindIncidentEventStepByIDRow, error)
	FindIncidentsByIDs(ctx context.Context, ids []string) ([]Incident, error)
	FindIncidentsByResource(ctx context.Context, arg FindIncidentsByResourceParams) ([]Incident, error)
	FindLastIncidentEventStepByIncidentAndStep(ctx context.Context, arg FindLastIncidentEventStepByIncidentAndStepParams) (IncidentEventStep, error)
	FindLastResolvedIncident(ctx context.Context) (Incident, error)
	FindMaintenanceByID(ctx context.Context, id string) (Maintenance, error)
	FindMissedHeartbeatsSQLite(ctx context.Context, arg FindMissedHeartbeatsSQLiteParams) ([]Resource, error)
	FindMonitoringActivitiesByResourceID(ctx context.Context, arg FindMonitoringActivitiesByResourceIDParams) ([]MonitoringActivity, error)
	FindNotificationChannelByID(ctx context.Context, id string) (NotificationChannel, error)
	FindNotificationChannelsByComponentID(ctx context.Context, componentID string) ([]NotificationChannel, error)
	FindNotificationChannelsByResourceID(ctx context.Context, resourceID string) ([]NotificationChannel, error)
	FindNotificationChannelsByType(ctx context.Context, type_ string) ([]NotificationChannel, error)
	FindNotificationEventByID(ctx context.Context, id string) (NotificationEvent, error)
	FindPendingNotificationEvents(ctx context.Context, arg FindPendingNotificationEventsParams) ([]NotificationEvent, error)
	FindResourceByHeartbeatSlug(ctx context.Context, heartbeatSlug sql.NullString) (Resource, error)
	FindResourceByID(ctx context.Context, id string) (Resource, error)
	FindResourceIDsByTagName(ctx context.Context, arg FindResourceIDsByTagNameParams) ([]string, error)
	FindResourcesByComponentID(ctx context.Context, componentID sql.NullString) ([]Resource, error)
	FindResourcesByIDs(ctx context.Context, ids []string) ([]Resource, error)
	FindSessionByID(ctx context.Context, id string) (Session, error)
	FindTagByID(ctx context.Context, id string) (Tag, error)
	FindTagByName(ctx context.Context, name string) (Tag, error)
	FindTagsByIDs(ctx context.Context, ids []string) ([]Tag, error)
	FindUnresolvedIncidents(ctx context.Context, arg FindUnresolvedIncidentsParams) ([]Incident, error)
	FindUptimeDailyAggForResource(ctx context.Context, arg FindUptimeDailyAggForResourceParams) ([]UptimeDailyAgg, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id string) (User, error)
	GetIncidentStatsSQLite(ctx context.Context, since time.Time) (GetIncidentStatsSQLiteRow, error)
	GetRecentResponseTimes(ctx context.Context, arg GetRecentResponseTimesParams) ([]GetRecentResponseTimesRow, error)
	GetResourceCredentialByResourceID(ctx context.Context, resourceID string) (ResourceCredential, error)
	GetStatusPageSettings(ctx context.Context) (StatusPageSetting, error)
	HasActiveIncident(ctx context.Context) (int64, error)
	LinkMaintenanceResource(ctx context.Context, arg LinkMaintenanceResourceParams) error
	// M2M: resource_notification_channels ---------------------------------------
	LinkResourceChannel(ctx context.Context, arg LinkResourceChannelParams) error
	// M2M: resource_tags ---------------------------------------------------------
	LinkResourceTag(ctx context.Context, arg LinkResourceTagParams) error
	ListAPIKeysByUserID(ctx context.Context, userID string) ([]ApiKey, error)
	ListActiveResources(ctx context.Context, arg ListActiveResourcesParams) ([]Resource, error)
	ListActiveSessionsByUser(ctx context.Context, userID string) ([]Session, error)
	ListChannelIDsByResourceID(ctx context.Context, resourceID string) ([]string, error)
	ListChannelsByResourceIDs(ctx context.Context, resourceIds []string) ([]ListChannelsByResourceIDsRow, error)
	ListComponents(ctx context.Context, arg ListComponentsParams) ([]Component, error)
	// 1-to-1 preloads ------------------------------------------------------------
	ListComponentsByIDs(ctx context.Context, ids []string) ([]Component, error)
	ListCredentialsByResourceIDs(ctx context.Context, resourceIds []string) ([]ResourceCredential, error)
	ListEscalationPolicies(ctx context.Context) ([]EscalationPolicy, error)
	ListEscalationStepsByPolicy(ctx context.Context, policyID string) ([]EscalationStep, error)
	ListIncidentDiagnosticsByIncidentIDs(ctx context.Context, incidentIds []string) ([]IncidentDiagnostic, error)
	ListIncidentEventSteps(ctx context.Context, arg ListIncidentEventStepsParams) ([]IncidentEventStep, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error)
	ListMaintenanceResourceIDsByMaintenanceID(ctx context.Context, maintenanceID string) ([]string, error)
	ListMaintenancesAll(ctx context.Context, arg ListMaintenancesAllParams) ([]Maintenance, error)
	ListMaintenancesByStatus(ctx context.Context, arg ListMaintenancesByStatusParams) ([]Maintenance, error)
	ListMonitoringActivities(ctx context.Context, arg ListMonitoringActivitiesParams) ([]MonitoringActivity, error)
	ListNotificationChannels(ctx context.Context, arg ListNotificationChannelsParams) ([]NotificationChannel, error)
	ListNotificationEvents(ctx context.Context, arg ListNotificationEventsParams) ([]NotificationEvent, error)
	ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error)
	ListResourcesByComponentID(ctx context.Context, componentID sql.NullString) ([]Resource, error)
	ListScheduledResources(ctx context.Context) ([]Resource, error)
	ListTagIDsByResourceID(ctx context.Context, resourceID string) ([]string, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListTagsByResourceIDs(ctx context.Context, resourceIds []string) ([]ListTagsByResourceIDsRow, error)
	MarkNotificationEventTerminal(ctx context.Context, arg MarkNotificationEventTerminalParams) (int64, error)
	MarkTwoFactorResetTokenUsed(ctx context.Context, arg MarkTwoFactorResetTokenUsedParams) (int64, error)
	NextEscalationPriority(ctx context.Context) (int64, error)
	Ping(ctx context.Context) (int64, error)
	ResourceCredentialExists(ctx context.Context, resourceID string) (int64, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeAllSessionsExcept(ctx context.Context, arg RevokeAllSessionsExceptParams) (int64, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	SelectMonitoringActivityHourlyAggregateInputs(ctx context.Context, arg SelectMonitoringActivityHourlyAggregateInputsParams) ([]SelectMonitoringActivityHourlyAggregateInputsRow, error)
	SelectMonitoringActivitySuccessInWindow(ctx context.Context, arg SelectMonitoringActivitySuccessInWindowParams) ([]int64, error)
	SetEscalationPolicyPriority(ctx context.Context, arg SetEscalationPolicyPriorityParams) (int64, error)
	SoftDeleteResource(ctx context.Context, id string) (int64, error)
	UnlinkMaintenanceResource(ctx context.Context, arg UnlinkMaintenanceResourceParams) error
	UnlinkResourceChannel(ctx context.Context, arg UnlinkResourceChannelParams) error
	UnlinkResourceTag(ctx context.Context, arg UnlinkResourceTagParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) (int64, error)
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) error
	UpdateComponentLastNotificationStatus(ctx context.Context, arg UpdateComponentLastNotificationStatusParams) (int64, error)
	UpdateEscalationPolicy(ctx context.Context, arg UpdateEscalationPolicyParams) (int64, error)
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (int64, error)
	UpdateIncidentDiagnostics(ctx context.Context, arg UpdateIncidentDiagnosticsParams) (int64, error)
	UpdateIncidentEventStep(ctx context.Context, arg UpdateIncidentEventStepParams) (int64, error)
	UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) error
	UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (int64, error)
	UpdateNotificationEvent(ctx context.Context, arg UpdateNotificationEventParams) (int64, error)
	UpdateResourceLastPingAt(ctx context.Context, arg UpdateResourceLastPingAtParams) (int64, error)
	UpdateResourceMain(ctx context.Context, arg UpdateResourceMainParams) (int64, error)
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (int64, error)
	UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error
	UpdateStatusPageSettings(ctx context.Context, arg UpdateStatusPageSettingsParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserTwoFactorSecret(ctx context.Context, arg UpdateUserTwoFactorSecretParams) error
	UpsertResourceCredential(ctx context.Context, arg UpsertResourceCredentialParams) error
	UpsertUptimeDailyAgg(ctx context.Context, arg UpsertUptimeDailyAggParams) error
}

var _ Querier = (*Queries)(nil)
