// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_health.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteResourceHealth = `-- name: DeleteResourceHealth :exec
DELETE FROM resource_health WHERE resource_id = ?1
`

// Called when a check collects nothing at all, so the interface shows no figures
// rather than yesterday's.
func (q *Queries) DeleteResourceHealth(ctx context.Context, resourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteResourceHealth, resourceID)
	return err
}

const findResourceHealth = `-- name: FindResourceHealth :one
SELECT resource_id, collected_at, connections_active, connections_max, longest_query_seconds, replication_lag_seconds, privilege_limited, unsupported_version FROM resource_health WHERE resource_id = ?1
`

func (q *Queries) FindResourceHealth(ctx context.Context, resourceID string) (ResourceHealth, error) {
	row := q.db.QueryRowContext(ctx, findResourceHealth, resourceID)
	var i ResourceHealth
	err := row.Scan(
		&i.ResourceID,
		&i.CollectedAt,
		&i.ConnectionsActive,
		&i.ConnectionsMax,
		&i.LongestQuerySeconds,
		&i.ReplicationLagSeconds,
		&i.PrivilegeLimited,
		&i.UnsupportedVersion,
	)
	return i, err
}

const upsertResourceHealth = `-- name: UpsertResourceHealth :exec
INSERT INTO resource_health (
    resource_id, collected_at, connections_active, connections_max,
    longest_query_seconds, replication_lag_seconds, privilege_limited, unsupported_version
)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
ON CONFLICT (resource_id) DO UPDATE SET
    collected_at            = excluded.collected_at,
    connections_active      = excluded.connections_active,
    connections_max         = excluded.connections_max,
    longest_query_seconds   = excluded.longest_query_seconds,
    replication_lag_seconds = excluded.replication_lag_seconds,
    privilege_limited       = excluded.privilege_limited,
    unsupported_version     = excluded.unsupported_version
`

type UpsertResourceHealthParams struct {
	ResourceID            string          `json:"resource_id"`
	CollectedAt           time.Time       `json:"collected_at"`
	ConnectionsActive     sql.NullInt64   `json:"connections_active"`
	ConnectionsMax        sql.NullInt64   `json:"connections_max"`
	LongestQuerySeconds   sql.NullFloat64 `json:"longest_query_seconds"`
	ReplicationLagSeconds sql.NullFloat64 `json:"replication_lag_seconds"`
	PrivilegeLimited      int64           `json:"privilege_limited"`
	UnsupportedVersion    int64           `json:"unsupported_version"`
}

// At most one row per monitor: replace rather than accumulate. This is what makes
// storage constant per monitor and removes any need for a retention job.
// Keep this file pure ASCII: sqlc slices SQLite query text by byte offset, so one
// multi-byte character silently truncates the generated SQL.
func (q *Queries) UpsertResourceHealth(ctx context.Context, arg UpsertResourceHealthParams) error {
	_, err := q.db.ExecContext(ctx, upsertResourceHealth,
		arg.ResourceID,
		arg.CollectedAt,
		arg.ConnectionsActive,
		arg.ConnectionsMax,
		arg.LongestQuerySeconds,
		arg.ReplicationLagSeconds,
		arg.PrivilegeLimited,
		arg.UnsupportedVersion,
	)
	return err
}
