// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_credential.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteResourceCredentialByResourceID = `-- name: DeleteResourceCredentialByResourceID :execrows
DELETE FROM resource_credentials WHERE resource_id = ?
`

func (q *Queries) DeleteResourceCredentialByResourceID(ctx context.Context, resourceID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteResourceCredentialByResourceID, resourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getResourceCredentialByResourceID = `-- name: GetResourceCredentialByResourceID :one
SELECT id, resource_id, username, password, options, created_at, updated_at FROM resource_credentials WHERE resource_id = ?
`

func (q *Queries) GetResourceCredentialByResourceID(ctx context.Context, resourceID string) (ResourceCredential, error) {
	row := q.db.QueryRowContext(ctx, getResourceCredentialByResourceID, resourceID)
	var i ResourceCredential
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Username,
		&i.Password,
		&i.Options,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resourceCredentialExists = `-- name: ResourceCredentialExists :one
SELECT COUNT(*) FROM resource_credentials WHERE resource_id = ?
`

func (q *Queries) ResourceCredentialExists(ctx context.Context, resourceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, resourceCredentialExists, resourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertResourceCredential = `-- name: UpsertResourceCredential :exec
INSERT INTO resource_credentials (
    id, resource_id, username, password, options, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (resource_id) DO UPDATE
SET username = excluded.username,
    password = excluded.password,
    options = excluded.options,
    updated_at = excluded.updated_at
`

type UpsertResourceCredentialParams struct {
	ID         string         `json:"id"`
	ResourceID string         `json:"resource_id"`
	Username   sql.NullString `json:"username"`
	Password   []byte         `json:"password"`
	Options    []byte         `json:"options"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertResourceCredential(ctx context.Context, arg UpsertResourceCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertResourceCredential,
		arg.ID,
		arg.ResourceID,
		arg.Username,
		arg.Password,
		arg.Options,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
