// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, browser, os, ip, location, last_active_at, created_at, revoked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, browser, os, ip, location, last_active_at, created_at, revoked_at
`

type CreateSessionParams struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Browser      string         `json:"browser"`
	Os           string         `json:"os"`
	Ip           string         `json:"ip"`
	Location     sql.NullString `json:"location"`
	LastActiveAt time.Time      `json:"last_active_at"`
	CreatedAt    time.Time      `json:"created_at"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Browser,
		arg.Os,
		arg.Ip,
		arg.Location,
		arg.LastActiveAt,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Browser,
		&i.Os,
		&i.Ip,
		&i.Location,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findSessionByID = `-- name: FindSessionByID :one
SELECT id, user_id, browser, os, ip, location, last_active_at, created_at, revoked_at FROM sessions WHERE id = ?
`

func (q *Queries) FindSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Browser,
		&i.Os,
		&i.Ip,
		&i.Location,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, browser, os, ip, location, last_active_at, created_at, revoked_at FROM sessions
WHERE user_id = ? AND revoked_at IS NULL
ORDER BY last_active_at DESC
`

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Browser,
			&i.Os,
			&i.Ip,
			&i.Location,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsExcept = `-- name: RevokeAllSessionsExcept :execrows
UPDATE sessions
SET revoked_at = ?
WHERE user_id = ? AND id <> ? AND revoked_at IS NULL
`

type RevokeAllSessionsExceptParams struct {
	RevokedAt sql.NullTime `json:"revoked_at"`
	UserID    string       `json:"user_id"`
	ID        string       `json:"id"`
}

func (q *Queries) RevokeAllSessionsExcept(ctx context.Context, arg RevokeAllSessionsExceptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAllSessionsExcept, arg.RevokedAt, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = ?
WHERE id = ? AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt sql.NullTime `json:"revoked_at"`
	ID        string       `json:"id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSession, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSessionLastActive = `-- name: UpdateSessionLastActive :exec
UPDATE sessions
SET last_active_at = ?
WHERE id = ?
`

type UpdateSessionLastActiveParams struct {
	LastActiveAt time.Time `json:"last_active_at"`
	ID           string    `json:"id"`
}

func (q *Queries) UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastActive, arg.LastActiveAt, arg.ID)
	return err
}
