// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statuspage_settings.sql

package sqlitesqlc

import (
	"context"
	"time"
)

const createStatusPageSettings = `-- name: CreateStatusPageSettings :exec
INSERT INTO status_page_settings (
    id, name, homepage_url, custom_domain, google_analytics_id,
    enable_details_page, show_uptime_percentage, hide_paused_monitors,
    show_incident_history, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStatusPageSettingsParams struct {
	ID                   string    `json:"id"`
	Name                 string    `json:"name"`
	HomepageUrl          string    `json:"homepage_url"`
	CustomDomain         string    `json:"custom_domain"`
	GoogleAnalyticsID    string    `json:"google_analytics_id"`
	EnableDetailsPage    int64     `json:"enable_details_page"`
	ShowUptimePercentage int64     `json:"show_uptime_percentage"`
	HidePausedMonitors   int64     `json:"hide_paused_monitors"`
	ShowIncidentHistory  int64     `json:"show_incident_history"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

func (q *Queries) CreateStatusPageSettings(ctx context.Context, arg CreateStatusPageSettingsParams) error {
	_, err := q.db.ExecContext(ctx, createStatusPageSettings,
		arg.ID,
		arg.Name,
		arg.HomepageUrl,
		arg.CustomDomain,
		arg.GoogleAnalyticsID,
		arg.EnableDetailsPage,
		arg.ShowUptimePercentage,
		arg.HidePausedMonitors,
		arg.ShowIncidentHistory,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getStatusPageSettings = `-- name: GetStatusPageSettings :one
SELECT id, created_at, updated_at, name, homepage_url, custom_domain, google_analytics_id, enable_details_page, show_uptime_percentage, hide_paused_monitors, show_incident_history FROM status_page_settings LIMIT 1
`

func (q *Queries) GetStatusPageSettings(ctx context.Context) (StatusPageSetting, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageSettings)
	var i StatusPageSetting
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.HomepageUrl,
		&i.CustomDomain,
		&i.GoogleAnalyticsID,
		&i.EnableDetailsPage,
		&i.ShowUptimePercentage,
		&i.HidePausedMonitors,
		&i.ShowIncidentHistory,
	)
	return i, err
}

const updateStatusPageSettings = `-- name: UpdateStatusPageSettings :exec
UPDATE status_page_settings
SET name = ?,
    homepage_url = ?,
    custom_domain = ?,
    google_analytics_id = ?,
    enable_details_page = ?,
    show_uptime_percentage = ?,
    hide_paused_monitors = ?,
    show_incident_history = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateStatusPageSettingsParams struct {
	Name                 string    `json:"name"`
	HomepageUrl          string    `json:"homepage_url"`
	CustomDomain         string    `json:"custom_domain"`
	GoogleAnalyticsID    string    `json:"google_analytics_id"`
	EnableDetailsPage    int64     `json:"enable_details_page"`
	ShowUptimePercentage int64     `json:"show_uptime_percentage"`
	HidePausedMonitors   int64     `json:"hide_paused_monitors"`
	ShowIncidentHistory  int64     `json:"show_incident_history"`
	UpdatedAt            time.Time `json:"updated_at"`
	ID                   string    `json:"id"`
}

func (q *Queries) UpdateStatusPageSettings(ctx context.Context, arg UpdateStatusPageSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusPageSettings,
		arg.Name,
		arg.HomepageUrl,
		arg.CustomDomain,
		arg.GoogleAnalyticsID,
		arg.EnableDetailsPage,
		arg.ShowUptimePercentage,
		arg.HidePausedMonitors,
		arg.ShowIncidentHistory,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
