// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statuspage_settings.sql

package sqlitesqlc

import (
	"context"
	"time"
)

const createStatusPageSettings = `-- name: CreateStatusPageSettings :exec
INSERT INTO status_page_settings (
    id, name, homepage_url, custom_domain,
    umami_website_id, umami_script_url,
    enable_details_page, show_uptime_percentage, hide_paused_monitors,
    show_incident_history,
    custom_domain_status, custom_domain_ssl_status, custom_domain_dns_records,
    logo_url_light, logo_url_dark, favicon_url, primary_color, theme_overrides,
    created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStatusPageSettingsParams struct {
	ID                     string    `json:"id"`
	Name                   string    `json:"name"`
	HomepageUrl            string    `json:"homepage_url"`
	CustomDomain           string    `json:"custom_domain"`
	UmamiWebsiteID         string    `json:"umami_website_id"`
	UmamiScriptUrl         string    `json:"umami_script_url"`
	EnableDetailsPage      int64     `json:"enable_details_page"`
	ShowUptimePercentage   int64     `json:"show_uptime_percentage"`
	HidePausedMonitors     int64     `json:"hide_paused_monitors"`
	ShowIncidentHistory    int64     `json:"show_incident_history"`
	CustomDomainStatus     string    `json:"custom_domain_status"`
	CustomDomainSslStatus  string    `json:"custom_domain_ssl_status"`
	CustomDomainDnsRecords string    `json:"custom_domain_dns_records"`
	LogoUrlLight           string    `json:"logo_url_light"`
	LogoUrlDark            string    `json:"logo_url_dark"`
	FaviconUrl             string    `json:"favicon_url"`
	PrimaryColor           string    `json:"primary_color"`
	ThemeOverrides         string    `json:"theme_overrides"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

func (q *Queries) CreateStatusPageSettings(ctx context.Context, arg CreateStatusPageSettingsParams) error {
	_, err := q.db.ExecContext(ctx, createStatusPageSettings,
		arg.ID,
		arg.Name,
		arg.HomepageUrl,
		arg.CustomDomain,
		arg.UmamiWebsiteID,
		arg.UmamiScriptUrl,
		arg.EnableDetailsPage,
		arg.ShowUptimePercentage,
		arg.HidePausedMonitors,
		arg.ShowIncidentHistory,
		arg.CustomDomainStatus,
		arg.CustomDomainSslStatus,
		arg.CustomDomainDnsRecords,
		arg.LogoUrlLight,
		arg.LogoUrlDark,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.ThemeOverrides,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getStatusPageSettings = `-- name: GetStatusPageSettings :one
SELECT id, created_at, updated_at, name, homepage_url, custom_domain, google_analytics_id, enable_details_page, show_uptime_percentage, hide_paused_monitors, show_incident_history, custom_domain_status, custom_domain_ssl_status, custom_domain_dns_records, logo_url_light, logo_url_dark, favicon_url, primary_color, theme_overrides, umami_website_id, umami_script_url FROM status_page_settings LIMIT 1
`

func (q *Queries) GetStatusPageSettings(ctx context.Context) (StatusPageSetting, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageSettings)
	var i StatusPageSetting
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.HomepageUrl,
		&i.CustomDomain,
		&i.GoogleAnalyticsID,
		&i.EnableDetailsPage,
		&i.ShowUptimePercentage,
		&i.HidePausedMonitors,
		&i.ShowIncidentHistory,
		&i.CustomDomainStatus,
		&i.CustomDomainSslStatus,
		&i.CustomDomainDnsRecords,
		&i.LogoUrlLight,
		&i.LogoUrlDark,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.ThemeOverrides,
		&i.UmamiWebsiteID,
		&i.UmamiScriptUrl,
	)
	return i, err
}

const updateStatusPageSettings = `-- name: UpdateStatusPageSettings :exec
UPDATE status_page_settings
SET name = ?,
    homepage_url = ?,
    custom_domain = ?,
    umami_website_id = ?,
    umami_script_url = ?,
    enable_details_page = ?,
    show_uptime_percentage = ?,
    hide_paused_monitors = ?,
    show_incident_history = ?,
    custom_domain_status = ?,
    custom_domain_ssl_status = ?,
    custom_domain_dns_records = ?,
    logo_url_light = ?,
    logo_url_dark = ?,
    favicon_url = ?,
    primary_color = ?,
    theme_overrides = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateStatusPageSettingsParams struct {
	Name                   string    `json:"name"`
	HomepageUrl            string    `json:"homepage_url"`
	CustomDomain           string    `json:"custom_domain"`
	UmamiWebsiteID         string    `json:"umami_website_id"`
	UmamiScriptUrl         string    `json:"umami_script_url"`
	EnableDetailsPage      int64     `json:"enable_details_page"`
	ShowUptimePercentage   int64     `json:"show_uptime_percentage"`
	HidePausedMonitors     int64     `json:"hide_paused_monitors"`
	ShowIncidentHistory    int64     `json:"show_incident_history"`
	CustomDomainStatus     string    `json:"custom_domain_status"`
	CustomDomainSslStatus  string    `json:"custom_domain_ssl_status"`
	CustomDomainDnsRecords string    `json:"custom_domain_dns_records"`
	LogoUrlLight           string    `json:"logo_url_light"`
	LogoUrlDark            string    `json:"logo_url_dark"`
	FaviconUrl             string    `json:"favicon_url"`
	PrimaryColor           string    `json:"primary_color"`
	ThemeOverrides         string    `json:"theme_overrides"`
	UpdatedAt              time.Time `json:"updated_at"`
	ID                     string    `json:"id"`
}

func (q *Queries) UpdateStatusPageSettings(ctx context.Context, arg UpdateStatusPageSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusPageSettings,
		arg.Name,
		arg.HomepageUrl,
		arg.CustomDomain,
		arg.UmamiWebsiteID,
		arg.UmamiScriptUrl,
		arg.EnableDetailsPage,
		arg.ShowUptimePercentage,
		arg.HidePausedMonitors,
		arg.ShowIncidentHistory,
		arg.CustomDomainStatus,
		arg.CustomDomainSslStatus,
		arg.CustomDomainDnsRecords,
		arg.LogoUrlLight,
		arg.LogoUrlDark,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.ThemeOverrides,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
