// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: two_factor_reset_token.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const countRecentTwoFactorResetTokensByUser = `-- name: CountRecentTwoFactorResetTokensByUser :one
SELECT COUNT(*) FROM two_factor_reset_tokens
WHERE user_id = ? AND created_at > ?
`

type CountRecentTwoFactorResetTokensByUserParams struct {
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CountRecentTwoFactorResetTokensByUser(ctx context.Context, arg CountRecentTwoFactorResetTokensByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentTwoFactorResetTokensByUser, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTwoFactorResetToken = `-- name: CreateTwoFactorResetToken :exec
INSERT INTO two_factor_reset_tokens (token_hash, user_id, expires_at, created_at)
VALUES (?, ?, ?, ?)
`

type CreateTwoFactorResetTokenParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateTwoFactorResetToken(ctx context.Context, arg CreateTwoFactorResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createTwoFactorResetToken,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredTwoFactorResetTokens = `-- name: DeleteExpiredTwoFactorResetTokens :exec
DELETE FROM two_factor_reset_tokens WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredTwoFactorResetTokens(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTwoFactorResetTokens, expiresAt)
	return err
}

const findActiveTwoFactorResetToken = `-- name: FindActiveTwoFactorResetToken :one
SELECT token_hash, user_id, expires_at, used_at, created_at FROM two_factor_reset_tokens
WHERE token_hash = ? AND used_at IS NULL AND expires_at > ?
`

type FindActiveTwoFactorResetTokenParams struct {
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) FindActiveTwoFactorResetToken(ctx context.Context, arg FindActiveTwoFactorResetTokenParams) (TwoFactorResetToken, error) {
	row := q.db.QueryRowContext(ctx, findActiveTwoFactorResetToken, arg.TokenHash, arg.ExpiresAt)
	var i TwoFactorResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTwoFactorResetTokenUsed = `-- name: MarkTwoFactorResetTokenUsed :execrows
UPDATE two_factor_reset_tokens
SET used_at = ?
WHERE token_hash = ? AND used_at IS NULL
`

type MarkTwoFactorResetTokenUsedParams struct {
	UsedAt    sql.NullTime `json:"used_at"`
	TokenHash string       `json:"token_hash"`
}

func (q *Queries) MarkTwoFactorResetTokenUsed(ctx context.Context, arg MarkTwoFactorResetTokenUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTwoFactorResetTokenUsed, arg.UsedAt, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
