// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uptime_daily_agg.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const findEarliestUptimeDailyAggDay = `-- name: FindEarliestUptimeDailyAggDay :one
SELECT MIN(day) AS earliest FROM uptime_daily_agg
`

func (q *Queries) FindEarliestUptimeDailyAggDay(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, findEarliestUptimeDailyAggDay)
	var earliest interface{}
	err := row.Scan(&earliest)
	return earliest, err
}

const findUptimeDailyAggForResource = `-- name: FindUptimeDailyAggForResource :many
SELECT resource_id, day, samples, up, degraded, down, uptime_ratio, computed_at
FROM uptime_daily_agg
WHERE resource_id = ?1
  AND day >= ?2
  AND day <= ?3
ORDER BY day ASC
`

type FindUptimeDailyAggForResourceParams struct {
	ResourceID string `json:"resource_id"`
	FromDay    string `json:"from_day"`
	ToDay      string `json:"to_day"`
}

func (q *Queries) FindUptimeDailyAggForResource(ctx context.Context, arg FindUptimeDailyAggForResourceParams) ([]UptimeDailyAgg, error) {
	rows, err := q.db.QueryContext(ctx, findUptimeDailyAggForResource, arg.ResourceID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeDailyAgg{}
	for rows.Next() {
		var i UptimeDailyAgg
		if err := rows.Scan(
			&i.ResourceID,
			&i.Day,
			&i.Samples,
			&i.Up,
			&i.Degraded,
			&i.Down,
			&i.UptimeRatio,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUptimeAggByResourcesSince = `-- name: SumUptimeAggByResourcesSince :many
SELECT
    resource_id,
    SUM(up)      AS up_sum,
    SUM(samples) AS samples_sum
FROM uptime_daily_agg
WHERE day >= ?1
  AND resource_id IN (/*SLICE:resource_ids*/?)
GROUP BY resource_id
`

type SumUptimeAggByResourcesSinceParams struct {
	FromDay     string   `json:"from_day"`
	ResourceIds []string `json:"resource_ids"`
}

type SumUptimeAggByResourcesSinceRow struct {
	ResourceID string          `json:"resource_id"`
	UpSum      sql.NullFloat64 `json:"up_sum"`
	SamplesSum sql.NullFloat64 `json:"samples_sum"`
}

// One round-trip bulk aggregation grouped by resource. Used by the list path
// to enrich each resource with its uptime ratio over a sliding window (30d).
func (q *Queries) SumUptimeAggByResourcesSince(ctx context.Context, arg SumUptimeAggByResourcesSinceParams) ([]SumUptimeAggByResourcesSinceRow, error) {
	query := sumUptimeAggByResourcesSince
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FromDay)
	if len(arg.ResourceIds) > 0 {
		for _, v := range arg.ResourceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", strings.Repeat(",?", len(arg.ResourceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUptimeAggByResourcesSinceRow{}
	for rows.Next() {
		var i SumUptimeAggByResourcesSinceRow
		if err := rows.Scan(&i.ResourceID, &i.UpSum, &i.SamplesSum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUptimeDailyAgg = `-- name: UpsertUptimeDailyAgg :exec
INSERT INTO uptime_daily_agg (
    resource_id, day, samples, up, degraded, down, uptime_ratio, computed_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(resource_id, day) DO UPDATE SET
    samples      = excluded.samples,
    up           = excluded.up,
    degraded     = excluded.degraded,
    down         = excluded.down,
    uptime_ratio = excluded.uptime_ratio,
    computed_at  = excluded.computed_at
`

type UpsertUptimeDailyAggParams struct {
	ResourceID  string    `json:"resource_id"`
	Day         string    `json:"day"`
	Samples     int64     `json:"samples"`
	Up          int64     `json:"up"`
	Degraded    int64     `json:"degraded"`
	Down        int64     `json:"down"`
	UptimeRatio float64   `json:"uptime_ratio"`
	ComputedAt  time.Time `json:"computed_at"`
}

func (q *Queries) UpsertUptimeDailyAgg(ctx context.Context, arg UpsertUptimeDailyAggParams) error {
	_, err := q.db.ExecContext(ctx, upsertUptimeDailyAgg,
		arg.ResourceID,
		arg.Day,
		arg.Samples,
		arg.Up,
		arg.Degraded,
		arg.Down,
		arg.UptimeRatio,
		arg.ComputedAt,
	)
	return err
}
