// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, name, hashed_password,
    password_initialized, force_password_change,
    two_factor_enabled, two_factor_secret, two_factor_backup_codes,
    last_login_at, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, email, name, hashed_password, password_initialized, force_password_change, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID                   string       `json:"id"`
	Email                string       `json:"email"`
	Name                 string       `json:"name"`
	HashedPassword       string       `json:"hashed_password"`
	PasswordInitialized  int64        `json:"password_initialized"`
	ForcePasswordChange  int64        `json:"force_password_change"`
	TwoFactorEnabled     int64        `json:"two_factor_enabled"`
	TwoFactorSecret      string       `json:"two_factor_secret"`
	TwoFactorBackupCodes []byte       `json:"two_factor_backup_codes"`
	LastLoginAt          sql.NullTime `json:"last_login_at"`
	CreatedAt            time.Time    `json:"created_at"`
	UpdatedAt            time.Time    `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.HashedPassword,
		arg.PasswordInitialized,
		arg.ForcePasswordChange,
		arg.TwoFactorEnabled,
		arg.TwoFactorSecret,
		arg.TwoFactorBackupCodes,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.PasswordInitialized,
		&i.ForcePasswordChange,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.TwoFactorBackupCodes,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, name, hashed_password, password_initialized, force_password_change, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login_at, created_at, updated_at FROM users WHERE email = ?
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.PasswordInitialized,
		&i.ForcePasswordChange,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.TwoFactorBackupCodes,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, name, hashed_password, password_initialized, force_password_change, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login_at, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.PasswordInitialized,
		&i.ForcePasswordChange,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.TwoFactorBackupCodes,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = ?,
    name = ?,
    hashed_password = ?,
    password_initialized = ?,
    force_password_change = ?,
    two_factor_enabled = ?,
    two_factor_secret = ?,
    two_factor_backup_codes = ?,
    last_login_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Email                string       `json:"email"`
	Name                 string       `json:"name"`
	HashedPassword       string       `json:"hashed_password"`
	PasswordInitialized  int64        `json:"password_initialized"`
	ForcePasswordChange  int64        `json:"force_password_change"`
	TwoFactorEnabled     int64        `json:"two_factor_enabled"`
	TwoFactorSecret      string       `json:"two_factor_secret"`
	TwoFactorBackupCodes []byte       `json:"two_factor_backup_codes"`
	LastLoginAt          sql.NullTime `json:"last_login_at"`
	UpdatedAt            time.Time    `json:"updated_at"`
	ID                   string       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Email,
		arg.Name,
		arg.HashedPassword,
		arg.PasswordInitialized,
		arg.ForcePasswordChange,
		arg.TwoFactorEnabled,
		arg.TwoFactorSecret,
		arg.TwoFactorBackupCodes,
		arg.LastLoginAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = ?,
    password_initialized = 1,
    force_password_change = 0
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	HashedPassword string `json:"hashed_password"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.HashedPassword, arg.ID)
	return err
}

const updateUserTwoFactorSecret = `-- name: UpdateUserTwoFactorSecret :exec
UPDATE users
SET two_factor_secret = ?,
    two_factor_enabled = ?
WHERE id = ?
`

type UpdateUserTwoFactorSecretParams struct {
	TwoFactorSecret  string `json:"two_factor_secret"`
	TwoFactorEnabled int64  `json:"two_factor_enabled"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateUserTwoFactorSecret(ctx context.Context, arg UpdateUserTwoFactorSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTwoFactorSecret, arg.TwoFactorSecret, arg.TwoFactorEnabled, arg.ID)
	return err
}
