// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcement.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (id, severity, title, description, dismissible, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, severity, title, description, dismissible, active, created_at, updated_at
`

type CreateAnnouncementParams struct {
	ID          string             `json:"id"`
	Severity    string             `json:"severity"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Dismissible bool               `json:"dismissible"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.ID,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.Dismissible,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.Dismissible,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
SELECT id, severity, title, description, dismissible, active, created_at, updated_at
FROM announcements
WHERE active = $1
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAnnouncements(ctx context.Context, active bool) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listActiveAnnouncements, active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.Dismissible,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
