// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPIKeysByUserID = `-- name: CountAPIKeysByUserID :one
SELECT COUNT(*) FROM api_keys WHERE user_id = $1
`

func (q *Queries) CountAPIKeysByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeysByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (
    id, created_at, updated_at, user_id, name, key_hash, key_prefix,
    scope, expires_at, last_used_at, last_used_ip, is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateAPIKeyParams struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Scope      string             `json:"scope"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp string             `json:"last_used_ip"`
	IsActive   bool               `json:"is_active"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scope,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.LastUsedIp,
		arg.IsActive,
	)
	return err
}

const findAPIKeyByIDForUser = `-- name: FindAPIKeyByIDForUser :one
SELECT id, created_at, updated_at, user_id, name, key_hash, key_prefix, scope, expires_at, last_used_at, last_used_ip, is_active FROM api_keys WHERE id = $1 AND user_id = $2
`

type FindAPIKeyByIDForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) FindAPIKeyByIDForUser(ctx context.Context, arg FindAPIKeyByIDForUserParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByIDForUser, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.IsActive,
	)
	return i, err
}

const findAPIKeyByKeyHash = `-- name: FindAPIKeyByKeyHash :one
SELECT id, created_at, updated_at, user_id, name, key_hash, key_prefix, scope, expires_at, last_used_at, last_used_ip, is_active FROM api_keys WHERE key_hash = $1
`

func (q *Queries) FindAPIKeyByKeyHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByKeyHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.IsActive,
	)
	return i, err
}

const listAPIKeysByUserID = `-- name: ListAPIKeysByUserID :many
SELECT id, created_at, updated_at, user_id, name, key_hash, key_prefix, scope, expires_at, last_used_at, last_used_ip, is_active FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUserID(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Scope,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET is_active = false
WHERE id = $1 AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :execrows
UPDATE api_keys
SET last_used_at = $2, last_used_ip = $3
WHERE id = $1
`

type UpdateAPIKeyLastUsedParams struct {
	ID         string             `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp string             `json:"last_used_ip"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAPIKeyLastUsed, arg.ID, arg.LastUsedAt, arg.LastUsedIp)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
