// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: erasure_records.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createErasureRecord = `-- name: CreateErasureRecord :exec

INSERT INTO erasure_records (
    id, created_at, operator_id, subject_kind, subject_fingerprint, changes, manual_review
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
`

type CreateErasureRecordParams struct {
	ID                 string             `json:"id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OperatorID         string             `json:"operator_id"`
	SubjectKind        string             `json:"subject_kind"`
	SubjectFingerprint string             `json:"subject_fingerprint"`
	Changes            []byte             `json:"changes"`
	ManualReview       int32              `json:"manual_review"`
}

// Spec 095: one row per erasure. Never the address: a keyed fingerprint.
func (q *Queries) CreateErasureRecord(ctx context.Context, arg CreateErasureRecordParams) error {
	_, err := q.db.Exec(ctx, createErasureRecord,
		arg.ID,
		arg.CreatedAt,
		arg.OperatorID,
		arg.SubjectKind,
		arg.SubjectFingerprint,
		arg.Changes,
		arg.ManualReview,
	)
	return err
}

const listErasureRecordsByFingerprint = `-- name: ListErasureRecordsByFingerprint :many
SELECT id, created_at, operator_id, subject_kind, subject_fingerprint, changes, manual_review FROM erasure_records
WHERE subject_fingerprint = $1
ORDER BY created_at DESC
`

func (q *Queries) ListErasureRecordsByFingerprint(ctx context.Context, subjectFingerprint string) ([]ErasureRecord, error) {
	rows, err := q.db.Query(ctx, listErasureRecordsByFingerprint, subjectFingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErasureRecord{}
	for rows.Next() {
		var i ErasureRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.OperatorID,
			&i.SubjectKind,
			&i.SubjectFingerprint,
			&i.Changes,
			&i.ManualReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
