// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: escalation_policy.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEscalationPolicy = `-- name: CreateEscalationPolicy :exec
INSERT INTO escalation_policies (id, name, scope_kind, scope_value, is_active, priority, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateEscalationPolicyParams struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	ScopeKind  string             `json:"scope_kind"`
	ScopeValue string             `json:"scope_value"`
	IsActive   bool               `json:"is_active"`
	Priority   int32              `json:"priority"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEscalationPolicy(ctx context.Context, arg CreateEscalationPolicyParams) error {
	_, err := q.db.Exec(ctx, createEscalationPolicy,
		arg.ID,
		arg.Name,
		arg.ScopeKind,
		arg.ScopeValue,
		arg.IsActive,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createEscalationStep = `-- name: CreateEscalationStep :exec
INSERT INTO escalation_steps (id, policy_id, step_order, delay_minutes, channel_ids)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEscalationStepParams struct {
	ID           string `json:"id"`
	PolicyID     string `json:"policy_id"`
	StepOrder    int32  `json:"step_order"`
	DelayMinutes int32  `json:"delay_minutes"`
	ChannelIds   []byte `json:"channel_ids"`
}

func (q *Queries) CreateEscalationStep(ctx context.Context, arg CreateEscalationStepParams) error {
	_, err := q.db.Exec(ctx, createEscalationStep,
		arg.ID,
		arg.PolicyID,
		arg.StepOrder,
		arg.DelayMinutes,
		arg.ChannelIds,
	)
	return err
}

const deleteEscalationPolicy = `-- name: DeleteEscalationPolicy :execrows
DELETE FROM escalation_policies WHERE id = $1
`

func (q *Queries) DeleteEscalationPolicy(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEscalationPolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEscalationStepsByPolicy = `-- name: DeleteEscalationStepsByPolicy :exec
DELETE FROM escalation_steps WHERE policy_id = $1
`

func (q *Queries) DeleteEscalationStepsByPolicy(ctx context.Context, policyID string) error {
	_, err := q.db.Exec(ctx, deleteEscalationStepsByPolicy, policyID)
	return err
}

const findEscalationPolicyByID = `-- name: FindEscalationPolicyByID :one
SELECT id, name, scope_kind, scope_value, is_active, priority, created_at, updated_at FROM escalation_policies WHERE id = $1
`

func (q *Queries) FindEscalationPolicyByID(ctx context.Context, id string) (EscalationPolicy, error) {
	row := q.db.QueryRow(ctx, findEscalationPolicyByID, id)
	var i EscalationPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScopeKind,
		&i.ScopeValue,
		&i.IsActive,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEscalationPolicies = `-- name: ListEscalationPolicies :many
SELECT id, name, scope_kind, scope_value, is_active, priority, created_at, updated_at FROM escalation_policies ORDER BY priority ASC, created_at ASC
`

func (q *Queries) ListEscalationPolicies(ctx context.Context) ([]EscalationPolicy, error) {
	rows, err := q.db.Query(ctx, listEscalationPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EscalationPolicy{}
	for rows.Next() {
		var i EscalationPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ScopeKind,
			&i.ScopeValue,
			&i.IsActive,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscalationStepsByPolicy = `-- name: ListEscalationStepsByPolicy :many
SELECT id, policy_id, step_order, delay_minutes, channel_ids FROM escalation_steps WHERE policy_id = $1 ORDER BY step_order ASC
`

func (q *Queries) ListEscalationStepsByPolicy(ctx context.Context, policyID string) ([]EscalationStep, error) {
	rows, err := q.db.Query(ctx, listEscalationStepsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EscalationStep{}
	for rows.Next() {
		var i EscalationStep
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.StepOrder,
			&i.DelayMinutes,
			&i.ChannelIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEscalationPriority = `-- name: NextEscalationPriority :one
SELECT COALESCE(MAX(priority), 0)::int + 1 AS next FROM escalation_policies WHERE is_active = TRUE
`

func (q *Queries) NextEscalationPriority(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextEscalationPriority)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const setEscalationPolicyPriority = `-- name: SetEscalationPolicyPriority :execrows
UPDATE escalation_policies
SET priority = $2, updated_at = $3
WHERE id = $1
`

type SetEscalationPolicyPriorityParams struct {
	ID        string             `json:"id"`
	Priority  int32              `json:"priority"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetEscalationPolicyPriority(ctx context.Context, arg SetEscalationPolicyPriorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEscalationPolicyPriority, arg.ID, arg.Priority, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEscalationPolicy = `-- name: UpdateEscalationPolicy :execrows
UPDATE escalation_policies
SET name = $2, scope_kind = $3, scope_value = $4, is_active = $5, priority = $6, updated_at = $7
WHERE id = $1
`

type UpdateEscalationPolicyParams struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	ScopeKind  string             `json:"scope_kind"`
	ScopeValue string             `json:"scope_value"`
	IsActive   bool               `json:"is_active"`
	Priority   int32              `json:"priority"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEscalationPolicy(ctx context.Context, arg UpdateEscalationPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEscalationPolicy,
		arg.ID,
		arg.Name,
		arg.ScopeKind,
		arg.ScopeValue,
		arg.IsActive,
		arg.Priority,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
