// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expiry_notification_log.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpiryNotificationLogsByKey = `-- name: CountExpiryNotificationLogsByKey :one
SELECT COUNT(*) FROM expiry_notification_logs
WHERE resource_id = $1 AND expiry_type = $2 AND threshold = $3
`

type CountExpiryNotificationLogsByKeyParams struct {
	ResourceID string `json:"resource_id"`
	ExpiryType string `json:"expiry_type"`
	Threshold  int32  `json:"threshold"`
}

func (q *Queries) CountExpiryNotificationLogsByKey(ctx context.Context, arg CountExpiryNotificationLogsByKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiryNotificationLogsByKey, arg.ResourceID, arg.ExpiryType, arg.Threshold)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpiryNotificationLog = `-- name: CreateExpiryNotificationLog :exec
INSERT INTO expiry_notification_logs (
    id, resource_id, expiry_type, threshold, sent_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateExpiryNotificationLogParams struct {
	ID         string             `json:"id"`
	ResourceID string             `json:"resource_id"`
	ExpiryType string             `json:"expiry_type"`
	Threshold  int32              `json:"threshold"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateExpiryNotificationLog(ctx context.Context, arg CreateExpiryNotificationLogParams) error {
	_, err := q.db.Exec(ctx, createExpiryNotificationLog,
		arg.ID,
		arg.ResourceID,
		arg.ExpiryType,
		arg.Threshold,
		arg.SentAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiryNotificationLogsByResourceIDAndType = `-- name: DeleteExpiryNotificationLogsByResourceIDAndType :exec
DELETE FROM expiry_notification_logs
WHERE resource_id = $1 AND expiry_type = $2
`

type DeleteExpiryNotificationLogsByResourceIDAndTypeParams struct {
	ResourceID string `json:"resource_id"`
	ExpiryType string `json:"expiry_type"`
}

func (q *Queries) DeleteExpiryNotificationLogsByResourceIDAndType(ctx context.Context, arg DeleteExpiryNotificationLogsByResourceIDAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteExpiryNotificationLogsByResourceIDAndType, arg.ResourceID, arg.ExpiryType)
	return err
}

const deleteExpiryNotificationLogsOlderThan = `-- name: DeleteExpiryNotificationLogsOlderThan :exec
DELETE FROM expiry_notification_logs
WHERE sent_at < $1
`

func (q *Queries) DeleteExpiryNotificationLogsOlderThan(ctx context.Context, sentAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiryNotificationLogsOlderThan, sentAt)
	return err
}
