// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incident.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIncidentsByResourceID = `-- name: CountIncidentsByResourceID :one
SELECT COUNT(*) FROM incidents WHERE resource_id = $1
`

func (q *Queries) CountIncidentsByResourceID(ctx context.Context, resourceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidentsByResourceID, resourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncident = `-- name: CreateIncident :exec

INSERT INTO incidents (
    id, created_at, updated_at, resource_id, cause,
    resolved_at, started_at, details
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateIncidentParams struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ResourceID string             `json:"resource_id"`
	Cause      string             `json:"cause"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	Details    []byte             `json:"details"`
}

// US2 of spec 048: incident_repository sqlc migration. No M2M;
// controlled-N+1 preload for Resource and IncidentDiagnostics
// (1-to-1, FK uniqueIndex on incident_id).
func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) error {
	_, err := q.db.Exec(ctx, createIncident,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ResourceID,
		arg.Cause,
		arg.ResolvedAt,
		arg.StartedAt,
		arg.Details,
	)
	return err
}

const deleteIncident = `-- name: DeleteIncident :execrows
DELETE FROM incidents WHERE id = $1
`

func (q *Queries) DeleteIncident(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIncident, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveIncidentByResourceID = `-- name: FindActiveIncidentByResourceID :one
SELECT id, created_at, updated_at, resource_id, cause, resolved_at, started_at, details FROM incidents
WHERE resource_id = $1 AND resolved_at IS NULL
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) FindActiveIncidentByResourceID(ctx context.Context, resourceID string) (Incident, error) {
	row := q.db.QueryRow(ctx, findActiveIncidentByResourceID, resourceID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceID,
		&i.Cause,
		&i.ResolvedAt,
		&i.StartedAt,
		&i.Details,
	)
	return i, err
}

const findIncidentByID = `-- name: FindIncidentByID :one
SELECT id, created_at, updated_at, resource_id, cause, resolved_at, started_at, details FROM incidents WHERE id = $1
`

func (q *Queries) FindIncidentByID(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, findIncidentByID, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceID,
		&i.Cause,
		&i.ResolvedAt,
		&i.StartedAt,
		&i.Details,
	)
	return i, err
}

const findIncidentsByIDs = `-- name: FindIncidentsByIDs :many
SELECT id, created_at, updated_at, resource_id, cause, resolved_at, started_at, details FROM incidents WHERE id = ANY($1::text[])
`

func (q *Queries) FindIncidentsByIDs(ctx context.Context, dollar_1 []string) ([]Incident, error) {
	rows, err := q.db.Query(ctx, findIncidentsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceID,
			&i.Cause,
			&i.ResolvedAt,
			&i.StartedAt,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findIncidentsByResource = `-- name: FindIncidentsByResource :many
SELECT id, created_at, updated_at, resource_id, cause, resolved_at, started_at, details FROM incidents
WHERE resource_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type FindIncidentsByResourceParams struct {
	ResourceID string `json:"resource_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) FindIncidentsByResource(ctx context.Context, arg FindIncidentsByResourceParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, findIncidentsByResource, arg.ResourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceID,
			&i.Cause,
			&i.ResolvedAt,
			&i.StartedAt,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLastResolvedIncident = `-- name: FindLastResolvedIncident :one
SELECT id, created_at, updated_at, resource_id, cause, resolved_at, started_at, details FROM incidents
WHERE resolved_at IS NOT NULL
ORDER BY resolved_at DESC
LIMIT 1
`

func (q *Queries) FindLastResolvedIncident(ctx context.Context) (Incident, error) {
	row := q.db.QueryRow(ctx, findLastResolvedIncident)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceID,
		&i.Cause,
		&i.ResolvedAt,
		&i.StartedAt,
		&i.Details,
	)
	return i, err
}

const findUnresolvedIncidents = `-- name: FindUnresolvedIncidents :many
SELECT id, created_at, updated_at, resource_id, cause, resolved_at, started_at, details FROM incidents
WHERE resolved_at IS NULL
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type FindUnresolvedIncidentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindUnresolvedIncidents(ctx context.Context, arg FindUnresolvedIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, findUnresolvedIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceID,
			&i.Cause,
			&i.ResolvedAt,
			&i.StartedAt,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncidentStatsPG = `-- name: GetIncidentStatsPG :one
WITH window_inc AS (
    SELECT resource_id FROM incidents WHERE started_at >= $1
)
SELECT
    COUNT(*)::bigint                       AS total_incidents,
    COUNT(DISTINCT resource_id)::bigint    AS affected_monitors
FROM window_inc
`

type GetIncidentStatsPGRow struct {
	TotalIncidents   int64 `json:"total_incidents"`
	AffectedMonitors int64 `json:"affected_monitors"`
}

// Two aggregated counts in a single round-trip. CTE keeps the row scan
// to one pass over the window.
func (q *Queries) GetIncidentStatsPG(ctx context.Context, startedAt pgtype.Timestamptz) (GetIncidentStatsPGRow, error) {
	row := q.db.QueryRow(ctx, getIncidentStatsPG, startedAt)
	var i GetIncidentStatsPGRow
	err := row.Scan(&i.TotalIncidents, &i.AffectedMonitors)
	return i, err
}

const hasActiveIncident = `-- name: HasActiveIncident :one
SELECT EXISTS(SELECT 1 FROM incidents WHERE resolved_at IS NULL) AS has_active
`

func (q *Queries) HasActiveIncident(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveIncident)
	var has_active bool
	err := row.Scan(&has_active)
	return has_active, err
}

const listIncidentDiagnosticsByIncidentIDs = `-- name: ListIncidentDiagnosticsByIncidentIDs :many
SELECT id, created_at, updated_at, incident_id, request_method, request_url, request_headers, request_timeout, http_status_code, response_headers, response_body, response_size, failure_type, error_message, error_summary, total_duration, dns_duration, tls_duration, first_byte_duration, body_truncated, body_encoded, icmp_available, icmp_reachable, icmp_rtt_ms, root_cause_hint, keyword, keyword_mode, keyword_found FROM incident_diagnostics
WHERE incident_id = ANY($1::text[])
`

func (q *Queries) ListIncidentDiagnosticsByIncidentIDs(ctx context.Context, dollar_1 []string) ([]IncidentDiagnostic, error) {
	rows, err := q.db.Query(ctx, listIncidentDiagnosticsByIncidentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentDiagnostic{}
	for rows.Next() {
		var i IncidentDiagnostic
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IncidentID,
			&i.RequestMethod,
			&i.RequestUrl,
			&i.RequestHeaders,
			&i.RequestTimeout,
			&i.HttpStatusCode,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.ResponseSize,
			&i.FailureType,
			&i.ErrorMessage,
			&i.ErrorSummary,
			&i.TotalDuration,
			&i.DnsDuration,
			&i.TlsDuration,
			&i.FirstByteDuration,
			&i.BodyTruncated,
			&i.BodyEncoded,
			&i.IcmpAvailable,
			&i.IcmpReachable,
			&i.IcmpRttMs,
			&i.RootCauseHint,
			&i.Keyword,
			&i.KeywordMode,
			&i.KeywordFound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, created_at, updated_at, resource_id, cause, resolved_at, started_at, details FROM incidents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListIncidentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceID,
			&i.Cause,
			&i.ResolvedAt,
			&i.StartedAt,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncident = `-- name: UpdateIncident :execrows
UPDATE incidents
SET resource_id = $2,
    cause       = $3,
    resolved_at = $4,
    started_at  = $5,
    details     = $6,
    updated_at  = $7
WHERE id = $1
`

type UpdateIncidentParams struct {
	ID         string             `json:"id"`
	ResourceID string             `json:"resource_id"`
	Cause      string             `json:"cause"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	Details    []byte             `json:"details"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIncident,
		arg.ID,
		arg.ResourceID,
		arg.Cause,
		arg.ResolvedAt,
		arg.StartedAt,
		arg.Details,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
