// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incident_updates.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncidentUpdate = `-- name: CreateIncidentUpdate :exec
INSERT INTO incident_updates (
    id, incident_id, status, message, posted_by, posted_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateIncidentUpdateParams struct {
	ID         string             `json:"id"`
	IncidentID string             `json:"incident_id"`
	Status     string             `json:"status"`
	Message    string             `json:"message"`
	PostedBy   string             `json:"posted_by"`
	PostedAt   pgtype.Timestamptz `json:"posted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateIncidentUpdate(ctx context.Context, arg CreateIncidentUpdateParams) error {
	_, err := q.db.Exec(ctx, createIncidentUpdate,
		arg.ID,
		arg.IncidentID,
		arg.Status,
		arg.Message,
		arg.PostedBy,
		arg.PostedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteIncidentUpdate = `-- name: DeleteIncidentUpdate :exec
DELETE FROM incident_updates WHERE id = $1
`

func (q *Queries) DeleteIncidentUpdate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteIncidentUpdate, id)
	return err
}

const getIncidentUpdate = `-- name: GetIncidentUpdate :one
SELECT id, incident_id, status, message, posted_by, posted_at, created_at, updated_at
FROM incident_updates
WHERE id = $1
`

func (q *Queries) GetIncidentUpdate(ctx context.Context, id string) (IncidentUpdate, error) {
	row := q.db.QueryRow(ctx, getIncidentUpdate, id)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Message,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidentUpdates = `-- name: ListIncidentUpdates :many
SELECT id, incident_id, status, message, posted_by, posted_at, created_at, updated_at
FROM incident_updates
WHERE incident_id = $1
ORDER BY posted_at DESC
`

func (q *Queries) ListIncidentUpdates(ctx context.Context, incidentID string) ([]IncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listIncidentUpdates, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentUpdate{}
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Message,
			&i.PostedBy,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentUpdatesByPostedBy = `-- name: ListIncidentUpdatesByPostedBy :many
SELECT id, incident_id, status, message, posted_by, posted_at, created_at, updated_at
FROM incident_updates
WHERE posted_by = $1
ORDER BY posted_at DESC
`

// Updates a given user authored (spec 094). posted_by holds the user ID.
func (q *Queries) ListIncidentUpdatesByPostedBy(ctx context.Context, postedBy string) ([]IncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listIncidentUpdatesByPostedBy, postedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentUpdate{}
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Message,
			&i.PostedBy,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkIncidentUpdatesAuthor = `-- name: UnlinkIncidentUpdatesAuthor :execrows
UPDATE incident_updates SET posted_by = '' WHERE posted_by = $1
`

// Spec 095: an erased account's updates stay published, without an author.
func (q *Queries) UnlinkIncidentUpdatesAuthor(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkIncidentUpdatesAuthor, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIncidentUpdate = `-- name: UpdateIncidentUpdate :exec
UPDATE incident_updates
SET status = $2,
    message = $3,
    posted_at = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateIncidentUpdateParams struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	Message   string             `json:"message"`
	PostedAt  pgtype.Timestamptz `json:"posted_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateIncidentUpdate(ctx context.Context, arg UpdateIncidentUpdateParams) error {
	_, err := q.db.Exec(ctx, updateIncidentUpdate,
		arg.ID,
		arg.Status,
		arg.Message,
		arg.PostedAt,
		arg.UpdatedAt,
	)
	return err
}
