// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incident_diagnostics.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncidentDiagnostics = `-- name: CreateIncidentDiagnostics :one
INSERT INTO incident_diagnostics (
    id, created_at, updated_at, incident_id,
    request_method, request_url, request_headers, request_timeout,
    http_status_code, response_headers, response_body, response_size,
    failure_type, error_message, error_summary,
    total_duration, dns_duration, tls_duration, first_byte_duration,
    body_truncated, body_encoded,
    keyword, keyword_mode, keyword_found,
    icmp_available, icmp_reachable, icmp_rtt_ms, root_cause_hint
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
        $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28)
RETURNING id, created_at, updated_at, incident_id, request_method, request_url, request_headers, request_timeout, http_status_code, response_headers, response_body, response_size, failure_type, error_message, error_summary, total_duration, dns_duration, tls_duration, first_byte_duration, body_truncated, body_encoded, icmp_available, icmp_reachable, icmp_rtt_ms, root_cause_hint, keyword, keyword_mode, keyword_found
`

type CreateIncidentDiagnosticsParams struct {
	ID                string             `json:"id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	IncidentID        string             `json:"incident_id"`
	RequestMethod     string             `json:"request_method"`
	RequestUrl        string             `json:"request_url"`
	RequestHeaders    string             `json:"request_headers"`
	RequestTimeout    int32              `json:"request_timeout"`
	HttpStatusCode    int32              `json:"http_status_code"`
	ResponseHeaders   string             `json:"response_headers"`
	ResponseBody      string             `json:"response_body"`
	ResponseSize      int32              `json:"response_size"`
	FailureType       string             `json:"failure_type"`
	ErrorMessage      string             `json:"error_message"`
	ErrorSummary      string             `json:"error_summary"`
	TotalDuration     int32              `json:"total_duration"`
	DnsDuration       int32              `json:"dns_duration"`
	TlsDuration       int32              `json:"tls_duration"`
	FirstByteDuration int32              `json:"first_byte_duration"`
	BodyTruncated     bool               `json:"body_truncated"`
	BodyEncoded       bool               `json:"body_encoded"`
	Keyword           pgtype.Text        `json:"keyword"`
	KeywordMode       pgtype.Text        `json:"keyword_mode"`
	KeywordFound      pgtype.Bool        `json:"keyword_found"`
	IcmpAvailable     pgtype.Bool        `json:"icmp_available"`
	IcmpReachable     pgtype.Bool        `json:"icmp_reachable"`
	IcmpRttMs         pgtype.Int4        `json:"icmp_rtt_ms"`
	RootCauseHint     string             `json:"root_cause_hint"`
}

func (q *Queries) CreateIncidentDiagnostics(ctx context.Context, arg CreateIncidentDiagnosticsParams) (IncidentDiagnostic, error) {
	row := q.db.QueryRow(ctx, createIncidentDiagnostics,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IncidentID,
		arg.RequestMethod,
		arg.RequestUrl,
		arg.RequestHeaders,
		arg.RequestTimeout,
		arg.HttpStatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ResponseSize,
		arg.FailureType,
		arg.ErrorMessage,
		arg.ErrorSummary,
		arg.TotalDuration,
		arg.DnsDuration,
		arg.TlsDuration,
		arg.FirstByteDuration,
		arg.BodyTruncated,
		arg.BodyEncoded,
		arg.Keyword,
		arg.KeywordMode,
		arg.KeywordFound,
		arg.IcmpAvailable,
		arg.IcmpReachable,
		arg.IcmpRttMs,
		arg.RootCauseHint,
	)
	var i IncidentDiagnostic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncidentID,
		&i.RequestMethod,
		&i.RequestUrl,
		&i.RequestHeaders,
		&i.RequestTimeout,
		&i.HttpStatusCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ResponseSize,
		&i.FailureType,
		&i.ErrorMessage,
		&i.ErrorSummary,
		&i.TotalDuration,
		&i.DnsDuration,
		&i.TlsDuration,
		&i.FirstByteDuration,
		&i.BodyTruncated,
		&i.BodyEncoded,
		&i.IcmpAvailable,
		&i.IcmpReachable,
		&i.IcmpRttMs,
		&i.RootCauseHint,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordFound,
	)
	return i, err
}

const deleteIncidentDiagnostics = `-- name: DeleteIncidentDiagnostics :execrows
DELETE FROM incident_diagnostics WHERE id = $1
`

func (q *Queries) DeleteIncidentDiagnostics(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIncidentDiagnostics, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findIncidentDiagnosticsByIncidentID = `-- name: FindIncidentDiagnosticsByIncidentID :one
SELECT id, created_at, updated_at, incident_id, request_method, request_url, request_headers, request_timeout, http_status_code, response_headers, response_body, response_size, failure_type, error_message, error_summary, total_duration, dns_duration, tls_duration, first_byte_duration, body_truncated, body_encoded, icmp_available, icmp_reachable, icmp_rtt_ms, root_cause_hint, keyword, keyword_mode, keyword_found FROM incident_diagnostics WHERE incident_id = $1
`

func (q *Queries) FindIncidentDiagnosticsByIncidentID(ctx context.Context, incidentID string) (IncidentDiagnostic, error) {
	row := q.db.QueryRow(ctx, findIncidentDiagnosticsByIncidentID, incidentID)
	var i IncidentDiagnostic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncidentID,
		&i.RequestMethod,
		&i.RequestUrl,
		&i.RequestHeaders,
		&i.RequestTimeout,
		&i.HttpStatusCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ResponseSize,
		&i.FailureType,
		&i.ErrorMessage,
		&i.ErrorSummary,
		&i.TotalDuration,
		&i.DnsDuration,
		&i.TlsDuration,
		&i.FirstByteDuration,
		&i.BodyTruncated,
		&i.BodyEncoded,
		&i.IcmpAvailable,
		&i.IcmpReachable,
		&i.IcmpRttMs,
		&i.RootCauseHint,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordFound,
	)
	return i, err
}

const updateIncidentDiagnostics = `-- name: UpdateIncidentDiagnostics :execrows
UPDATE incident_diagnostics
SET request_method = $2,
    request_url = $3,
    request_headers = $4,
    request_timeout = $5,
    http_status_code = $6,
    response_headers = $7,
    response_body = $8,
    response_size = $9,
    failure_type = $10,
    error_message = $11,
    error_summary = $12,
    total_duration = $13,
    dns_duration = $14,
    tls_duration = $15,
    first_byte_duration = $16,
    body_truncated = $17,
    body_encoded = $18,
    keyword = $19,
    keyword_mode = $20,
    keyword_found = $21,
    icmp_available = $22,
    icmp_reachable = $23,
    icmp_rtt_ms = $24,
    root_cause_hint = $25,
    updated_at = $26
WHERE id = $1
`

type UpdateIncidentDiagnosticsParams struct {
	ID                string             `json:"id"`
	RequestMethod     string             `json:"request_method"`
	RequestUrl        string             `json:"request_url"`
	RequestHeaders    string             `json:"request_headers"`
	RequestTimeout    int32              `json:"request_timeout"`
	HttpStatusCode    int32              `json:"http_status_code"`
	ResponseHeaders   string             `json:"response_headers"`
	ResponseBody      string             `json:"response_body"`
	ResponseSize      int32              `json:"response_size"`
	FailureType       string             `json:"failure_type"`
	ErrorMessage      string             `json:"error_message"`
	ErrorSummary      string             `json:"error_summary"`
	TotalDuration     int32              `json:"total_duration"`
	DnsDuration       int32              `json:"dns_duration"`
	TlsDuration       int32              `json:"tls_duration"`
	FirstByteDuration int32              `json:"first_byte_duration"`
	BodyTruncated     bool               `json:"body_truncated"`
	BodyEncoded       bool               `json:"body_encoded"`
	Keyword           pgtype.Text        `json:"keyword"`
	KeywordMode       pgtype.Text        `json:"keyword_mode"`
	KeywordFound      pgtype.Bool        `json:"keyword_found"`
	IcmpAvailable     pgtype.Bool        `json:"icmp_available"`
	IcmpReachable     pgtype.Bool        `json:"icmp_reachable"`
	IcmpRttMs         pgtype.Int4        `json:"icmp_rtt_ms"`
	RootCauseHint     string             `json:"root_cause_hint"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateIncidentDiagnostics(ctx context.Context, arg UpdateIncidentDiagnosticsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIncidentDiagnostics,
		arg.ID,
		arg.RequestMethod,
		arg.RequestUrl,
		arg.RequestHeaders,
		arg.RequestTimeout,
		arg.HttpStatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ResponseSize,
		arg.FailureType,
		arg.ErrorMessage,
		arg.ErrorSummary,
		arg.TotalDuration,
		arg.DnsDuration,
		arg.TlsDuration,
		arg.FirstByteDuration,
		arg.BodyTruncated,
		arg.BodyEncoded,
		arg.Keyword,
		arg.KeywordMode,
		arg.KeywordFound,
		arg.IcmpAvailable,
		arg.IcmpReachable,
		arg.IcmpRttMs,
		arg.RootCauseHint,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
