// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incident_event_step.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncidentEventStep = `-- name: CreateIncidentEventStep :exec
INSERT INTO incident_event_steps (id, created_at, updated_at, incident_id, step, message)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateIncidentEventStepParams struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	IncidentID string             `json:"incident_id"`
	Step       string             `json:"step"`
	Message    pgtype.Text        `json:"message"`
}

func (q *Queries) CreateIncidentEventStep(ctx context.Context, arg CreateIncidentEventStepParams) error {
	_, err := q.db.Exec(ctx, createIncidentEventStep,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IncidentID,
		arg.Step,
		arg.Message,
	)
	return err
}

const deleteIncidentEventStep = `-- name: DeleteIncidentEventStep :execrows
DELETE FROM incident_event_steps WHERE id = $1
`

func (q *Queries) DeleteIncidentEventStep(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIncidentEventStep, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findIncidentEventStepByID = `-- name: FindIncidentEventStepByID :one
SELECT
    s.id, s.created_at, s.updated_at, s.incident_id, s.step, s.message,
    i.created_at AS i_created_at,
    i.updated_at AS i_updated_at,
    i.resource_id,
    i.cause,
    i.resolved_at,
    i.started_at,
    i.details
FROM incident_event_steps s
JOIN incidents i ON i.id = s.incident_id
WHERE s.id = $1
`

type FindIncidentEventStepByIDRow struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	IncidentID string             `json:"incident_id"`
	Step       string             `json:"step"`
	Message    pgtype.Text        `json:"message"`
	ICreatedAt pgtype.Timestamptz `json:"i_created_at"`
	IUpdatedAt pgtype.Timestamptz `json:"i_updated_at"`
	ResourceID string             `json:"resource_id"`
	Cause      string             `json:"cause"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	Details    []byte             `json:"details"`
}

// Single JOIN preload (Clarification Q1) — incident embedded into event step.
func (q *Queries) FindIncidentEventStepByID(ctx context.Context, id string) (FindIncidentEventStepByIDRow, error) {
	row := q.db.QueryRow(ctx, findIncidentEventStepByID, id)
	var i FindIncidentEventStepByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncidentID,
		&i.Step,
		&i.Message,
		&i.ICreatedAt,
		&i.IUpdatedAt,
		&i.ResourceID,
		&i.Cause,
		&i.ResolvedAt,
		&i.StartedAt,
		&i.Details,
	)
	return i, err
}

const findLastIncidentEventStepByIncidentAndStep = `-- name: FindLastIncidentEventStepByIncidentAndStep :one
SELECT id, created_at, updated_at, incident_id, step, message FROM incident_event_steps
WHERE incident_id = $1 AND step = $2
ORDER BY created_at DESC
LIMIT 1
`

type FindLastIncidentEventStepByIncidentAndStepParams struct {
	IncidentID string `json:"incident_id"`
	Step       string `json:"step"`
}

func (q *Queries) FindLastIncidentEventStepByIncidentAndStep(ctx context.Context, arg FindLastIncidentEventStepByIncidentAndStepParams) (IncidentEventStep, error) {
	row := q.db.QueryRow(ctx, findLastIncidentEventStepByIncidentAndStep, arg.IncidentID, arg.Step)
	var i IncidentEventStep
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncidentID,
		&i.Step,
		&i.Message,
	)
	return i, err
}

const listIncidentEventSteps = `-- name: ListIncidentEventSteps :many
SELECT id, created_at, updated_at, incident_id, step, message FROM incident_event_steps
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListIncidentEventStepsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIncidentEventSteps(ctx context.Context, arg ListIncidentEventStepsParams) ([]IncidentEventStep, error) {
	rows, err := q.db.Query(ctx, listIncidentEventSteps, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentEventStep{}
	for rows.Next() {
		var i IncidentEventStep
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IncidentID,
			&i.Step,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentEventStep = `-- name: UpdateIncidentEventStep :execrows
UPDATE incident_event_steps
SET incident_id = $2, step = $3, message = $4, updated_at = $5
WHERE id = $1
`

type UpdateIncidentEventStepParams struct {
	ID         string             `json:"id"`
	IncidentID string             `json:"incident_id"`
	Step       string             `json:"step"`
	Message    pgtype.Text        `json:"message"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateIncidentEventStep(ctx context.Context, arg UpdateIncidentEventStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIncidentEventStep,
		arg.ID,
		arg.IncidentID,
		arg.Step,
		arg.Message,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
