// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaintenance = `-- name: CreateMaintenance :exec
INSERT INTO maintenances (
    id, created_at, updated_at, title, description, strategy, status,
    start_at, end_at, cron_expr, window_minutes, timezone,
    effective_from, effective_until, started_at, ended_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type CreateMaintenanceParams struct {
	ID             string             `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Strategy       string             `json:"strategy"`
	Status         string             `json:"status"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	EndAt          pgtype.Timestamptz `json:"end_at"`
	CronExpr       pgtype.Text        `json:"cron_expr"`
	WindowMinutes  pgtype.Int4        `json:"window_minutes"`
	Timezone       pgtype.Text        `json:"timezone"`
	EffectiveFrom  pgtype.Timestamptz `json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `json:"effective_until"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) error {
	_, err := q.db.Exec(ctx, createMaintenance,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.Strategy,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.CronExpr,
		arg.WindowMinutes,
		arg.Timezone,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const deleteMaintenance = `-- name: DeleteMaintenance :execrows
DELETE FROM maintenances WHERE id = $1
`

func (q *Queries) DeleteMaintenance(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMaintenance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveMaintenancesForResource = `-- name: FindActiveMaintenancesForResource :many
SELECT DISTINCT m.id, m.created_at, m.updated_at, m.title, m.description, m.strategy, m.status, m.start_at, m.end_at, m.cron_expr, m.window_minutes, m.timezone, m.effective_from, m.effective_until, m.started_at, m.ended_at FROM maintenances m
JOIN maintenance_resources mr ON mr.maintenance_id = m.id
WHERE mr.resource_id = $1
  AND (
    m.status = 'active'
    OR (m.strategy = 'one_time' AND m.status = 'scheduled' AND m.start_at <= $2 AND m.end_at >= $3)
  )
`

type FindActiveMaintenancesForResourceParams struct {
	ResourceID string             `json:"resource_id"`
	StartAt    pgtype.Timestamptz `json:"start_at"`
	EndAt      pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) FindActiveMaintenancesForResource(ctx context.Context, arg FindActiveMaintenancesForResourceParams) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, findActiveMaintenancesForResource, arg.ResourceID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Strategy,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CronExpr,
			&i.WindowMinutes,
			&i.Timezone,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMaintenanceByID = `-- name: FindMaintenanceByID :one
SELECT id, created_at, updated_at, title, description, strategy, status, start_at, end_at, cron_expr, window_minutes, timezone, effective_from, effective_until, started_at, ended_at FROM maintenances WHERE id = $1
`

func (q *Queries) FindMaintenanceByID(ctx context.Context, id string) (Maintenance, error) {
	row := q.db.QueryRow(ctx, findMaintenanceByID, id)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.Strategy,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CronExpr,
		&i.WindowMinutes,
		&i.Timezone,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const linkMaintenanceResource = `-- name: LinkMaintenanceResource :exec
INSERT INTO maintenance_resources (maintenance_id, resource_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkMaintenanceResourceParams struct {
	MaintenanceID string `json:"maintenance_id"`
	ResourceID    string `json:"resource_id"`
}

func (q *Queries) LinkMaintenanceResource(ctx context.Context, arg LinkMaintenanceResourceParams) error {
	_, err := q.db.Exec(ctx, linkMaintenanceResource, arg.MaintenanceID, arg.ResourceID)
	return err
}

const listMaintenanceResourceIDsByMaintenanceID = `-- name: ListMaintenanceResourceIDsByMaintenanceID :many
SELECT resource_id FROM maintenance_resources WHERE maintenance_id = $1
`

func (q *Queries) ListMaintenanceResourceIDsByMaintenanceID(ctx context.Context, maintenanceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMaintenanceResourceIDsByMaintenanceID, maintenanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource_id string
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenancesAll = `-- name: ListMaintenancesAll :many
SELECT id, created_at, updated_at, title, description, strategy, status, start_at, end_at, cron_expr, window_minutes, timezone, effective_from, effective_until, started_at, ended_at FROM maintenances ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListMaintenancesAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMaintenancesAll(ctx context.Context, arg ListMaintenancesAllParams) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, listMaintenancesAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Strategy,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CronExpr,
			&i.WindowMinutes,
			&i.Timezone,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenancesByStatus = `-- name: ListMaintenancesByStatus :many
SELECT id, created_at, updated_at, title, description, strategy, status, start_at, end_at, cron_expr, window_minutes, timezone, effective_from, effective_until, started_at, ended_at FROM maintenances WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListMaintenancesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListMaintenancesByStatus(ctx context.Context, arg ListMaintenancesByStatusParams) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, listMaintenancesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Strategy,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CronExpr,
			&i.WindowMinutes,
			&i.Timezone,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkMaintenanceResource = `-- name: UnlinkMaintenanceResource :exec
DELETE FROM maintenance_resources WHERE maintenance_id = $1 AND resource_id = $2
`

type UnlinkMaintenanceResourceParams struct {
	MaintenanceID string `json:"maintenance_id"`
	ResourceID    string `json:"resource_id"`
}

func (q *Queries) UnlinkMaintenanceResource(ctx context.Context, arg UnlinkMaintenanceResourceParams) error {
	_, err := q.db.Exec(ctx, unlinkMaintenanceResource, arg.MaintenanceID, arg.ResourceID)
	return err
}

const updateMaintenance = `-- name: UpdateMaintenance :exec
UPDATE maintenances
SET title = $2, description = $3, strategy = $4, status = $5,
    start_at = $6, end_at = $7, cron_expr = $8, window_minutes = $9, timezone = $10,
    effective_from = $11, effective_until = $12,
    started_at = $13, ended_at = $14, updated_at = $15
WHERE id = $1
`

type UpdateMaintenanceParams struct {
	ID             string             `json:"id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Strategy       string             `json:"strategy"`
	Status         string             `json:"status"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	EndAt          pgtype.Timestamptz `json:"end_at"`
	CronExpr       pgtype.Text        `json:"cron_expr"`
	WindowMinutes  pgtype.Int4        `json:"window_minutes"`
	Timezone       pgtype.Text        `json:"timezone"`
	EffectiveFrom  pgtype.Timestamptz `json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `json:"effective_until"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) error {
	_, err := q.db.Exec(ctx, updateMaintenance,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Strategy,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.CronExpr,
		arg.WindowMinutes,
		arg.Timezone,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.StartedAt,
		arg.EndedAt,
		arg.UpdatedAt,
	)
	return err
}
