// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitoring_activity.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const avgResponseTimeByResourceInWindow = `-- name: AvgResponseTimeByResourceInWindow :one
SELECT AVG(response_time)::float8 FROM monitoring_activities
WHERE resource_id = $1 AND created_at >= $2 AND success = true
`

type AvgResponseTimeByResourceInWindowParams struct {
	ResourceID string             `json:"resource_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AvgResponseTimeByResourceInWindow(ctx context.Context, arg AvgResponseTimeByResourceInWindowParams) (float64, error) {
	row := q.db.QueryRow(ctx, avgResponseTimeByResourceInWindow, arg.ResourceID, arg.CreatedAt)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMonitoringActivityByResourceSuccess = `-- name: CountMonitoringActivityByResourceSuccess :one
SELECT COUNT(*) FROM monitoring_activities
WHERE resource_id = $1 AND created_at >= $2 AND success = true
`

type CountMonitoringActivityByResourceSuccessParams struct {
	ResourceID string             `json:"resource_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountMonitoringActivityByResourceSuccess(ctx context.Context, arg CountMonitoringActivityByResourceSuccessParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMonitoringActivityByResourceSuccess, arg.ResourceID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonitoringActivityByResourceTotal = `-- name: CountMonitoringActivityByResourceTotal :one
SELECT COUNT(*) FROM monitoring_activities WHERE resource_id = $1 AND created_at >= $2
`

type CountMonitoringActivityByResourceTotalParams struct {
	ResourceID string             `json:"resource_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountMonitoringActivityByResourceTotal(ctx context.Context, arg CountMonitoringActivityByResourceTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMonitoringActivityByResourceTotal, arg.ResourceID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonitoringActivitySinceSuccess = `-- name: CountMonitoringActivitySinceSuccess :one
SELECT COUNT(*) FROM monitoring_activities WHERE created_at >= $1 AND success = true
`

func (q *Queries) CountMonitoringActivitySinceSuccess(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countMonitoringActivitySinceSuccess, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonitoringActivitySinceTotal = `-- name: CountMonitoringActivitySinceTotal :one
SELECT COUNT(*) FROM monitoring_activities WHERE created_at >= $1
`

func (q *Queries) CountMonitoringActivitySinceTotal(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countMonitoringActivitySinceTotal, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMonitoringActivity = `-- name: CreateMonitoringActivity :exec
INSERT INTO monitoring_activities (
    id, created_at, updated_at, resource_id, message, success,
    response_time, response_data, is_maintenance
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateMonitoringActivityParams struct {
	ID            string             `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ResourceID    string             `json:"resource_id"`
	Message       string             `json:"message"`
	Success       bool               `json:"success"`
	ResponseTime  int32              `json:"response_time"`
	ResponseData  []byte             `json:"response_data"`
	IsMaintenance bool               `json:"is_maintenance"`
}

func (q *Queries) CreateMonitoringActivity(ctx context.Context, arg CreateMonitoringActivityParams) error {
	_, err := q.db.Exec(ctx, createMonitoringActivity,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ResourceID,
		arg.Message,
		arg.Success,
		arg.ResponseTime,
		arg.ResponseData,
		arg.IsMaintenance,
	)
	return err
}

const findMonitoringActivitiesByResourceID = `-- name: FindMonitoringActivitiesByResourceID :many
SELECT id, created_at, updated_at, resource_id, message, success, response_time, response_data, is_maintenance FROM monitoring_activities
WHERE resource_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindMonitoringActivitiesByResourceIDParams struct {
	ResourceID string `json:"resource_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) FindMonitoringActivitiesByResourceID(ctx context.Context, arg FindMonitoringActivitiesByResourceIDParams) ([]MonitoringActivity, error) {
	rows, err := q.db.Query(ctx, findMonitoringActivitiesByResourceID, arg.ResourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringActivity{}
	for rows.Next() {
		var i MonitoringActivity
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceID,
			&i.Message,
			&i.Success,
			&i.ResponseTime,
			&i.ResponseData,
			&i.IsMaintenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentResponseTimes = `-- name: GetRecentResponseTimes :many
SELECT created_at, response_time FROM monitoring_activities
WHERE resource_id = $1 AND success = true
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentResponseTimesParams struct {
	ResourceID string `json:"resource_id"`
	Limit      int32  `json:"limit"`
}

type GetRecentResponseTimesRow struct {
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ResponseTime int32              `json:"response_time"`
}

func (q *Queries) GetRecentResponseTimes(ctx context.Context, arg GetRecentResponseTimesParams) ([]GetRecentResponseTimesRow, error) {
	rows, err := q.db.Query(ctx, getRecentResponseTimes, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentResponseTimesRow{}
	for rows.Next() {
		var i GetRecentResponseTimesRow
		if err := rows.Scan(&i.CreatedAt, &i.ResponseTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringActivities = `-- name: ListMonitoringActivities :many
SELECT id, created_at, updated_at, resource_id, message, success, response_time, response_data, is_maintenance FROM monitoring_activities
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMonitoringActivitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMonitoringActivities(ctx context.Context, arg ListMonitoringActivitiesParams) ([]MonitoringActivity, error) {
	rows, err := q.db.Query(ctx, listMonitoringActivities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringActivity{}
	for rows.Next() {
		var i MonitoringActivity
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceID,
			&i.Message,
			&i.Success,
			&i.ResponseTime,
			&i.ResponseData,
			&i.IsMaintenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMonitoringActivityHourlyAggregateInputs = `-- name: SelectMonitoringActivityHourlyAggregateInputs :many
SELECT created_at, success FROM monitoring_activities
WHERE resource_id = $1 AND created_at >= $2
ORDER BY created_at ASC
`

type SelectMonitoringActivityHourlyAggregateInputsParams struct {
	ResourceID string             `json:"resource_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SelectMonitoringActivityHourlyAggregateInputsRow struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Success   bool               `json:"success"`
}

func (q *Queries) SelectMonitoringActivityHourlyAggregateInputs(ctx context.Context, arg SelectMonitoringActivityHourlyAggregateInputsParams) ([]SelectMonitoringActivityHourlyAggregateInputsRow, error) {
	rows, err := q.db.Query(ctx, selectMonitoringActivityHourlyAggregateInputs, arg.ResourceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectMonitoringActivityHourlyAggregateInputsRow{}
	for rows.Next() {
		var i SelectMonitoringActivityHourlyAggregateInputsRow
		if err := rows.Scan(&i.CreatedAt, &i.Success); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMonitoringActivitySuccessInWindow = `-- name: SelectMonitoringActivitySuccessInWindow :many
SELECT success FROM monitoring_activities
WHERE resource_id = $1 AND created_at >= $2
ORDER BY created_at ASC
`

type SelectMonitoringActivitySuccessInWindowParams struct {
	ResourceID string             `json:"resource_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SelectMonitoringActivitySuccessInWindow(ctx context.Context, arg SelectMonitoringActivitySuccessInWindowParams) ([]bool, error) {
	rows, err := q.db.Query(ctx, selectMonitoringActivitySuccessInWindow, arg.ResourceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []bool{}
	for rows.Next() {
		var success bool
		if err := rows.Scan(&success); err != nil {
			return nil, err
		}
		items = append(items, success)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
