// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotificationEventForUpdate = `-- name: ClaimNotificationEventForUpdate :one
SELECT id FROM notification_events
WHERE id = $1
  AND status = 'pending'
  AND (claim_owner IS NULL OR claim_owner = '')
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimNotificationEventForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, claimNotificationEventForUpdate, id)
	err := row.Scan(&id)
	return id, err
}

const createNotificationEvent = `-- name: CreateNotificationEvent :exec
INSERT INTO notification_events (
    id, created_at, updated_at, incident_id, type,
    status, claim_owner, claimed_at, processed_at, last_error
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateNotificationEventParams struct {
	ID          string             `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IncidentID  string             `json:"incident_id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	ClaimOwner  pgtype.Text        `json:"claim_owner"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LastError   string             `json:"last_error"`
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) error {
	_, err := q.db.Exec(ctx, createNotificationEvent,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IncidentID,
		arg.Type,
		arg.Status,
		arg.ClaimOwner,
		arg.ClaimedAt,
		arg.ProcessedAt,
		arg.LastError,
	)
	return err
}

const deleteNotificationEvent = `-- name: DeleteNotificationEvent :exec
DELETE FROM notification_events WHERE id = $1
`

func (q *Queries) DeleteNotificationEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNotificationEvent, id)
	return err
}

const findNotificationEventByID = `-- name: FindNotificationEventByID :one
SELECT id, created_at, updated_at, incident_id, type, status, claim_owner, claimed_at, processed_at, last_error FROM notification_events WHERE id = $1
`

func (q *Queries) FindNotificationEventByID(ctx context.Context, id string) (NotificationEvent, error) {
	row := q.db.QueryRow(ctx, findNotificationEventByID, id)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IncidentID,
		&i.Type,
		&i.Status,
		&i.ClaimOwner,
		&i.ClaimedAt,
		&i.ProcessedAt,
		&i.LastError,
	)
	return i, err
}

const findPendingNotificationEvents = `-- name: FindPendingNotificationEvents :many
SELECT id, created_at, updated_at, incident_id, type, status, claim_owner, claimed_at, processed_at, last_error FROM notification_events
WHERE status = 'pending'
  AND type IN ('down', 'up')
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type FindPendingNotificationEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindPendingNotificationEvents(ctx context.Context, arg FindPendingNotificationEventsParams) ([]NotificationEvent, error) {
	rows, err := q.db.Query(ctx, findPendingNotificationEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IncidentID,
			&i.Type,
			&i.Status,
			&i.ClaimOwner,
			&i.ClaimedAt,
			&i.ProcessedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationEvents = `-- name: ListNotificationEvents :many
SELECT id, created_at, updated_at, incident_id, type, status, claim_owner, claimed_at, processed_at, last_error FROM notification_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNotificationEvents(ctx context.Context, arg ListNotificationEventsParams) ([]NotificationEvent, error) {
	rows, err := q.db.Query(ctx, listNotificationEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IncidentID,
			&i.Type,
			&i.Status,
			&i.ClaimOwner,
			&i.ClaimedAt,
			&i.ProcessedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationEventTerminal = `-- name: MarkNotificationEventTerminal :execrows
UPDATE notification_events
SET status = $2, processed_at = $3, last_error = $4,
    claim_owner = NULL, claimed_at = NULL
WHERE id = $1
`

type MarkNotificationEventTerminalParams struct {
	ID          string             `json:"id"`
	Status      string             `json:"status"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LastError   string             `json:"last_error"`
}

func (q *Queries) MarkNotificationEventTerminal(ctx context.Context, arg MarkNotificationEventTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationEventTerminal,
		arg.ID,
		arg.Status,
		arg.ProcessedAt,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNotificationEvent = `-- name: UpdateNotificationEvent :execrows
UPDATE notification_events
SET incident_id = $2, type = $3, status = $4,
    claim_owner = $5, claimed_at = $6, processed_at = $7, last_error = $8,
    updated_at = $9
WHERE id = $1
`

type UpdateNotificationEventParams struct {
	ID          string             `json:"id"`
	IncidentID  string             `json:"incident_id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	ClaimOwner  pgtype.Text        `json:"claim_owner"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LastError   string             `json:"last_error"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateNotificationEvent(ctx context.Context, arg UpdateNotificationEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotificationEvent,
		arg.ID,
		arg.IncidentID,
		arg.Type,
		arg.Status,
		arg.ClaimOwner,
		arg.ClaimedAt,
		arg.ProcessedAt,
		arg.LastError,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNotificationEventClaim = `-- name: UpdateNotificationEventClaim :exec
UPDATE notification_events
SET claim_owner = $2, claimed_at = $3
WHERE id = $1
`

type UpdateNotificationEventClaimParams struct {
	ID         string             `json:"id"`
	ClaimOwner pgtype.Text        `json:"claim_owner"`
	ClaimedAt  pgtype.Timestamptz `json:"claimed_at"`
}

func (q *Queries) UpdateNotificationEventClaim(ctx context.Context, arg UpdateNotificationEventClaimParams) error {
	_, err := q.db.Exec(ctx, updateNotificationEventClaim, arg.ID, arg.ClaimOwner, arg.ClaimedAt)
	return err
}
