// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_settings.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReportSettings = `-- name: GetReportSettings :one
SELECT id, enabled, recipient_email, schedule, scope, last_sent_at, created_at, updated_at
FROM report_settings
LIMIT 1
`

func (q *Queries) GetReportSettings(ctx context.Context) (ReportSetting, error) {
	row := q.db.QueryRow(ctx, getReportSettings)
	var i ReportSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.RecipientEmail,
		&i.Schedule,
		&i.Scope,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReportSettings = `-- name: UpsertReportSettings :one
INSERT INTO report_settings (id, enabled, recipient_email, schedule, scope, last_sent_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(id) DO UPDATE SET
    enabled = excluded.enabled,
    recipient_email = excluded.recipient_email,
    schedule = excluded.schedule,
    scope = excluded.scope,
    last_sent_at = excluded.last_sent_at,
    updated_at = excluded.updated_at
RETURNING id, enabled, recipient_email, schedule, scope, last_sent_at, created_at, updated_at
`

type UpsertReportSettingsParams struct {
	ID             string             `json:"id"`
	Enabled        bool               `json:"enabled"`
	RecipientEmail string             `json:"recipient_email"`
	Schedule       string             `json:"schedule"`
	Scope          string             `json:"scope"`
	LastSentAt     pgtype.Timestamptz `json:"last_sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertReportSettings(ctx context.Context, arg UpsertReportSettingsParams) (ReportSetting, error) {
	row := q.db.QueryRow(ctx, upsertReportSettings,
		arg.ID,
		arg.Enabled,
		arg.RecipientEmail,
		arg.Schedule,
		arg.Scope,
		arg.LastSentAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ReportSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.RecipientEmail,
		&i.Schedule,
		&i.Scope,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
