// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_history.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReportHistory = `-- name: CreateReportHistory :one
INSERT INTO report_history (id, period, sent_at, status, uptime_pct, incident_count, downtime_seconds, recipient_email, resource_breakdown, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, period, sent_at, status, uptime_pct, incident_count, downtime_seconds, recipient_email, resource_breakdown, created_at
`

type CreateReportHistoryParams struct {
	ID                string             `json:"id"`
	Period            string             `json:"period"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	Status            string             `json:"status"`
	UptimePct         float64            `json:"uptime_pct"`
	IncidentCount     int32              `json:"incident_count"`
	DowntimeSeconds   int64              `json:"downtime_seconds"`
	RecipientEmail    string             `json:"recipient_email"`
	ResourceBreakdown []byte             `json:"resource_breakdown"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReportHistory(ctx context.Context, arg CreateReportHistoryParams) (ReportHistory, error) {
	row := q.db.QueryRow(ctx, createReportHistory,
		arg.ID,
		arg.Period,
		arg.SentAt,
		arg.Status,
		arg.UptimePct,
		arg.IncidentCount,
		arg.DowntimeSeconds,
		arg.RecipientEmail,
		arg.ResourceBreakdown,
		arg.CreatedAt,
	)
	var i ReportHistory
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.SentAt,
		&i.Status,
		&i.UptimePct,
		&i.IncidentCount,
		&i.DowntimeSeconds,
		&i.RecipientEmail,
		&i.ResourceBreakdown,
		&i.CreatedAt,
	)
	return i, err
}

const findReportHistoryByPeriod = `-- name: FindReportHistoryByPeriod :one
SELECT id, period, sent_at, status, uptime_pct, incident_count, downtime_seconds, recipient_email, resource_breakdown, created_at
FROM report_history
WHERE period = $1
`

func (q *Queries) FindReportHistoryByPeriod(ctx context.Context, period string) (ReportHistory, error) {
	row := q.db.QueryRow(ctx, findReportHistoryByPeriod, period)
	var i ReportHistory
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.SentAt,
		&i.Status,
		&i.UptimePct,
		&i.IncidentCount,
		&i.DowntimeSeconds,
		&i.RecipientEmail,
		&i.ResourceBreakdown,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentReportHistory = `-- name: ListRecentReportHistory :many
SELECT id, period, sent_at, status, uptime_pct, incident_count, downtime_seconds, recipient_email, resource_breakdown, created_at
FROM report_history
ORDER BY sent_at DESC
LIMIT $1
`

func (q *Queries) ListRecentReportHistory(ctx context.Context, lim int32) ([]ReportHistory, error) {
	rows, err := q.db.Query(ctx, listRecentReportHistory, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportHistory{}
	for rows.Next() {
		var i ReportHistory
		if err := rows.Scan(
			&i.ID,
			&i.Period,
			&i.SentAt,
			&i.Status,
			&i.UptimePct,
			&i.IncidentCount,
			&i.DowntimeSeconds,
			&i.RecipientEmail,
			&i.ResourceBreakdown,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
