// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_health.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteResourceHealth = `-- name: DeleteResourceHealth :exec
DELETE FROM resource_health WHERE resource_id = $1
`

// Called when a check collects nothing at all, so the interface shows no figures
// rather than yesterday's.
func (q *Queries) DeleteResourceHealth(ctx context.Context, resourceID string) error {
	_, err := q.db.Exec(ctx, deleteResourceHealth, resourceID)
	return err
}

const findResourceHealth = `-- name: FindResourceHealth :one
SELECT resource_id, collected_at, connections_active, connections_max, longest_query_seconds, replication_lag_seconds, privilege_limited, unsupported_version FROM resource_health WHERE resource_id = $1
`

func (q *Queries) FindResourceHealth(ctx context.Context, resourceID string) (ResourceHealth, error) {
	row := q.db.QueryRow(ctx, findResourceHealth, resourceID)
	var i ResourceHealth
	err := row.Scan(
		&i.ResourceID,
		&i.CollectedAt,
		&i.ConnectionsActive,
		&i.ConnectionsMax,
		&i.LongestQuerySeconds,
		&i.ReplicationLagSeconds,
		&i.PrivilegeLimited,
		&i.UnsupportedVersion,
	)
	return i, err
}

const upsertResourceHealth = `-- name: UpsertResourceHealth :exec
INSERT INTO resource_health (
    resource_id, collected_at, connections_active, connections_max,
    longest_query_seconds, replication_lag_seconds, privilege_limited, unsupported_version
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (resource_id) DO UPDATE SET
    collected_at            = EXCLUDED.collected_at,
    connections_active      = EXCLUDED.connections_active,
    connections_max         = EXCLUDED.connections_max,
    longest_query_seconds   = EXCLUDED.longest_query_seconds,
    replication_lag_seconds = EXCLUDED.replication_lag_seconds,
    privilege_limited       = EXCLUDED.privilege_limited,
    unsupported_version     = EXCLUDED.unsupported_version
`

type UpsertResourceHealthParams struct {
	ResourceID            string             `json:"resource_id"`
	CollectedAt           pgtype.Timestamptz `json:"collected_at"`
	ConnectionsActive     pgtype.Int8        `json:"connections_active"`
	ConnectionsMax        pgtype.Int8        `json:"connections_max"`
	LongestQuerySeconds   pgtype.Float8      `json:"longest_query_seconds"`
	ReplicationLagSeconds pgtype.Float8      `json:"replication_lag_seconds"`
	PrivilegeLimited      bool               `json:"privilege_limited"`
	UnsupportedVersion    bool               `json:"unsupported_version"`
}

// At most one row per monitor: replace rather than accumulate. This is what makes
// storage constant per monitor and removes any need for a retention job.
func (q *Queries) UpsertResourceHealth(ctx context.Context, arg UpsertResourceHealthParams) error {
	_, err := q.db.Exec(ctx, upsertResourceHealth,
		arg.ResourceID,
		arg.CollectedAt,
		arg.ConnectionsActive,
		arg.ConnectionsMax,
		arg.LongestQuerySeconds,
		arg.ReplicationLagSeconds,
		arg.PrivilegeLimited,
		arg.UnsupportedVersion,
	)
	return err
}
