// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countResourcesByComponentID = `-- name: CountResourcesByComponentID :one
SELECT COUNT(*) FROM resources
WHERE component_id = $1 AND is_active = TRUE
`

func (q *Queries) CountResourcesByComponentID(ctx context.Context, componentID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesByComponentID, componentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :exec

INSERT INTO resources (
    id, created_at, updated_at, name, type, interval, timeout, target,
    last_checked, status, is_active, failure_count,
    ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar,
    component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds,
    flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes,
    last_status_transition, flap_started_at, reminder_interval_minutes,
    heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at,
    keyword, keyword_mode, protocol_type, protocol_port
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19, $20,
    $21, $22, $23, $24,
    $25, $26, $27,
    $28, $29, $30, $31,
    $32, $33, $34, $35
)
`

type CreateResourceParams struct {
	ID                      string             `json:"id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Name                    string             `json:"name"`
	Type                    string             `json:"type"`
	Interval                int32              `json:"interval"`
	Timeout                 int32              `json:"timeout"`
	Target                  string             `json:"target"`
	LastChecked             pgtype.Timestamptz `json:"last_checked"`
	Status                  string             `json:"status"`
	IsActive                bool               `json:"is_active"`
	FailureCount            int32              `json:"failure_count"`
	SslExpirationDate       pgtype.Timestamptz `json:"ssl_expiration_date"`
	SslIssuer               pgtype.Text        `json:"ssl_issuer"`
	DomainExpirationDate    pgtype.Timestamptz `json:"domain_expiration_date"`
	DomainRegistrar         pgtype.Text        `json:"domain_registrar"`
	ComponentID             pgtype.Text        `json:"component_id"`
	ConfirmationChecks      int32              `json:"confirmation_checks"`
	ConfirmationInterval    int32              `json:"confirmation_interval"`
	ExpiryAlertThresholds   pgtype.Text        `json:"expiry_alert_thresholds"`
	FlapDetectionEnabled    bool               `json:"flap_detection_enabled"`
	FlapThreshold           int32              `json:"flap_threshold"`
	FlapWindowSeconds       int32              `json:"flap_window_seconds"`
	FlapMaxDurationMinutes  int32              `json:"flap_max_duration_minutes"`
	LastStatusTransition    pgtype.Timestamptz `json:"last_status_transition"`
	FlapStartedAt           pgtype.Timestamptz `json:"flap_started_at"`
	ReminderIntervalMinutes int32              `json:"reminder_interval_minutes"`
	HeartbeatSlug           pgtype.Text        `json:"heartbeat_slug"`
	HeartbeatInterval       pgtype.Int4        `json:"heartbeat_interval"`
	HeartbeatGrace          pgtype.Int4        `json:"heartbeat_grace"`
	LastPingAt              pgtype.Timestamp   `json:"last_ping_at"`
	Keyword                 pgtype.Text        `json:"keyword"`
	KeywordMode             pgtype.Text        `json:"keyword_mode"`
	ProtocolType            pgtype.Text        `json:"protocol_type"`
	ProtocolPort            pgtype.Int4        `json:"protocol_port"`
}

// PR1 of US1: CRUD without M2M and without 1-to-1 preloads.
// Deferred to later PRs: FindByTag (M2M JOIN), dynamic UpdateMonitoringState /
// UpdateMetadata, Tags / NotificationChannels / Component / Credential preloads.
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) error {
	_, err := q.db.Exec(ctx, createResource,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Type,
		arg.Interval,
		arg.Timeout,
		arg.Target,
		arg.LastChecked,
		arg.Status,
		arg.IsActive,
		arg.FailureCount,
		arg.SslExpirationDate,
		arg.SslIssuer,
		arg.DomainExpirationDate,
		arg.DomainRegistrar,
		arg.ComponentID,
		arg.ConfirmationChecks,
		arg.ConfirmationInterval,
		arg.ExpiryAlertThresholds,
		arg.FlapDetectionEnabled,
		arg.FlapThreshold,
		arg.FlapWindowSeconds,
		arg.FlapMaxDurationMinutes,
		arg.LastStatusTransition,
		arg.FlapStartedAt,
		arg.ReminderIntervalMinutes,
		arg.HeartbeatSlug,
		arg.HeartbeatInterval,
		arg.HeartbeatGrace,
		arg.LastPingAt,
		arg.Keyword,
		arg.KeywordMode,
		arg.ProtocolType,
		arg.ProtocolPort,
	)
	return err
}

const findMissedHeartbeatsPG = `-- name: FindMissedHeartbeatsPG :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port FROM resources
WHERE type = 'heartbeat'
  AND status = 'up'
  AND is_active = TRUE
  AND last_ping_at IS NOT NULL
  AND EXTRACT(EPOCH FROM last_ping_at) + heartbeat_interval + heartbeat_grace < $1::double precision
ORDER BY last_ping_at ASC
LIMIT $2::int
`

type FindMissedHeartbeatsPGParams struct {
	NowUnix  float64 `json:"now_unix"`
	RowLimit int32   `json:"row_limit"`
}

func (q *Queries) FindMissedHeartbeatsPG(ctx context.Context, arg FindMissedHeartbeatsPGParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, findMissedHeartbeatsPG, arg.NowUnix, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResourceByHeartbeatSlug = `-- name: FindResourceByHeartbeatSlug :one
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port FROM resources
WHERE heartbeat_slug = $1
  AND type = 'heartbeat'
  AND is_active = TRUE
`

func (q *Queries) FindResourceByHeartbeatSlug(ctx context.Context, heartbeatSlug pgtype.Text) (Resource, error) {
	row := q.db.QueryRow(ctx, findResourceByHeartbeatSlug, heartbeatSlug)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Type,
		&i.Interval,
		&i.Timeout,
		&i.Target,
		&i.LastChecked,
		&i.Status,
		&i.IsActive,
		&i.FailureCount,
		&i.SslExpirationDate,
		&i.SslIssuer,
		&i.DomainExpirationDate,
		&i.DomainRegistrar,
		&i.ComponentID,
		&i.ConfirmationChecks,
		&i.ConfirmationInterval,
		&i.ExpiryAlertThresholds,
		&i.FlapDetectionEnabled,
		&i.FlapThreshold,
		&i.FlapWindowSeconds,
		&i.FlapMaxDurationMinutes,
		&i.LastStatusTransition,
		&i.FlapStartedAt,
		&i.ReminderIntervalMinutes,
		&i.HeartbeatSlug,
		&i.HeartbeatInterval,
		&i.HeartbeatGrace,
		&i.LastPingAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.ProtocolType,
		&i.ProtocolPort,
	)
	return i, err
}

const findResourceByID = `-- name: FindResourceByID :one
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port FROM resources WHERE id = $1 AND is_active = TRUE
`

func (q *Queries) FindResourceByID(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRow(ctx, findResourceByID, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Type,
		&i.Interval,
		&i.Timeout,
		&i.Target,
		&i.LastChecked,
		&i.Status,
		&i.IsActive,
		&i.FailureCount,
		&i.SslExpirationDate,
		&i.SslIssuer,
		&i.DomainExpirationDate,
		&i.DomainRegistrar,
		&i.ComponentID,
		&i.ConfirmationChecks,
		&i.ConfirmationInterval,
		&i.ExpiryAlertThresholds,
		&i.FlapDetectionEnabled,
		&i.FlapThreshold,
		&i.FlapWindowSeconds,
		&i.FlapMaxDurationMinutes,
		&i.LastStatusTransition,
		&i.FlapStartedAt,
		&i.ReminderIntervalMinutes,
		&i.HeartbeatSlug,
		&i.HeartbeatInterval,
		&i.HeartbeatGrace,
		&i.LastPingAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.ProtocolType,
		&i.ProtocolPort,
	)
	return i, err
}

const findResourceIDsByTagName = `-- name: FindResourceIDsByTagName :many
SELECT r.id
FROM resources r
JOIN resource_tags rt ON r.id = rt.resource_id
JOIN tags t ON rt.tag_id = t.id
WHERE t.name = $1 AND r.is_active = TRUE
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type FindResourceIDsByTagNameParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) FindResourceIDsByTagName(ctx context.Context, arg FindResourceIDsByTagNameParams) ([]string, error) {
	rows, err := q.db.Query(ctx, findResourceIDsByTagName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResourcesByComponentID = `-- name: FindResourcesByComponentID :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port FROM resources
WHERE component_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) FindResourcesByComponentID(ctx context.Context, componentID pgtype.Text) ([]Resource, error) {
	rows, err := q.db.Query(ctx, findResourcesByComponentID, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResourcesByIDs = `-- name: FindResourcesByIDs :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port FROM resources WHERE id = ANY($1::text[])
`

func (q *Queries) FindResourcesByIDs(ctx context.Context, dollar_1 []string) ([]Resource, error) {
	rows, err := q.db.Query(ctx, findResourcesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkResourceTag = `-- name: LinkResourceTag :exec

INSERT INTO resource_tags (resource_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkResourceTagParams struct {
	ResourceID string `json:"resource_id"`
	TagID      string `json:"tag_id"`
}

// M2M: resource_tags ---------------------------------------------------------
func (q *Queries) LinkResourceTag(ctx context.Context, arg LinkResourceTagParams) error {
	_, err := q.db.Exec(ctx, linkResourceTag, arg.ResourceID, arg.TagID)
	return err
}

const listActiveResources = `-- name: ListActiveResources :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port FROM resources
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveResourcesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveResources(ctx context.Context, arg ListActiveResourcesParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listActiveResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port FROM resources
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListResourcesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledResources = `-- name: ListScheduledResources :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port FROM resources
WHERE is_active = TRUE
ORDER BY id ASC
`

func (q *Queries) ListScheduledResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listScheduledResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagIDsByResourceID = `-- name: ListTagIDsByResourceID :many
SELECT tag_id FROM resource_tags WHERE resource_id = $1
`

func (q *Queries) ListTagIDsByResourceID(ctx context.Context, resourceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTagIDsByResourceID, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByResourceIDs = `-- name: ListTagsByResourceIDs :many
SELECT rt.resource_id, t.id, t.name, t.color, t.description, t.created_at, t.updated_at
FROM resource_tags rt
JOIN tags t ON rt.tag_id = t.id
WHERE rt.resource_id = ANY($1::text[])
`

type ListTagsByResourceIDsRow struct {
	ResourceID  string             `json:"resource_id"`
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Color       pgtype.Text        `json:"color"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTagsByResourceIDs(ctx context.Context, dollar_1 []string) ([]ListTagsByResourceIDsRow, error) {
	rows, err := q.db.Query(ctx, listTagsByResourceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsByResourceIDsRow{}
	for rows.Next() {
		var i ListTagsByResourceIDsRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteResource = `-- name: SoftDeleteResource :execrows
UPDATE resources SET is_active = FALSE
WHERE id = $1 AND is_active = TRUE
`

func (q *Queries) SoftDeleteResource(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteResource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkResourceTag = `-- name: UnlinkResourceTag :exec
DELETE FROM resource_tags WHERE resource_id = $1 AND tag_id = $2
`

type UnlinkResourceTagParams struct {
	ResourceID string `json:"resource_id"`
	TagID      string `json:"tag_id"`
}

func (q *Queries) UnlinkResourceTag(ctx context.Context, arg UnlinkResourceTagParams) error {
	_, err := q.db.Exec(ctx, unlinkResourceTag, arg.ResourceID, arg.TagID)
	return err
}

const updateResourceLastPingAt = `-- name: UpdateResourceLastPingAt :execrows
UPDATE resources SET last_ping_at = $2
WHERE id = $1 AND type = 'heartbeat' AND is_active = TRUE
`

type UpdateResourceLastPingAtParams struct {
	ID         string           `json:"id"`
	LastPingAt pgtype.Timestamp `json:"last_ping_at"`
}

func (q *Queries) UpdateResourceLastPingAt(ctx context.Context, arg UpdateResourceLastPingAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateResourceLastPingAt, arg.ID, arg.LastPingAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateResourceMain = `-- name: UpdateResourceMain :execrows
UPDATE resources
SET name                      = $2,
    type                      = $3,
    target                    = $4,
    interval                  = $5,
    timeout                   = $6,
    is_active                 = $7,
    confirmation_checks       = $8,
    confirmation_interval     = $9,
    component_id              = $10,
    expiry_alert_thresholds   = $11,
    flap_detection_enabled    = $12,
    flap_threshold            = $13,
    flap_window_seconds       = $14,
    flap_max_duration_minutes = $15,
    reminder_interval_minutes = $16,
    heartbeat_interval        = $17,
    heartbeat_grace           = $18,
    updated_at                = $19
WHERE id = $1
`

type UpdateResourceMainParams struct {
	ID                      string             `json:"id"`
	Name                    string             `json:"name"`
	Type                    string             `json:"type"`
	Target                  string             `json:"target"`
	Interval                int32              `json:"interval"`
	Timeout                 int32              `json:"timeout"`
	IsActive                bool               `json:"is_active"`
	ConfirmationChecks      int32              `json:"confirmation_checks"`
	ConfirmationInterval    int32              `json:"confirmation_interval"`
	ComponentID             pgtype.Text        `json:"component_id"`
	ExpiryAlertThresholds   pgtype.Text        `json:"expiry_alert_thresholds"`
	FlapDetectionEnabled    bool               `json:"flap_detection_enabled"`
	FlapThreshold           int32              `json:"flap_threshold"`
	FlapWindowSeconds       int32              `json:"flap_window_seconds"`
	FlapMaxDurationMinutes  int32              `json:"flap_max_duration_minutes"`
	ReminderIntervalMinutes int32              `json:"reminder_interval_minutes"`
	HeartbeatInterval       pgtype.Int4        `json:"heartbeat_interval"`
	HeartbeatGrace          pgtype.Int4        `json:"heartbeat_grace"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateResourceMain(ctx context.Context, arg UpdateResourceMainParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateResourceMain,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Target,
		arg.Interval,
		arg.Timeout,
		arg.IsActive,
		arg.ConfirmationChecks,
		arg.ConfirmationInterval,
		arg.ComponentID,
		arg.ExpiryAlertThresholds,
		arg.FlapDetectionEnabled,
		arg.FlapThreshold,
		arg.FlapWindowSeconds,
		arg.FlapMaxDurationMinutes,
		arg.ReminderIntervalMinutes,
		arg.HeartbeatInterval,
		arg.HeartbeatGrace,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateResourceStatus = `-- name: UpdateResourceStatus :execrows
UPDATE resources SET status = $2 WHERE id = $1
`

type UpdateResourceStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateResourceStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
