// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, browser, os, ip, location, last_active_at, created_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, browser, os, ip, location, last_active_at, created_at, revoked_at
`

type CreateSessionParams struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Browser      string             `json:"browser"`
	Os           string             `json:"os"`
	Ip           string             `json:"ip"`
	Location     pgtype.Text        `json:"location"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Browser,
		arg.Os,
		arg.Ip,
		arg.Location,
		arg.LastActiveAt,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Browser,
		&i.Os,
		&i.Ip,
		&i.Location,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findSessionByID = `-- name: FindSessionByID :one
SELECT id, user_id, browser, os, ip, location, last_active_at, created_at, revoked_at FROM sessions WHERE id = $1
`

func (q *Queries) FindSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Browser,
		&i.Os,
		&i.Ip,
		&i.Location,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, browser, os, ip, location, last_active_at, created_at, revoked_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_active_at DESC
`

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Browser,
			&i.Os,
			&i.Ip,
			&i.Location,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsExcept = `-- name: RevokeAllSessionsExcept :execrows
UPDATE sessions
SET revoked_at = $3
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeAllSessionsExceptParams struct {
	UserID    string             `json:"user_id"`
	ID        string             `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAllSessionsExcept(ctx context.Context, arg RevokeAllSessionsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessionsExcept, arg.UserID, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        string             `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionLastActive = `-- name: UpdateSessionLastActive :exec
UPDATE sessions
SET last_active_at = $2
WHERE id = $1
`

type UpdateSessionLastActiveParams struct {
	ID           string             `json:"id"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error {
	_, err := q.db.Exec(ctx, updateSessionLastActive, arg.ID, arg.LastActiveAt)
	return err
}
