// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuspage_settings.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStatusPageSettings = `-- name: CreateStatusPageSettings :exec
INSERT INTO status_page_settings (
    id, name, homepage_url, custom_domain, google_analytics_id,
    enable_details_page, show_uptime_percentage, hide_paused_monitors,
    show_incident_history, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateStatusPageSettingsParams struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	HomepageUrl          string             `json:"homepage_url"`
	CustomDomain         string             `json:"custom_domain"`
	GoogleAnalyticsID    string             `json:"google_analytics_id"`
	EnableDetailsPage    bool               `json:"enable_details_page"`
	ShowUptimePercentage bool               `json:"show_uptime_percentage"`
	HidePausedMonitors   bool               `json:"hide_paused_monitors"`
	ShowIncidentHistory  bool               `json:"show_incident_history"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStatusPageSettings(ctx context.Context, arg CreateStatusPageSettingsParams) error {
	_, err := q.db.Exec(ctx, createStatusPageSettings,
		arg.ID,
		arg.Name,
		arg.HomepageUrl,
		arg.CustomDomain,
		arg.GoogleAnalyticsID,
		arg.EnableDetailsPage,
		arg.ShowUptimePercentage,
		arg.HidePausedMonitors,
		arg.ShowIncidentHistory,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getStatusPageSettings = `-- name: GetStatusPageSettings :one
SELECT id, created_at, updated_at, name, homepage_url, custom_domain, google_analytics_id, enable_details_page, show_uptime_percentage, hide_paused_monitors, show_incident_history FROM status_page_settings LIMIT 1
`

func (q *Queries) GetStatusPageSettings(ctx context.Context) (StatusPageSetting, error) {
	row := q.db.QueryRow(ctx, getStatusPageSettings)
	var i StatusPageSetting
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.HomepageUrl,
		&i.CustomDomain,
		&i.GoogleAnalyticsID,
		&i.EnableDetailsPage,
		&i.ShowUptimePercentage,
		&i.HidePausedMonitors,
		&i.ShowIncidentHistory,
	)
	return i, err
}

const updateStatusPageSettings = `-- name: UpdateStatusPageSettings :exec
UPDATE status_page_settings
SET name = $2,
    homepage_url = $3,
    custom_domain = $4,
    google_analytics_id = $5,
    enable_details_page = $6,
    show_uptime_percentage = $7,
    hide_paused_monitors = $8,
    show_incident_history = $9,
    updated_at = $10
WHERE id = $1
`

type UpdateStatusPageSettingsParams struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	HomepageUrl          string             `json:"homepage_url"`
	CustomDomain         string             `json:"custom_domain"`
	GoogleAnalyticsID    string             `json:"google_analytics_id"`
	EnableDetailsPage    bool               `json:"enable_details_page"`
	ShowUptimePercentage bool               `json:"show_uptime_percentage"`
	HidePausedMonitors   bool               `json:"hide_paused_monitors"`
	ShowIncidentHistory  bool               `json:"show_incident_history"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateStatusPageSettings(ctx context.Context, arg UpdateStatusPageSettingsParams) error {
	_, err := q.db.Exec(ctx, updateStatusPageSettings,
		arg.ID,
		arg.Name,
		arg.HomepageUrl,
		arg.CustomDomain,
		arg.GoogleAnalyticsID,
		arg.EnableDetailsPage,
		arg.ShowUptimePercentage,
		arg.HidePausedMonitors,
		arg.ShowIncidentHistory,
		arg.UpdatedAt,
	)
	return err
}
