// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statuspage_settings.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStatusPageSettings = `-- name: CreateStatusPageSettings :exec
INSERT INTO status_page_settings (
    id, name, homepage_url, custom_domain, google_analytics_id,
    enable_details_page, show_uptime_percentage, hide_paused_monitors,
    show_incident_history,
    custom_domain_status, custom_domain_ssl_status, custom_domain_dns_records,
    logo_url_light, logo_url_dark, favicon_url, primary_color, theme_overrides,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
`

type CreateStatusPageSettingsParams struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	HomepageUrl            string             `json:"homepage_url"`
	CustomDomain           string             `json:"custom_domain"`
	GoogleAnalyticsID      string             `json:"google_analytics_id"`
	EnableDetailsPage      bool               `json:"enable_details_page"`
	ShowUptimePercentage   bool               `json:"show_uptime_percentage"`
	HidePausedMonitors     bool               `json:"hide_paused_monitors"`
	ShowIncidentHistory    bool               `json:"show_incident_history"`
	CustomDomainStatus     string             `json:"custom_domain_status"`
	CustomDomainSslStatus  string             `json:"custom_domain_ssl_status"`
	CustomDomainDnsRecords []byte             `json:"custom_domain_dns_records"`
	LogoUrlLight           string             `json:"logo_url_light"`
	LogoUrlDark            string             `json:"logo_url_dark"`
	FaviconUrl             string             `json:"favicon_url"`
	PrimaryColor           string             `json:"primary_color"`
	ThemeOverrides         []byte             `json:"theme_overrides"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStatusPageSettings(ctx context.Context, arg CreateStatusPageSettingsParams) error {
	_, err := q.db.Exec(ctx, createStatusPageSettings,
		arg.ID,
		arg.Name,
		arg.HomepageUrl,
		arg.CustomDomain,
		arg.GoogleAnalyticsID,
		arg.EnableDetailsPage,
		arg.ShowUptimePercentage,
		arg.HidePausedMonitors,
		arg.ShowIncidentHistory,
		arg.CustomDomainStatus,
		arg.CustomDomainSslStatus,
		arg.CustomDomainDnsRecords,
		arg.LogoUrlLight,
		arg.LogoUrlDark,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.ThemeOverrides,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getStatusPageSettings = `-- name: GetStatusPageSettings :one
SELECT id, created_at, updated_at, name, homepage_url, custom_domain, google_analytics_id, enable_details_page, show_uptime_percentage, hide_paused_monitors, show_incident_history, custom_domain_status, custom_domain_ssl_status, custom_domain_dns_records, logo_url_light, logo_url_dark, favicon_url, primary_color, theme_overrides FROM status_page_settings LIMIT 1
`

func (q *Queries) GetStatusPageSettings(ctx context.Context) (StatusPageSetting, error) {
	row := q.db.QueryRow(ctx, getStatusPageSettings)
	var i StatusPageSetting
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.HomepageUrl,
		&i.CustomDomain,
		&i.GoogleAnalyticsID,
		&i.EnableDetailsPage,
		&i.ShowUptimePercentage,
		&i.HidePausedMonitors,
		&i.ShowIncidentHistory,
		&i.CustomDomainStatus,
		&i.CustomDomainSslStatus,
		&i.CustomDomainDnsRecords,
		&i.LogoUrlLight,
		&i.LogoUrlDark,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.ThemeOverrides,
	)
	return i, err
}

const updateStatusPageSettings = `-- name: UpdateStatusPageSettings :exec
UPDATE status_page_settings
SET name = $2,
    homepage_url = $3,
    custom_domain = $4,
    google_analytics_id = $5,
    enable_details_page = $6,
    show_uptime_percentage = $7,
    hide_paused_monitors = $8,
    show_incident_history = $9,
    custom_domain_status = $10,
    custom_domain_ssl_status = $11,
    custom_domain_dns_records = $12,
    logo_url_light = $13,
    logo_url_dark = $14,
    favicon_url = $15,
    primary_color = $16,
    theme_overrides = $17,
    updated_at = $18
WHERE id = $1
`

type UpdateStatusPageSettingsParams struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	HomepageUrl            string             `json:"homepage_url"`
	CustomDomain           string             `json:"custom_domain"`
	GoogleAnalyticsID      string             `json:"google_analytics_id"`
	EnableDetailsPage      bool               `json:"enable_details_page"`
	ShowUptimePercentage   bool               `json:"show_uptime_percentage"`
	HidePausedMonitors     bool               `json:"hide_paused_monitors"`
	ShowIncidentHistory    bool               `json:"show_incident_history"`
	CustomDomainStatus     string             `json:"custom_domain_status"`
	CustomDomainSslStatus  string             `json:"custom_domain_ssl_status"`
	CustomDomainDnsRecords []byte             `json:"custom_domain_dns_records"`
	LogoUrlLight           string             `json:"logo_url_light"`
	LogoUrlDark            string             `json:"logo_url_dark"`
	FaviconUrl             string             `json:"favicon_url"`
	PrimaryColor           string             `json:"primary_color"`
	ThemeOverrides         []byte             `json:"theme_overrides"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateStatusPageSettings(ctx context.Context, arg UpdateStatusPageSettingsParams) error {
	_, err := q.db.Exec(ctx, updateStatusPageSettings,
		arg.ID,
		arg.Name,
		arg.HomepageUrl,
		arg.CustomDomain,
		arg.GoogleAnalyticsID,
		arg.EnableDetailsPage,
		arg.ShowUptimePercentage,
		arg.HidePausedMonitors,
		arg.ShowIncidentHistory,
		arg.CustomDomainStatus,
		arg.CustomDomainSslStatus,
		arg.CustomDomainDnsRecords,
		arg.LogoUrlLight,
		arg.LogoUrlDark,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.ThemeOverrides,
		arg.UpdatedAt,
	)
	return err
}
