// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, created_at, updated_at, name, color, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, name, color, description
`

type CreateTagParams struct {
	ID          string             `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Name        string             `json:"name"`
	Color       pgtype.Text        `json:"color"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Color,
		arg.Description,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Color,
		&i.Description,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTagByID = `-- name: FindTagByID :one
SELECT id, created_at, updated_at, name, color, description FROM tags WHERE id = $1
`

func (q *Queries) FindTagByID(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRow(ctx, findTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Color,
		&i.Description,
	)
	return i, err
}

const findTagByName = `-- name: FindTagByName :one
SELECT id, created_at, updated_at, name, color, description FROM tags WHERE name = $1
`

func (q *Queries) FindTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, findTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Color,
		&i.Description,
	)
	return i, err
}

const findTagsByIDs = `-- name: FindTagsByIDs :many
SELECT id, created_at, updated_at, name, color, description FROM tags WHERE id = ANY($1::text[])
`

func (q *Queries) FindTagsByIDs(ctx context.Context, dollar_1 []string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, findTagsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Color,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, created_at, updated_at, name, color, description FROM tags
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTagsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Color,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :execrows
UPDATE tags
SET name = $2, color = $3, description = $4, updated_at = $5
WHERE id = $1
`

type UpdateTagParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Color       pgtype.Text        `json:"color"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTag,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
