// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: two_factor_reset_token.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentTwoFactorResetTokensByUser = `-- name: CountRecentTwoFactorResetTokensByUser :one
SELECT COUNT(*)::bigint FROM two_factor_reset_tokens
WHERE user_id = $1 AND created_at > $2
`

type CountRecentTwoFactorResetTokensByUserParams struct {
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountRecentTwoFactorResetTokensByUser(ctx context.Context, arg CountRecentTwoFactorResetTokensByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentTwoFactorResetTokensByUser, arg.UserID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTwoFactorResetToken = `-- name: CreateTwoFactorResetToken :exec
INSERT INTO two_factor_reset_tokens (token_hash, user_id, expires_at, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateTwoFactorResetTokenParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTwoFactorResetToken(ctx context.Context, arg CreateTwoFactorResetTokenParams) error {
	_, err := q.db.Exec(ctx, createTwoFactorResetToken,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredTwoFactorResetTokens = `-- name: DeleteExpiredTwoFactorResetTokens :exec
DELETE FROM two_factor_reset_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredTwoFactorResetTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredTwoFactorResetTokens, expiresAt)
	return err
}

const findActiveTwoFactorResetToken = `-- name: FindActiveTwoFactorResetToken :one
SELECT token_hash, user_id, expires_at, used_at, created_at FROM two_factor_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > $2
`

type FindActiveTwoFactorResetTokenParams struct {
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) FindActiveTwoFactorResetToken(ctx context.Context, arg FindActiveTwoFactorResetTokenParams) (TwoFactorResetToken, error) {
	row := q.db.QueryRow(ctx, findActiveTwoFactorResetToken, arg.TokenHash, arg.ExpiresAt)
	var i TwoFactorResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTwoFactorResetTokenUsed = `-- name: MarkTwoFactorResetTokenUsed :execrows
UPDATE two_factor_reset_tokens
SET used_at = $2
WHERE token_hash = $1 AND used_at IS NULL
`

type MarkTwoFactorResetTokenUsedParams struct {
	TokenHash string             `json:"token_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) MarkTwoFactorResetTokenUsed(ctx context.Context, arg MarkTwoFactorResetTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTwoFactorResetTokenUsed, arg.TokenHash, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
