// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uptime_daily_agg.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findEarliestUptimeDailyAggDay = `-- name: FindEarliestUptimeDailyAggDay :one
SELECT MIN(day) AS earliest FROM uptime_daily_agg
`

func (q *Queries) FindEarliestUptimeDailyAggDay(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, findEarliestUptimeDailyAggDay)
	var earliest interface{}
	err := row.Scan(&earliest)
	return earliest, err
}

const findUptimeDailyAggForResource = `-- name: FindUptimeDailyAggForResource :many
SELECT resource_id, day, samples, up, degraded, down, uptime_ratio, computed_at
FROM uptime_daily_agg
WHERE resource_id = $1
  AND day BETWEEN $2 AND $3
ORDER BY day ASC
`

type FindUptimeDailyAggForResourceParams struct {
	ResourceID string      `json:"resource_id"`
	Day        pgtype.Date `json:"day"`
	Day_2      pgtype.Date `json:"day_2"`
}

func (q *Queries) FindUptimeDailyAggForResource(ctx context.Context, arg FindUptimeDailyAggForResourceParams) ([]UptimeDailyAgg, error) {
	rows, err := q.db.Query(ctx, findUptimeDailyAggForResource, arg.ResourceID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeDailyAgg{}
	for rows.Next() {
		var i UptimeDailyAgg
		if err := rows.Scan(
			&i.ResourceID,
			&i.Day,
			&i.Samples,
			&i.Up,
			&i.Degraded,
			&i.Down,
			&i.UptimeRatio,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUptimeDailyAggRange = `-- name: FindUptimeDailyAggRange :many
SELECT resource_id, day, samples, up, degraded, down, uptime_ratio, computed_at
FROM uptime_daily_agg
WHERE resource_id = ANY($1::text[])
  AND day BETWEEN $2 AND $3
ORDER BY day ASC
`

type FindUptimeDailyAggRangeParams struct {
	ResourceIds []string    `json:"resource_ids"`
	FromDay     pgtype.Date `json:"from_day"`
	ToDay       pgtype.Date `json:"to_day"`
}

func (q *Queries) FindUptimeDailyAggRange(ctx context.Context, arg FindUptimeDailyAggRangeParams) ([]UptimeDailyAgg, error) {
	rows, err := q.db.Query(ctx, findUptimeDailyAggRange, arg.ResourceIds, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeDailyAgg{}
	for rows.Next() {
		var i UptimeDailyAgg
		if err := rows.Scan(
			&i.ResourceID,
			&i.Day,
			&i.Samples,
			&i.Up,
			&i.Degraded,
			&i.Down,
			&i.UptimeRatio,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUptimeDailyAgg = `-- name: UpsertUptimeDailyAgg :exec
INSERT INTO uptime_daily_agg (
    resource_id, day, samples, up, degraded, down, uptime_ratio, computed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (resource_id, day) DO UPDATE SET
    samples      = EXCLUDED.samples,
    up           = EXCLUDED.up,
    degraded     = EXCLUDED.degraded,
    down         = EXCLUDED.down,
    uptime_ratio = EXCLUDED.uptime_ratio,
    computed_at  = EXCLUDED.computed_at
`

type UpsertUptimeDailyAggParams struct {
	ResourceID  string             `json:"resource_id"`
	Day         pgtype.Date        `json:"day"`
	Samples     int32              `json:"samples"`
	Up          int32              `json:"up"`
	Degraded    int32              `json:"degraded"`
	Down        int32              `json:"down"`
	UptimeRatio pgtype.Numeric     `json:"uptime_ratio"`
	ComputedAt  pgtype.Timestamptz `json:"computed_at"`
}

func (q *Queries) UpsertUptimeDailyAgg(ctx context.Context, arg UpsertUptimeDailyAggParams) error {
	_, err := q.db.Exec(ctx, upsertUptimeDailyAgg,
		arg.ResourceID,
		arg.Day,
		arg.Samples,
		arg.Up,
		arg.Degraded,
		arg.Down,
		arg.UptimeRatio,
		arg.ComputedAt,
	)
	return err
}
