// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, name, hashed_password,
    password_initialized, force_password_change,
    two_factor_enabled, two_factor_secret, two_factor_backup_codes,
    last_login_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, email, name, hashed_password, password_initialized, force_password_change, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID                   string             `json:"id"`
	Email                string             `json:"email"`
	Name                 string             `json:"name"`
	HashedPassword       string             `json:"hashed_password"`
	PasswordInitialized  bool               `json:"password_initialized"`
	ForcePasswordChange  bool               `json:"force_password_change"`
	TwoFactorEnabled     bool               `json:"two_factor_enabled"`
	TwoFactorSecret      string             `json:"two_factor_secret"`
	TwoFactorBackupCodes []byte             `json:"two_factor_backup_codes"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.HashedPassword,
		arg.PasswordInitialized,
		arg.ForcePasswordChange,
		arg.TwoFactorEnabled,
		arg.TwoFactorSecret,
		arg.TwoFactorBackupCodes,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.PasswordInitialized,
		&i.ForcePasswordChange,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.TwoFactorBackupCodes,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, name, hashed_password, password_initialized, force_password_change, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.PasswordInitialized,
		&i.ForcePasswordChange,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.TwoFactorBackupCodes,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, name, hashed_password, password_initialized, force_password_change, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.PasswordInitialized,
		&i.ForcePasswordChange,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.TwoFactorBackupCodes,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $2,
    name = $3,
    hashed_password = $4,
    password_initialized = $5,
    force_password_change = $6,
    two_factor_enabled = $7,
    two_factor_secret = $8,
    two_factor_backup_codes = $9,
    last_login_at = $10,
    updated_at = $11
WHERE id = $1
`

type UpdateUserParams struct {
	ID                   string             `json:"id"`
	Email                string             `json:"email"`
	Name                 string             `json:"name"`
	HashedPassword       string             `json:"hashed_password"`
	PasswordInitialized  bool               `json:"password_initialized"`
	ForcePasswordChange  bool               `json:"force_password_change"`
	TwoFactorEnabled     bool               `json:"two_factor_enabled"`
	TwoFactorSecret      string             `json:"two_factor_secret"`
	TwoFactorBackupCodes []byte             `json:"two_factor_backup_codes"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.HashedPassword,
		arg.PasswordInitialized,
		arg.ForcePasswordChange,
		arg.TwoFactorEnabled,
		arg.TwoFactorSecret,
		arg.TwoFactorBackupCodes,
		arg.LastLoginAt,
		arg.UpdatedAt,
	)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = $2,
    password_initialized = true,
    force_password_change = false
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID             string `json:"id"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	return err
}

const updateUserTwoFactorSecret = `-- name: UpdateUserTwoFactorSecret :exec
UPDATE users
SET two_factor_secret = $2,
    two_factor_enabled = $3
WHERE id = $1
`

type UpdateUserTwoFactorSecretParams struct {
	ID               string `json:"id"`
	TwoFactorSecret  string `json:"two_factor_secret"`
	TwoFactorEnabled bool   `json:"two_factor_enabled"`
}

func (q *Queries) UpdateUserTwoFactorSecret(ctx context.Context, arg UpdateUserTwoFactorSecretParams) error {
	_, err := q.db.Exec(ctx, updateUserTwoFactorSecret, arg.ID, arg.TwoFactorSecret, arg.TwoFactorEnabled)
	return err
}
