package worker

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/denisakp/ogoune/internal/config"
	"github.com/denisakp/ogoune/internal/domain"
	icmppkg "github.com/denisakp/ogoune/internal/icmp"
	"github.com/denisakp/ogoune/internal/monitoring"
	"github.com/denisakp/ogoune/internal/repository"
	"github.com/denisakp/ogoune/internal/service"
	"github.com/hibiken/asynq"
)

const (
	defaultConfirmationInterval = 30
)

func normalizeConfirmationChecks(value int) int {
	if value <= 0 {
		return 1
	}
	return value
}

type incidentManager interface {
	CreateIncident(ctx context.Context, r *domain.Resource, result domain.CheckResult) error
	ResolveIncident(ctx context.Context, r *domain.Resource, result domain.CheckResult) error
	NotifyFlapping(ctx context.Context, r *domain.Resource, transitionCount, windowSeconds, maxDurationMinutes int) error
	NotifyStabilized(ctx context.Context, r *domain.Resource, finalStatus domain.ResourceStatus) error
	SendReminderIfDue(ctx context.Context, r *domain.Resource) error
	FindLatestIncidentForResource(ctx context.Context, resourceID string) (*domain.Incident, error)
}

type confirmationRescheduler interface {
	ScheduleWithInterval(ctx context.Context, resource *domain.Resource, interval time.Duration) error
}

// MonitoringTaskHandler processes monitoring tasks from the Asynq queue.
// It executes health checks and handles status changes with direct service calls.
type MonitoringTaskHandler struct {
	resources    repository.ResourceRepository
	activities   repository.MonitoringActivityRepository
	maintenances repository.MaintenanceRepository
	diagnostics  repository.IncidentDiagnosticsRepository
	executor     *domain.CheckExecutor
	incidents    incidentManager
	components   *service.ComponentService
	scheduler    confirmationRescheduler

	lockMu        sync.Mutex
	resourceLocks map[string]*sync.Mutex
}

// NewMonitoringTaskHandler creates a new monitoring task handler.
func NewMonitoringTaskHandler(
	resources repository.ResourceRepository,
	activities repository.MonitoringActivityRepository,
	maintenances repository.MaintenanceRepository,
	diagnostics repository.IncidentDiagnosticsRepository,
	executor *domain.CheckExecutor,
	incidents *monitoring.IncidentService,
	components *service.ComponentService,
	scheduler confirmationRescheduler,
) *MonitoringTaskHandler {
	return &MonitoringTaskHandler{
		resources:     resources,
		activities:    activities,
		maintenances:  maintenances,
		diagnostics:   diagnostics,
		executor:      executor,
		incidents:     incidents,
		components:    components,
		scheduler:     scheduler,
		resourceLocks: map[string]*sync.Mutex{},
	}
}

func (h *MonitoringTaskHandler) lockForResource(resourceID string) *sync.Mutex {
	h.lockMu.Lock()
	defer h.lockMu.Unlock()

	if lock, exists := h.resourceLocks[resourceID]; exists {
		return lock
	}

	lock := &sync.Mutex{}
	h.resourceLocks[resourceID] = lock
	return lock
}

// ProcessTask processes a monitoring task from the queue.
func (h *MonitoringTaskHandler) ProcessTask(ctx context.Context, task *asynq.Task) error {
	// Parse the task payload
	var payload struct {
		ResourceID string `json:"resource_id"`
		Type       string `json:"type"`
		Target     string `json:"target"`
		Timeout    int    `json:"timeout"`
	}

	if err := json.Unmarshal(task.Payload(), &payload); err != nil {
		return fmt.Errorf("failed to unmarshal task payload: %w", err)
	}

	resourceLock := h.lockForResource(payload.ResourceID)
	resourceLock.Lock()
	defer resourceLock.Unlock()

	// Get the current resource from the database
	resource, err := h.resources.FindByID(ctx, payload.ResourceID)
	if err != nil {
		return fmt.Errorf("failed to find resource %s: %w", payload.ResourceID, err)
	}

	// Skip monitoring if the resource is no longer active
	if !resource.IsActive {
		return nil
	}

	// Store the previous status for state transitions
	previousStatus := resource.Status

	// Execute the health check
	result, err := h.executor.ExecuteCheck(resource)
	if err != nil {
		return fmt.Errorf("failed to execute check for resource %s: %w", resource.ID, err)
	}

	message := fmt.Sprintf("Check %s - Status: %s", resource.Type, result.Status)
	responseTimeMs := 0
	if result.ResponseTime > 0 {
		// Round up to preserve very fast checks (<1ms) as 1ms instead of 0ms.
		responseTimeMs = int((result.ResponseTime + time.Millisecond - 1) / time.Millisecond)
	}
	activity := &domain.MonitoringActivity{
		ResourceID:   resource.ID,
		Message:      message,
		Success:      result.Status == string(domain.StatusUp),
		ResponseTime: responseTimeMs,
		ResponseData: []byte(result.ResponseData),
		// ID will be auto-generated by Base.BeforeCreate with unique ULID
	}
	// Maintenance override: if resource under maintenance, mark activity and skip business transitions
	activeMaintenances, _ := h.maintenances.FindActiveForResource(ctx, resource.ID, time.Now())
	if len(activeMaintenances) > 0 {
		activity.IsMaintenance = true
		if err := h.activities.Create(ctx, activity); err != nil {
			fmt.Printf("Warning: failed to persist monitoring activity (maintenance): %v\n", err)
		}
		// Do not update resource status, failure counts, or incidents during maintenance
		return nil
	}
	if err := h.activities.Create(ctx, activity); err != nil {
		// Log error but continue processing - we don't want to block incident logic
		fmt.Printf("Warning: failed to persist monitoring activity: %v\n", err)
	}

	currentResultStatus := domain.ResourceStatus(result.Status)
	now := time.Now()
	resource.LastChecked = &now
	confirmationChecks := normalizeConfirmationChecks(resource.ConfirmationChecks)
	confirmationInterval := resource.ConfirmationInterval
	if confirmationInterval <= 0 {
		confirmationInterval = defaultConfirmationInterval
	}

	if resource.Status != currentResultStatus && currentResultStatus != domain.StatusFlapping {
		resource.LastStatusTransition = &now
	}

	if handled, err := h.handleFlapping(ctx, resource, previousStatus, currentResultStatus, now, confirmationChecks); err != nil {
		return err
	} else if handled {
		return nil
	}

	switch currentResultStatus {
	case domain.StatusUp:
		// Resource is UP
		if previousStatus == domain.StatusDown {
			// This is a RECOVERY - resource was down, now it's up
			fmt.Printf("[RECOVERY] Resource %s recovered from DOWN to UP (failure_count was: %d)\n", resource.ID, resource.FailureCount)
			if err := h.incidents.ResolveIncident(ctx, resource, result); err != nil {
				fmt.Printf("Warning: failed to resolve incident: %v\n", err)
			}
		}

		// Reset failure count and update status to UP
		resource.FailureCount = 0
		resource.Status = domain.StatusUp
		if err := h.resources.Update(ctx, resource); err != nil {
			return fmt.Errorf("failed to update resource status: %w", err)
		}

		if h.scheduler != nil {
			_ = h.scheduler.ScheduleWithInterval(ctx, resource, time.Duration(resource.Interval)*time.Second)
		}

	case domain.StatusDown:
		// Resource is DOWN - increment failure count and evaluate confirmation window state.
		previousFailureCount := resource.FailureCount
		resource.FailureCount++
		fmt.Printf("[FAILURE] Resource %s failed (failure_count: %d, previous_status: %s)\n", resource.ID, resource.FailureCount, previousStatus)
		resource.Status = domain.StatusDown
		if err := h.resources.Update(ctx, resource); err != nil {
			fmt.Printf("[WARNING] failed to persist failure progression for resource %s; skipping incident creation this cycle and retrying later: %v\n", resource.ID, err)
			if h.scheduler != nil {
				_ = h.scheduler.ScheduleWithInterval(ctx, resource, time.Duration(confirmationInterval)*time.Second)
			}
			break
		}

		// While below threshold, run fast confirmation retries.
		if resource.FailureCount < confirmationChecks {
			if h.scheduler != nil {
				_ = h.scheduler.ScheduleWithInterval(ctx, resource, time.Duration(confirmationInterval)*time.Second)
			}
			break
		}

		// Create incident whenever confirmation is satisfied; incident service prevents duplicates.
		if resource.FailureCount >= confirmationChecks {
			if previousFailureCount < confirmationChecks {
				fmt.Printf("[INCIDENT_TRIGGER] Resource %s reached confirmation threshold (%d failures), attempting incident creation\n", resource.ID, confirmationChecks)
			} else {
				fmt.Printf("[INCIDENT_RECONCILE] Resource %s already above threshold (%d failures), ensuring incident exists\n", resource.ID, confirmationChecks)
			}
			if err := h.incidents.CreateIncident(ctx, resource, result); err != nil {
				fmt.Printf("Warning: failed to create incident at threshold crossing: %v\n", err)
			} else {
				// Enrich diagnostics with ICMP probe results for failed checks.
				cfg := config.Load()
				if cfg.EnableICMP {
					h.enrichIncidentDiagnostics(ctx, resource.ID, resource.Type, resource.Target, result)
				}
			}
		}

		if err := h.incidents.SendReminderIfDue(ctx, resource); err != nil {
			fmt.Printf("Warning: failed to send reminder notification: %v\n", err)
		}

		if h.scheduler != nil {
			_ = h.scheduler.ScheduleWithInterval(ctx, resource, time.Duration(resource.Interval)*time.Second)
		}
	default:
		// Handle other statuses (error, unknown, etc.)
		resource.Status = currentResultStatus
		if err := h.resources.Update(ctx, resource); err != nil {
			return fmt.Errorf("failed to update resource status: %w", err)
		}
	}

	// Notify component state changes (best-effort)
	if h.components != nil && resource.ComponentID != nil {
		_ = h.components.RecalculateAndNotify(ctx, *resource.ComponentID)
	}

	return nil
}

func (h *MonitoringTaskHandler) handleFlapping(ctx context.Context, resource *domain.Resource, previousStatus, currentResultStatus domain.ResourceStatus, now time.Time, confirmationChecks int) (bool, error) {
	if currentResultStatus != domain.StatusUp && currentResultStatus != domain.StatusDown {
		return false, nil
	}

	cfg := config.Load()
	flapEnabled := resource.FlapDetectionEnabled
	if !flapEnabled && resource.FlapThreshold == 0 && resource.FlapWindowSeconds == 0 && resource.FlapMaxDurationMinutes == 0 {
		flapEnabled = cfg.FlapDetectionEnabled
	}
	flapThreshold := resource.FlapThreshold
	if flapThreshold <= 0 {
		flapThreshold = cfg.FlapThreshold
	}
	flapWindowSeconds := resource.FlapWindowSeconds
	if flapWindowSeconds <= 0 {
		flapWindowSeconds = cfg.FlapWindowSeconds
	}
	flapMaxDurationMinutes := resource.FlapMaxDurationMinutes
	if flapMaxDurationMinutes <= 0 {
		flapMaxDurationMinutes = cfg.FlapMaxDurationMinutes
	}

	detector := monitoring.NewFlapDetector(h.activities, monitoring.FlapConfig{
		Enabled:            flapEnabled,
		Threshold:          flapThreshold,
		WindowSeconds:      flapWindowSeconds,
		MaxDurationMinutes: flapMaxDurationMinutes,
	})
	transitions, err := detector.Evaluate(ctx, resource.ID, now.Add(-time.Duration(flapWindowSeconds)*time.Second))
	if err != nil {
		return false, fmt.Errorf("failed to evaluate flapping state: %w", err)
	}

	if transitions >= flapThreshold {
		if previousStatus == domain.StatusFlapping {
			if detector.ShouldForceIncident(resource.FlapStartedAt) {
				resource.FlapStartedAt = nil
				resource.Status = currentResultStatus
				resource.LastStatusTransition = &now
				if currentResultStatus == domain.StatusDown {
					resource.FailureCount = confirmationChecks - 1
				}
				return false, nil
			}

			resource.Status = domain.StatusFlapping
			resource.FailureCount = 0
			if err := h.resources.Update(ctx, resource); err != nil {
				return true, fmt.Errorf("failed to persist flapping resource state: %w", err)
			}
			if h.scheduler != nil {
				_ = h.scheduler.ScheduleWithInterval(ctx, resource, time.Duration(resource.Interval)*time.Second)
			}
			return true, nil
		}

		resource.Status = domain.StatusFlapping
		resource.FlapStartedAt = &now
		resource.FailureCount = 0
		if err := h.resources.Update(ctx, resource); err != nil {
			return true, fmt.Errorf("failed to persist flapping entry state: %w", err)
		}
		if err := h.incidents.NotifyFlapping(ctx, resource, transitions, flapWindowSeconds, flapMaxDurationMinutes); err != nil {
			fmt.Printf("Warning: failed to dispatch flapping notification: %v\n", err)
		}
		if h.scheduler != nil {
			_ = h.scheduler.ScheduleWithInterval(ctx, resource, time.Duration(resource.Interval)*time.Second)
		}
		return true, nil
	}

	if previousStatus == domain.StatusFlapping {
		resource.FlapStartedAt = nil
		resource.Status = currentResultStatus
		resource.LastStatusTransition = &now
		if currentResultStatus == domain.StatusDown {
			resource.FailureCount = confirmationChecks - 1
		} else {
			resource.FailureCount = 0
		}
		if err := h.incidents.NotifyStabilized(ctx, resource, currentResultStatus); err != nil {
			fmt.Printf("Warning: failed to dispatch stabilization notification: %v\n", err)
		}
	}

	return false, nil
}

// persistIncidentDiagnostics builds and stores diagnostic information for an incident.
// It captures rich context about what failed to help users debug issues.
// If diagnostics fail to persist, it logs the error but doesn't fail the incident creation.
func (h *MonitoringTaskHandler) persistIncidentDiagnostics(ctx context.Context, resource *domain.Resource, resourceRecord *domain.Resource, result domain.CheckResult) error {
	// Fetch the most recent active incident for this resource
	incidents, err := h.resources.FindByID(ctx, resource.ID)
	if err != nil {
		return fmt.Errorf("failed to fetch resource for incident lookup: %w", err)
	}

	if len(incidents.Incidents) == 0 {
		return fmt.Errorf("no incidents found for resource %s", resource.ID)
	}

	// Get the most recent incident (should be the one just created)
	latestIncident := incidents.Incidents[len(incidents.Incidents)-1]
	if latestIncident.ResolvedAt != nil {
		// Skip if already resolved (shouldn't happen, but guard anyway)
		return nil
	}

	// Build diagnostics from check result
	diag := BuildIncidentDiagnostics(latestIncident.ID, result, resourceRecord)

	// Persist to database
	if _, err := h.diagnostics.Create(ctx, diag); err != nil {
		return fmt.Errorf("failed to create incident diagnostics: %w", err)
	}

	fmt.Printf("Persisted diagnostics for incident %s\n", latestIncident.ID)
	return nil
}

// enrichIncidentDiagnostics enriches incident diagnostics with ICMP probe results.
// This runs immediately after incident creation for a DOWN check.
// For non-ICMP monitors, it runs one active probe with fixed 2s timeout.
// For ICMP monitors, it reuses the existing check result and never probes again.
func (h *MonitoringTaskHandler) enrichIncidentDiagnostics(ctx context.Context, resourceID string, resourceType domain.ResourceType, target string, result domain.CheckResult) {
	// Use a bounded context for enrichment work.
	enrichCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	latestIncident, err := h.incidents.FindLatestIncidentForResource(enrichCtx, resourceID)
	if err != nil {
		fmt.Printf("[ENRICHMENT] Failed to fetch latest incident for resource %s: %v\n", resourceID, err)
		return
	}

	if latestIncident.ResolvedAt != nil {
		// Skip if already resolved
		return
	}

	// Query diagnostics for this incident
	diag, err := h.diagnostics.FindByIncidentID(enrichCtx, latestIncident.ID)
	if err != nil {
		fmt.Printf("[ENRICHMENT] Failed to fetch diagnostics for incident %s: %v\n", latestIncident.ID, err)
		return
	}

	if diag == nil {
		fmt.Printf("[ENRICHMENT] No diagnostics found for incident %s\n", latestIncident.ID)
		return
	}

	// Call enricher (fixed 2s timeout for active probes)
	enrichment := icmppkg.Enrich(resourceType, target, result)

	// Merge enrichment results into diagnostics
	diag.WithICMP(enrichment.ICMPAvailable, enrichment.ICMPReachable, enrichment.ICMPRTTMs, enrichment.RootCauseHint)

	// Persist enriched diagnostics
	if err := h.diagnostics.Update(enrichCtx, diag); err != nil {
		fmt.Printf("[ENRICHMENT] Failed to update diagnostics for incident %s: %v\n", latestIncident.ID, err)
		return
	}

	fmt.Printf("[ENRICHMENT] Enriched diagnostics for incident %s (hint: %s)\n", latestIncident.ID, enrichment.RootCauseHint)
}
